# ==================== CNCL-6: `5dive council` (v0.11) ====================
# Standalone deliberation council. The engine + CLI are node modules (src/council/
# engine.mjs + cli.mjs); this bundle ships as ONE bash file, so they are embedded
# below and materialized to a temp dir at call time — the same self-contained
# pattern as `memory search`. This file is GENERATED by src/council/gen_cmd.mjs
# from those two canonical sources; edit the .mjs (or the template) and re-run the
# generator, never this embedded copy. Drift is caught by tests/council_cli_contract.mjs.
#
# Ports the four tested prototypes (convene/verdict, gate-clear map, loop+node,
# standing benches + tamper-evident receipt). Model calls go through the A-with-seam
# adapter (COUNCIL_API_KEY / COUNCIL_BASE_URL); COUNCIL_MOCK=1 runs offline.

COUNCIL_DIR="${STATE_DIR}/council"
COUNCIL_REGISTRY="${COUNCIL_DIR}/benches.json"
COUNCIL_RECEIPTS="${COUNCIL_DIR}/receipts"
COUNCIL_GENESIS="${COUNCIL_DIR}/genesis.json"
COUNCIL_LINEAGE="${COUNCIL_DIR}/lineage.jsonl"

_council_help() {
  cat >&2 <<'COUNCIL_HELP'
5dive council — standalone deliberation council (v0.11)

  5dive council init --seats=<a:chair,b,c,...> --threshold=<majority|all|N|a/b> --veto=<principal>
      Human-seed the primary Council ONCE (sudo-gated, fail-closed if already initialized;
      --force re-seeds and the re-seed is logged in the lineage). The veto principal must be
      RESOLVABLE (human:<agent> -> that agent's paired human, or tg:<user_id>) or init refuses
      it. The genesis record is sealed on the root gate-proof rail and hash-chained into
      ${COUNCIL_LINEAGE}. Principle: an agent must not bootstrap its own governance body.

  5dive council lineage [verify|ls]
      Verify the sealed genesis lineage (re-seal each record, compare digests, check the
      hash-chain) or list it. `verify` fails closed on any tamper or broken link.

  5dive council convene "<question>" [--seats=a,b,c] [--mode=quick|deliberate|adversarial]
                                     [--bench=<name>] [--class=<decisionClass>]
                                     [--threshold=<n>]
                                     [--timeout=120] [--idle-secs=5] [--poll-secs=2] [--standalone]
      Convene a council over a question. By DEFAULT (CNCL-7) it DISPATCHES the question
      to the real seated agents — each seat votes via its OWN harness over the
      `5dive agent ask` rail, no shared model key. A seat that times out or replies
      without a COUNCIL-VOTE line is a recorded ABSTAIN; a convene that falls below
      quorum returns no verdict and auto-escalates with a human brief. The first round
      is BLIND (no seat sees another before its own vote); adversarial adds a rebuttal
      round, recorded separately. Emits an auditable verdict (deterministic tally over
      the current roster) and a tamper-evident, root-signed receipt. On a primary-council
      PASS it also OFFERS the founder veto to the genesis principal (CNCL-9, non-blocking):
      the pass stands, the receipt stamps executeAfter + a one-time tap nonce, and a ping
      fires. Defaults to the 5-seat standing Council. --standalone selects the deferred
      single-key modelCall seam instead of dispatch.
      (A veto can NEVER be asserted from a CLI string — `--veto-by` is refused; see below.)

  5dive council veto exercise --receipt=<sealed digest> --nonce=<tap nonce>
                              [--tier=hold|posthoc] [--reason=<why>]
      Exercise the founder veto on a sealed pass — the authenticated tap. The one-time
      nonce (minted at seal, bound to the offered recipient) authenticates it; `hold`
      (within veto_hold, default 15m) flips the pass to BLOCKED before execution,
      `posthoc` (until veto_posthoc, default 48h) flips it and flags an unwind. The flip
      is a NEW root-sealed record hash-chained to the original verdict digest; the
      original receipt is never mutated. Tier is auto-derived from the clock if omitted.

  5dive council bench ls
  5dive council bench show <name>
  5dive council bench add  <name> --seats=a:lens|b:lens [--mode=] [--threshold=] [--desc=]
  5dive council bench rm   <name>
      Manage the persisted, editable registry of standing benches (built-ins:
      council, ship, brand, security — fail-closed on an unknown name; add/rm are
      privileged governance writes and need sudo).

  Add --json for a machine envelope. The default dispatch path needs NO model key
  (each seat uses its own harness). The --standalone seam uses COUNCIL_API_KEY
  (A-with-seam; BYO/OpenRouter via COUNCIL_BASE_URL). COUNCIL_MOCK=1 runs a
  deterministic offline council (no key, no network, no agent dispatch) for tests + smoke.
COUNCIL_HELP
}

_council_write_runtime() {
  local dir="$1"
  cat > "$dir/engine.mjs" <<'COUNCIL_ENGINE_MJS'
__ENGINE_MJS__
COUNCIL_ENGINE_MJS
  cat > "$dir/cli.mjs" <<'COUNCIL_CLI_MJS'
__CLI_MJS__
COUNCIL_CLI_MJS
}

# CNCL-8: resolve a veto PRINCIPAL to a concrete recipient id (fail-closed: echoes
# nothing if it can't resolve, and init then refuses). Supported forms:
#   human:<agent>  -> that agent's paired human (access.json allowFrom[0]) — e.g.
#                     human:main resolves to the human paired to @agent-main's bot.
#   tg:<digits> | <digits>  -> a literal Telegram user_id.
# An agent can only resolve principals that already exist as paired channels; it cannot
# invent a recipient. This is the "resolvable principal" invariant from the redesign.
_council_resolve_principal() {
  local p="$1"
  case "$p" in
    tg:*) local id="${p#tg:}"; [[ "$id" =~ ^[0-9]+$ ]] && printf '%s' "$id"; return 0 ;;
    human:*)
      local name="${p#human:}"
      [[ -n "$name" ]] || return 0
      _task_agent_channel "$name" >/dev/null 2>&1 || return 0
      [[ -n "${TASK_CH_ACCESS:-}" && -r "$TASK_CH_ACCESS" ]] || return 0
      jq -r '(.allowFrom // [])[0] // empty' "$TASK_CH_ACCESS" 2>/dev/null
      return 0 ;;
    *) [[ "$p" =~ ^[0-9]+$ ]] && printf '%s' "$p"; return 0 ;;
  esac
}

# CNCL-9: SHA-256 hex of a string (the nonce-digest primitive; seal stores the digest, exercise
# hashes the presented nonce and compares). Empty on a missing sha256sum (fail-closed downstream).
_council_sha256() { printf '%s' "${1:-}" | sha256sum 2>/dev/null | awk '{print $1}'; }

# CNCL-9 (main gate amendment 3): durable audit trail for REFUSED veto attempts — a forged
# `--veto-by` CLI string on convene, or a nonce/recipient mismatch on exercise. "refused + logged"
# must mean a real line on disk a test can assert, not just an stderr message. The file is
# attacker-triggerable, so it is root-owned 0600 (never group-readable).
_council_veto_audit() {
  local event="$1" ref="${2:-}" subject="${3:-}"
  mkdir -p "$COUNCIL_DIR" 2>/dev/null || true
  [[ -w "$COUNCIL_DIR" || -f "${COUNCIL_DIR}/veto-audit.jsonl" ]] || return 0
  local line
  line="$(jq -cn --arg e "$event" --arg r "$ref" --arg s "$subject" --arg u "$(id -un 2>/dev/null)" \
    '{ts:(now|todate? // ""), event:$e, ref:$r, subject:$s, by:$u, kind:"veto-refused"}' 2>/dev/null)" || return 0
  printf '%s\n' "$line" >> "${COUNCIL_DIR}/veto-audit.jsonl" 2>/dev/null || true
  chmod 0600 "${COUNCIL_DIR}/veto-audit.jsonl" 2>/dev/null || true
  [[ "$(id -u)" -eq 0 ]] && chown root:root "${COUNCIL_DIR}/veto-audit.jsonl" 2>/dev/null || true
  return 0
}

# CNCL-9: fire the founder veto ping at seal (non-blocking, best-effort). Records a durable ping
# entry (so "the ping fired" is observable + testable) and attempts a live notify to the resolved
# recipient. The tappable button + its callback -> `council veto exercise` is the telegram-plugin
# leg that pairs with a live genesis; this CLI leg guarantees the recipient is notified with the
# receipt handle + the one-time nonce the tap must present.
_council_veto_ping() {
  local resolved="$1" digest="$2" execute_after="$3" nonce="$4"
  mkdir -p "$COUNCIL_DIR" 2>/dev/null || true
  # CNCL-9 (main gate amendment 2): the pings audit records ONLY the nonce DIGEST, never the raw
  # bearer token. The raw nonce leaves this process solely via the founder delivery leg (_tg_send)
  # below. The file is additionally locked 0600 root so a group-claude agent cannot read even the
  # digest+recipient trail.
  local nonce_digest; nonce_digest="$(_council_sha256 "$nonce")"
  local line
  line="$(jq -cn --arg r "$resolved" --arg d "$digest" --arg ea "$execute_after" --arg nd "$nonce_digest" \
    '{ts:(now|todate? // ""), recipient:$r, receiptDigest:$d, executeAfter:$ea, nonceDigest:$nd, kind:"veto-offer"}' 2>/dev/null)" || line=""
  if [[ -n "$line" && -w "$COUNCIL_DIR" ]]; then
    printf '%s\n' "$line" >> "${COUNCIL_DIR}/veto-pings.jsonl" 2>/dev/null || true
    chmod 0600 "${COUNCIL_DIR}/veto-pings.jsonl" 2>/dev/null || true
    [[ "$(id -u)" -eq 0 ]] && chown root:root "${COUNCIL_DIR}/veto-pings.jsonl" 2>/dev/null || true
  fi
  # Founder delivery leg: the RAW one-time nonce is delivered ONLY here, to the resolved recipient.
  # A missing rail must never fail the (already-sealed) convene. Skipped under MOCK (offline tests
  # exercise the durable audit above without touching a live telegram rail).
  if [[ -z "${COUNCIL_MOCK:-}" ]] && command -v _tg_send >/dev/null 2>&1; then
    _tg_send "$resolved" "Council veto offer — a pass sealed (${digest:0:12}…). Execution holds until ${execute_after}. Tap to VETO (nonce ${nonce}), or ignore to let it proceed." >/dev/null 2>&1 || true
  fi
  return 0
}

# CNCL-9: authenticated founder veto EXERCISE (the confirmed tap). bash owns authentication (the
# one-time nonce minted at seal, bound to the offered recipient); cli owns the fail-closed flip +
# the chained record. The original convene receipt is NEVER re-sealed or mutated — the veto is a
# NEW root-sealed record hash-chained to the original verdict digest.
#   5dive council veto exercise --receipt=<sealed digest> --nonce=<tap nonce> [--tier=hold|posthoc]
#                               [--reason=<why>]
_council_veto() {
  local dir="$1"; shift
  [[ "${1:-}" == "exercise" ]] || fail "$E_USAGE" "unknown veto action: ${1:-} (exercise)"
  shift
  local rcpt_digest="" nonce="" tier="" reason=""
  local a
  for a in "$@"; do
    case "$a" in
      --receipt=*) rcpt_digest="${a#--receipt=}" ;;
      --nonce=*)   nonce="${a#--nonce=}" ;;
      --tier=*)    tier="${a#--tier=}" ;;
      --reason=*)  reason="${a#--reason=}" ;;
    esac
  done
  [[ -n "$rcpt_digest" ]] || fail "$E_USAGE" "veto exercise needs --receipt=<sealed convene receipt digest>"
  [[ -n "$nonce" ]]       || fail "$E_PERMISSION" "veto exercise needs --nonce=<the one-time tap nonce> (an unauthenticated exercise is refused)"

  # Locate the sealed convene receipt by its digest.
  local rf found=""
  if [[ -d "$COUNCIL_RECEIPTS" ]]; then
    for rf in "$COUNCIL_RECEIPTS"/*.json; do
      [[ -f "$rf" ]] || continue
      [[ "$(jq -r '.sealedDigest // empty' "$rf" 2>/dev/null)" == "$rcpt_digest" ]] && { found="$rf"; break; }
    done
  fi
  [[ -n "$found" ]] || fail "$E_GENERIC" "no sealed council receipt with digest ${rcpt_digest:0:16}… (fail-closed)"

  # HARDENING (main gate): before trusting ANY field of the receipt (.verdict / .vetoNonceDigest /
  # .vetoOffer), re-seal its canonical bytes on the gate-proof rail and confirm they match the
  # stored sealedDigest. A receipt whose body was edited (swapped nonce digest, flipped verdict,
  # widened offer) fails HERE — fail-closed — so the authenticated-tap path only ever acts on a
  # byte-intact receipt.
  local rcanon rseal=""
  rcanon="$(jq -r '.canonical // empty' "$found" 2>/dev/null)"
  [[ -n "$rcanon" ]] || fail "$E_GENERIC" "sealed receipt carries no canonical bytes to re-verify (fail-closed)"
  if [[ "$(id -u)" -eq 0 ]]; then rseal="$(printf '%s' "$rcanon" | cmd_gate_proof_sign_stdin 2>/dev/null)" || rseal=""
  else rseal="$(printf '%s' "$rcanon" | sudo -n 5dive gate-proof sign 2>/dev/null)" || rseal=""; fi
  [[ -n "$rseal" ]] || fail "$E_GENERIC" "cannot re-seal the receipt canonical (need root + an enforce key) — refusing to trust an unverifiable receipt (fail-closed)"
  [[ "$rseal" == "$rcpt_digest" ]] || { _council_veto_audit "receipt-tampered" "$rcpt_digest"; fail "$E_PERMISSION" "receipt canonical does not re-seal to its sealedDigest — the receipt was tampered (refused + logged, fail-closed)"; }

  # AUTHENTICATE the tap: sha256(presented nonce) must equal the nonce DIGEST minted for THIS offer.
  # The raw nonce is never stored server-side (only its digest rides in the receipt), so a
  # group-readable receipt no longer leaks the bearer token (main gate amendment 2).
  # CNCL-9 AMENDMENT (main gate): the nonce digest + executeAfter + stampedAt are read from the
  # VERIFIED canonical (which just re-sealed to the stored digest above), NEVER from the raw wrapper.
  # The wrapper's `.vetoNonceDigest`/`.executeAfter` are unsealed and forgeable; before this fix the
  # re-seal check only covered `.canonical`, so swapping `.vetoNonceDigest` to sha256(attacker-nonce)
  # passed the check and let an attacker exercise with a chosen nonce. Now those fields ride INSIDE
  # `.canonical` (seal-augment folded them in at seal time), so any edit breaks the re-seal above and
  # the values used here come from the byte-intact bytes. offer_resolved/principal stay wrapper-read:
  # exercise still requires the sealed-digest-matching nonce (the bearer token), which only the
  # founder holds, so a widened offer cannot help an attacker who lacks that nonce.
  local stored_nonce_digest offer_resolved offer_principal execute_after stamped_at verdict_json binding_json
  binding_json="$(printf '%s' "$rcanon" | node "$dir/cli.mjs" read-binding --canonical=- 2>/dev/null)" || binding_json=""
  stored_nonce_digest="$(printf '%s' "$binding_json" | jq -r '.nonceDigest // empty' 2>/dev/null)"
  execute_after="$(printf '%s' "$binding_json" | jq -r '.executeAfter // empty' 2>/dev/null)"
  stamped_at="$(printf '%s' "$binding_json" | jq -r '.stampedAt // empty' 2>/dev/null)"
  offer_resolved="$(jq -r '.verdict.vetoOffer.resolved // empty' "$found" 2>/dev/null)"
  offer_principal="$(jq -r '.verdict.vetoOffer.principal // empty' "$found" 2>/dev/null)"
  [[ -n "$stored_nonce_digest" && -n "$offer_resolved" ]] || fail "$E_GENERIC" "receipt carries no veto offer to exercise (fail-closed)"
  local presented_digest; presented_digest="$(_council_sha256 "$nonce")"
  [[ -n "$presented_digest" && "$presented_digest" == "$stored_nonce_digest" ]] || { _council_veto_audit "nonce-mismatch" "$rcpt_digest" "$offer_resolved"; fail "$E_PERMISSION" "veto nonce mismatch — this tap is not the one offered to the founder principal (refused + logged)"; }

  # Derive the tier from the clock unless explicitly given: within the HOLD window -> hold; after it
  # (up to veto_posthoc) -> posthoc; beyond posthoc -> refused (the veto has expired, pass is final).
  local now_e ea_e st_e posthoc="${COUNCIL_VETO_POSTHOC_SECS:-172800}"
  [[ "$posthoc" =~ ^[0-9]+$ ]] || posthoc=172800
  now_e="$(date -u +%s)"
  ea_e="$(date -u -d "$execute_after" +%s 2>/dev/null || echo 0)"
  st_e="$(date -u -d "$stamped_at" +%s 2>/dev/null || echo 0)"
  if [[ -z "$tier" ]]; then
    if (( ea_e > 0 && now_e < ea_e )); then tier="hold"; else tier="posthoc"; fi
  fi
  if [[ "$tier" == "posthoc" ]] && (( st_e > 0 && now_e > st_e + posthoc )); then
    fail "$E_GENERIC" "veto window expired (past veto_posthoc=${posthoc}s from seal) — the pass is final, no override (fail-closed)"
  fi

  verdict_json="$(jq -c '.verdict' "$found" 2>/dev/null)"
  local stamped; stamped="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  local vraw
  vraw="$(node "$dir/cli.mjs" veto exercise \
    --orig-digest="$rcpt_digest" --by="$offer_principal" --resolved="$offer_resolved" \
    --tier="$tier" --reason="$reason" --verdict="$verdict_json" --stamped-at="$stamped")" || return $?

  # Root-seal the chained veto record and hash-chain it onto the original verdict digest. Same rail
  # + discipline as the genesis lineage; the original receipt bytes are left untouched.
  local canonical vdigest=""
  canonical="$(printf '%s' "$vraw" | jq -r '.canonical // empty')"
  if [[ -n "$canonical" ]]; then
    if [[ "$(id -u)" -eq 0 ]]; then vdigest="$(printf '%s' "$canonical" | cmd_gate_proof_sign_stdin)" || vdigest=""
    else vdigest="$(printf '%s' "$canonical" | sudo -n 5dive gate-proof sign 2>/dev/null)" || vdigest=""; fi
  fi
  [[ -n "$vdigest" ]] || fail "$E_GENERIC" "could not seal the veto record on the gate-proof rail (need root + an enforce key) — veto NOT recorded"

  if [[ -w "$COUNCIL_RECEIPTS" ]]; then
    printf '%s' "$vraw" | jq --arg d "$vdigest" --arg p "$rcpt_digest" --arg s "$stamped" \
      '{kind:"veto", stampedAt:$s, sealedDigest:$d, prevDigest:$p, tier: .vetoRecord.tier, unwindRequired: .vetoRecord.unwindRequired, record: .vetoRecord, flippedVerdict: .flippedVerdict, canonical: .canonical}' \
      > "${COUNCIL_RECEIPTS}/veto-${stamped//:/-}.json" 2>/dev/null || true
  fi
  # Append to the tamper-evident lineage. CNCL-9 (main gate amendment 1): the jsonl WRAPPER must
  # hash-chain to the LINEAGE head (prevDigest = the last lineage entry's digest, seq = last+1) so
  # `council lineage verify` stays green after a veto. The veto->original-verdict link is NOT lost:
  # it already rides INSIDE the signed record (record.prevDigest = the original verdict digest,
  # sealed in the canonical bytes). We keep it in the wrapper too, as `origDigest`, for readers.
  if [[ -f "$COUNCIL_LINEAGE" || -w "$COUNCIL_DIR" ]]; then
    local l_prev="" l_seq=0
    if [[ -f "$COUNCIL_LINEAGE" ]]; then
      l_prev="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.digest // ""' 2>/dev/null)"
      local l_last; l_last="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.seq // -1' 2>/dev/null)"
      [[ "$l_last" =~ ^[0-9]+$ ]] && l_seq=$((l_last+1))
    fi
    printf '%s' "$vraw" | jq -c --arg d "$vdigest" --arg lp "$l_prev" --arg od "$rcpt_digest" --arg sq "$l_seq" --arg s "$stamped" \
      '{seq: ($sq|tonumber), kind:"veto", stampedAt:$s, digest:$d, prevDigest:$lp, origDigest:$od, canonical: .canonical, record: .vetoRecord}' \
      >> "$COUNCIL_LINEAGE" 2>/dev/null || true
  fi

  if (( JSON_MODE )); then
    printf '%s' "$vraw" | jq --arg d "$vdigest" --arg p "$rcpt_digest" '{ok:true, data: (. + {sealedDigest:$d, prevDigest:$p})}'
  else
    echo "veto:         EXERCISED (${tier}) by ${offer_principal}"
    echo "disposition:  blocked  (pass overruled; original verdict left sealed + immutable)"
    [[ "$tier" == "posthoc" ]] && echo "unwind:       REQUIRED — reversible work must be manually unwound (v0.11)"
    echo "chained:      veto ${vdigest:0:16}… -> verdict ${rcpt_digest:0:16}…"
  fi
}

_council_init_or_lineage() {
  local sub="$1" dir="$2"; shift 2
  mkdir -p "$COUNCIL_DIR" 2>/dev/null || true

  if [[ "$sub" == "lineage" ]]; then
    local action="${1:-verify}"
    if [[ ! -f "$COUNCIL_LINEAGE" ]]; then
      if (( JSON_MODE )); then printf '%s\n' '{"ok":true,"data":{"entries":[],"chain":"empty"}}'; else echo "lineage: (empty — council not yet initialized)"; fi
      return 0
    fi
    if [[ "$action" == "ls" ]]; then
      if (( JSON_MODE )); then jq -s '{ok:true,data:{entries:.}}' "$COUNCIL_LINEAGE"
      else jq -r '"seq \(.seq)\t\(.kind)\t\(.stampedAt)\tdigest=\(.digest[0:16])…\tprev=\((.prevDigest // "")[0:8])"' "$COUNCIL_LINEAGE"; fi
      return 0
    fi
    # verify: re-seal each canonical on the ROOT rail, compare to the stored digest, and
    # check the prevDigest hash-chain links back to genesis. Fails closed on any mismatch.
    local ok=1 prev="" line seq canonical stored kind computed n=0
    while IFS= read -r line; do
      [[ -n "$line" ]] || continue
      n=$((n+1))
      seq="$(printf '%s' "$line" | jq -r '.seq')"
      kind="$(printf '%s' "$line" | jq -r '.kind')"
      stored="$(printf '%s' "$line" | jq -r '.digest')"
      canonical="$(printf '%s' "$line" | jq -r '.canonical')"
      local lprev; lprev="$(printf '%s' "$line" | jq -r '.prevDigest // ""')"
      if [[ "$lprev" != "$prev" ]]; then echo "lineage: BROKEN CHAIN at seq $seq (prevDigest=$lprev, expected $prev)" >&2; ok=0; fi
      if [[ "$(id -u)" -eq 0 ]]; then computed="$(printf '%s' "$canonical" | cmd_gate_proof_sign_stdin 2>/dev/null)"; else computed="$(printf '%s' "$canonical" | sudo -n 5dive gate-proof sign 2>/dev/null)"; fi
      if [[ -z "$computed" ]]; then echo "lineage: cannot re-seal seq $seq (no gate-proof key / not root)" >&2; ok=0
      elif [[ "$computed" != "$stored" ]]; then echo "lineage: TAMPERED seq $seq ($kind) — digest mismatch" >&2; ok=0; fi
      prev="$stored"
    done < "$COUNCIL_LINEAGE"
    if (( ok )); then
      if (( JSON_MODE )); then printf '%s\n' "{\"ok\":true,\"data\":{\"verified\":true,\"entries\":$n}}"; else echo "lineage: VERIFIED ($n entr$([[ $n -eq 1 ]] && echo y || echo ies), chain intact)"; fi
      return 0
    else
      if (( JSON_MODE )); then printf '%s\n' '{"ok":false,"error":"lineage verification failed"}'; fi
      return "$E_GENERIC"
    fi
  fi

  # ---- init (sudo-gated, one-time) ----------------------------------------
  if [[ ! -w "$COUNCIL_DIR" ]]; then
    fail "$E_PERMISSION" "council init seeds the governance body — it writes ${COUNCIL_DIR} (root-owned) and must be human/sudo-run: sudo 5dive council init $*"
  fi
  # Resolve the veto principal up front so init refuses an unresolvable one BEFORE any write.
  local principal="" a
  local -a passthru=()
  for a in "$@"; do
    case "$a" in --veto=*) principal="${a#--veto=}" ;; esac
    passthru+=("$a")
  done
  [[ -n "$principal" ]] || fail "$E_USAGE" "council init needs --veto=<principal> (e.g. human:main)"
  local resolved; resolved="$(_council_resolve_principal "$principal")"
  [[ -n "$resolved" ]] || fail "$E_USAGE" "veto principal '$principal' did not resolve to a real recipient — init rejects an unknown principal (fail-closed). Use human:<agent> (a paired agent) or tg:<user_id>."

  local genesis_exists=0; [[ -f "$COUNCIL_GENESIS" ]] && genesis_exists=1
  # hash-chain head: prevDigest + next seq come from the last lineage line.
  local prev_digest="" seq=0
  if [[ -f "$COUNCIL_LINEAGE" ]]; then
    prev_digest="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.digest // ""' 2>/dev/null)"
    local last_seq; last_seq="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.seq // -1' 2>/dev/null)"
    [[ "$last_seq" =~ ^[0-9]+$ ]] && seq=$((last_seq+1))
  fi
  local stamped; stamped="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  local raw
  raw="$(node "$dir/cli.mjs" init "${passthru[@]}" \
    --registry="$COUNCIL_REGISTRY" --veto-resolved="$resolved" \
    --genesis-exists="$genesis_exists" --prev-digest="$prev_digest" --seq="$seq" \
    --stamped-at="$stamped")" || return $?

  # Seal the canonical genesis bytes on the ROOT rail and hash-chain into the lineage. The
  # seal is what makes the roster non-forgeable; the chain makes the whole history verifiable.
  local canonical digest=""
  canonical="$(printf '%s' "$raw" | jq -r '.canonical // empty')"
  if [[ -z "$canonical" ]]; then fail "$E_GENERIC" "init produced no canonical record"; fi
  if [[ "$(id -u)" -eq 0 ]]; then digest="$(printf '%s' "$canonical" | cmd_gate_proof_sign_stdin 2>/dev/null)" || digest=""
  else digest="$(printf '%s' "$canonical" | sudo -n 5dive gate-proof sign 2>/dev/null)" || digest=""; fi
  [[ -n "$digest" ]] || fail "$E_GENERIC" "could not seal the genesis record on the gate-proof rail (need root + an enforce key) — genesis NOT written"

  printf '%s' "$raw" | jq --arg d "$digest" '.genesis + {sealedDigest:$d}' > "$COUNCIL_GENESIS"
  printf '%s' "$raw" | jq -c --arg d "$digest" --arg p "$prev_digest" \
    '{seq: .genesis.seq, kind: "genesis", stampedAt: .genesis.stampedAt, digest: $d, prevDigest: $p, canonical: .canonical, record: .genesis}' \
    >> "$COUNCIL_LINEAGE"

  if (( JSON_MODE )); then
    printf '%s' "$raw" | jq --arg d "$digest" '{ok:true, data: (. + {sealedDigest:$d})}'
  else
    local seats chair
    seats="$(printf '%s' "$raw" | jq -r '.seats | join(", ")')"
    chair="$(printf '%s' "$raw" | jq -r '.chair // "none"')"
    echo "council: initialized (seq $seq)"
    echo "seats:   $seats"
    echo "chair:   $chair"
    echo "veto:    $principal -> $resolved"
    echo "genesis: sealed (${digest:0:16}…) + hash-chained into lineage"
  fi
  return 0
}

cmd_council() {
  command -v node >/dev/null 2>&1 || fail "$E_GENERIC" "5dive council needs node on PATH"
  command -v jq   >/dev/null 2>&1 || fail "$E_GENERIC" "5dive council needs jq on PATH"
  local sub="${1:-}"; [[ $# -gt 0 ]] && shift || true
  case "$sub" in
    ""|-h|--help|help) _council_help; return 0 ;;
    convene|bench|init|lineage|veto) ;;
    *) fail "$E_USAGE" "unknown council command: $sub (convene|bench|init|lineage|veto)" ;;
  esac

  local dir; dir="$(mktemp -d -t 5dive-council.XXXXXX)" || fail "$E_GENERIC" "mktemp failed"
  # shellcheck disable=SC2064
  trap "rm -rf '$dir'" RETURN
  _council_write_runtime "$dir"

  # CNCL-8: council init (human-seeded genesis) + lineage verify -----------
  if [[ "$sub" == "init" || "$sub" == "lineage" ]]; then
    _council_init_or_lineage "$sub" "$dir" "$@"
    return $?
  fi

  # CNCL-9: authenticated founder veto exercise (the confirmed tap) ---------
  if [[ "$sub" == "veto" ]]; then
    _council_veto "$dir" "$@"
    return $?
  fi

  if [[ "$sub" == "bench" ]]; then
    local action="${1:-ls}"
    case "$action" in
      add|rm)
        mkdir -p "$COUNCIL_DIR" 2>/dev/null || true
        if [[ ! -w "$COUNCIL_DIR" ]]; then
          fail "$E_PERMISSION" "editing standing benches writes ${COUNCIL_REGISTRY} (root-owned) — re-run via: sudo 5dive council bench $action $*"
        fi
        ;;
    esac
    # cli.mjs always emits JSON; format it here so text/JSON honor the global contract.
    local braw; braw="$(node "$dir/cli.mjs" bench "$@" --registry="$COUNCIL_REGISTRY")" || return $?
    if (( JSON_MODE )); then
      printf '%s' "$braw" | jq '{ok:true, data: .}'
    elif [[ "$action" == "ls" ]]; then
      printf '%s' "$braw" | jq -r '.benches[] | "  \(.name)\t\(if .builtin then "(built-in)" else "" end)\(if .custom then "(custom)" else "" end)"'
    elif [[ "$action" == "show" ]]; then
      printf '%s' "$braw" | jq -r '"bench:  \(.name)\ndesc:   \(.description)\nmode:   \(.mode)\nseats:  \(.seats | map(.id) | join(", "))"'
    else
      printf '%s' "$braw" | jq -r 'to_entries[0] | "OK — bench \(.value) \(.key)"'
    fi
    return 0
  fi

  # convene ------------------------------------------------------------------
  local stamped; stamped="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  local genesis_exists=0; [[ -f "$COUNCIL_GENESIS" ]] && genesis_exists=1

  # CNCL-9 (main gate amendment 3): a `--veto-by` / `--veto-reason` on convene is a FORGE attempt —
  # an agent trying to assert a veto from a plain CLI string. cli.mjs refuses it (exit 9), but the
  # acceptance says "refused + LOGGED", so we write the durable audit line HERE before dispatch,
  # independent of cli's ordering (the refusal message still comes from cli). A test asserts it.
  local _fa _forge=""
  for _fa in "$@"; do
    case "$_fa" in
      --veto-by=*|--veto-by|--veto-reason=*|--veto-reason)
        _forge="${_forge:+$_forge,}${_fa%%=*}" ;;
    esac
  done
  [[ -n "$_forge" ]] && _council_veto_audit "forge-attempt-veto-by" "convene" "$_forge"

  # CNCL-9: on a PRIMARY-council convene we OFFER the founder veto to the genesis principal. The
  # offer rides inside the sealed receipt; the flip only ever happens later via an authenticated
  # tap (`council veto exercise`). We pass the genesis-resolved principal + the HOLD window (the
  # veto_hold constitution key; env-overridable seam until CNCL-13/14) down to the engine so the
  # offer is recorded on a pass. Ad-hoc panels (no genesis) get no offer.
  local -a veto_args=()
  local veto_hold="${COUNCIL_VETO_HOLD_SECS:-900}"
  [[ "$veto_hold" =~ ^[0-9]+$ ]] || veto_hold=900
  if (( genesis_exists )); then
    local g_principal g_resolved
    g_principal="$(jq -r '.veto.principal // empty' "$COUNCIL_GENESIS" 2>/dev/null)"
    g_resolved="$(jq -r '.veto.resolved // empty' "$COUNCIL_GENESIS" 2>/dev/null)"
    if [[ -n "$g_principal" && -n "$g_resolved" ]]; then
      veto_args=(--veto-principal="$g_principal" --veto-resolved="$g_resolved" --veto-window="$veto_hold")
    fi
  fi

  local raw
  raw="$(node "$dir/cli.mjs" convene "$@" "${veto_args[@]}" --registry="$COUNCIL_REGISTRY" --genesis-exists="$genesis_exists" --stamped-at="$stamped")" || return $?

  # Seal the receipt canonical at the root HMAC rail — a standalone engine has no
  # key, so the seal (via gate-proof) is what makes the verdict tamper-evident. The
  # founder veto + dissent already ride INSIDE the signed bytes (canonicalTranscript).
  local base_canonical canonical digest=""
  base_canonical="$(printf '%s' "$raw" | jq -r '.receipt.canonical // empty')"
  if [[ -n "$base_canonical" ]]; then
    # CNCL-9: if the sealed verdict carries a veto OFFER (a primary-council pass), stamp the HOLD
    # deadline (executeAfter = sealedAt + veto_hold) and mint a one-time tap nonce bound to the
    # offered recipient. AMENDMENT (main gate): mint these BEFORE sealing and FOLD their binding
    # (nonce DIGEST + executeAfter) INTO the canonical via seal-augment, so they are covered by the
    # same HMAC as the rest of the receipt. Pre-amendment they were stamped onto the unsealed
    # wrapper AFTER the seal, so the exercise-time re-seal (which only re-signs `.canonical`) did
    # not cover them and an edited `.vetoNonceDigest` slipped through. A base receipt (no offer)
    # gets no seal-binding line and stays byte-identical to CNCL-6/8.
    local offer_resolved execute_after="" veto_nonce="" veto_nonce_digest=""
    offer_resolved="$(printf '%s' "$raw" | jq -r '.verdict.vetoOffer.resolved // empty' 2>/dev/null)"
    if [[ -n "$offer_resolved" ]]; then
      execute_after="$(date -u -d "$stamped + ${veto_hold} seconds" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo "")"
      veto_nonce="$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
      veto_nonce_digest="$(_council_sha256 "$veto_nonce")"
      canonical="$(printf '%s' "$base_canonical" | node "$dir/cli.mjs" seal-augment --canonical=- --nonce-digest="$veto_nonce_digest" --execute-after="$execute_after")" || canonical="$base_canonical"
    else
      canonical="$base_canonical"
    fi
    if [[ "$(id -u)" -eq 0 ]]; then
      digest="$(printf '%s' "$canonical" | cmd_gate_proof_sign_stdin)" || digest=""
    else
      digest="$(printf '%s' "$canonical" | sudo -n 5dive gate-proof sign 2>/dev/null)" || digest=""
    fi
    if [[ -n "$digest" ]]; then
      mkdir -p "$COUNCIL_RECEIPTS" 2>/dev/null || true
      if [[ -w "$COUNCIL_RECEIPTS" ]]; then
        # Offline-test capture ONLY: when MOCK is on AND a sink path is provided, drop the raw nonce
        # so the bash e2e can present it at exercise. Double-gated on COUNCIL_MOCK (never set in a
        # real convene) + COUNCIL_VETO_NONCE_SINK, so PRODUCTION never writes the raw nonce to disk —
        # in prod it leaves solely via the _tg_send founder delivery leg (main gate amendment 2).
        if [[ -n "$veto_nonce" && -n "${COUNCIL_MOCK:-}" && -n "${COUNCIL_VETO_NONCE_SINK:-}" ]]; then
          ( umask 077; printf '%s\n' "$veto_nonce" > "$COUNCIL_VETO_NONCE_SINK" ) 2>/dev/null || true
        fi
        # The receipt stores the AUGMENTED canonical (with the sealed veto-binding line). The wrapper
        # still surfaces executeAfter + vetoNonceDigest for display/dashboard audit, but exercise no
        # longer TRUSTS them — it reads the binding back out of the verified canonical (fail-closed).
        # The raw nonce never touches the receipt; it is delivered solely to the founder via the ping.
        printf '%s' "$raw" | jq --arg d "$digest" --arg s "$stamped" --arg ea "$execute_after" --arg nd "$veto_nonce_digest" --arg canon "$canonical" \
          '{stampedAt:$s, sealedDigest:$d, council, question, disposition, verdict, canonical: $canon}
           + (if ($ea|length)>0 then {executeAfter:$ea} else {} end)
           + (if ($nd|length)>0 then {vetoNonceDigest:$nd} else {} end)' \
          > "${COUNCIL_RECEIPTS}/${stamped//:/-}.json" 2>/dev/null || true
        # Fire the founder ping at seal (non-blocking, best-effort). Writes the durable digest-only
        # pings audit (0600) always; the live _tg_send notify (which carries the raw nonce) is
        # skipped under MOCK. The tappable button + its callback -> `council veto exercise` routing
        # is the telegram-plugin leg that pairs with a live genesis (post-seed).
        if [[ -n "$offer_resolved" ]]; then
          _council_veto_ping "$offer_resolved" "$digest" "$execute_after" "$veto_nonce" || true
        fi
      fi
    fi
  fi

  if (( JSON_MODE )); then
    printf '%s' "$raw" | jq --arg d "$digest" '{ok:true, data: (. + {sealedDigest: $d})}'
  else
    local council q disp rec tally conf dissent brief
    council="$(printf '%s' "$raw" | jq -r '.council')"
    q="$(printf '%s' "$raw" | jq -r '.question')"
    disp="$(printf '%s' "$raw" | jq -r '.disposition')"
    rec="$(printf '%s' "$raw" | jq -r '.verdict.recommendation')"
    tally="$(printf '%s' "$raw" | jq -r '.verdict.tally | "a\(.approve)/r\(.reject)/e\(.escalate)"')"
    conf="$(printf '%s' "$raw" | jq -r '.verdict.confidence')"
    dissent="$(printf '%s' "$raw" | jq -r '.verdict.dissent // "none"')"
    brief="$(printf '%s' "$raw" | jq -r '.verdict.brief // empty')"
    echo "council:      $council"
    echo "question:     $q"
    echo "disposition:  $disp  (recommendation=$rec, tally=$tally, confidence=$conf)"
    [[ -n "$dissent" && "$dissent" != "none" ]] && echo "dissent:      $dissent"
    [[ -n "$brief" ]] && echo "brief:        $brief"
    if [[ -n "$digest" ]]; then
      echo "receipt:      sealed (${digest:0:16}…)"
    else
      echo "receipt:      unsealed (no gate-proof key / not root — run via sudo to seal)"
    fi
  fi
}

# In-process root seal: reuse the existing gate-proof signer without a re-exec when
# we are already root (keeps the HMAC key handling in one place).
cmd_gate_proof_sign_stdin() { cmd_gate_proof sign; }
