# ==================== CNCL-6: `5dive council` (v0.11) ====================
# Standalone deliberation council. The engine + CLI are node modules (src/council/
# engine.mjs + cli.mjs); this bundle ships as ONE bash file, so they are embedded
# below and materialized to a temp dir at call time — the same self-contained
# pattern as `memory search`. This file is GENERATED by src/council/gen_cmd.mjs
# from those two canonical sources; edit the .mjs (or the template) and re-run the
# generator, never this embedded copy. Drift is caught by tests/council_cli_contract.mjs.
#
# Ports the four tested prototypes (convene/verdict, gate-clear map, loop+node,
# standing benches + tamper-evident receipt). Model calls go through the A-with-seam
# adapter (COUNCIL_API_KEY / COUNCIL_BASE_URL); COUNCIL_MOCK=1 runs offline.

COUNCIL_DIR="${STATE_DIR}/council"
COUNCIL_REGISTRY="${COUNCIL_DIR}/benches.json"
COUNCIL_RECEIPTS="${COUNCIL_DIR}/receipts"
COUNCIL_GENESIS="${COUNCIL_DIR}/genesis.json"
COUNCIL_LINEAGE="${COUNCIL_DIR}/lineage.jsonl"

_council_constitution_path() {
  printf '%s' "${FIVEDIVE_CONSTITUTION_FILE:-${STATE_DIR}/5dive.md}"
}

# Parse the machine-enforced YAML frontmatter through the same loader the tally
# engine uses. Kept as a function (not a source-time global) so test/runtime
# STATE_DIR overrides resolve correctly.
_council_constitution_json() {
  command -v node >/dev/null 2>&1 || return 1
  local dir rc=0
  dir="$(mktemp -d -t 5dive-constitution.XXXXXX)" || return 1
  _council_write_runtime "$dir"
  node "$dir/cli.mjs" constitution --path="$(_council_constitution_path)" || rc=$?
  rm -rf "$dir"
  return "$rc"
}

_council_hard_gate_rx() {
  _council_constitution_json | jq -r '.hardGateRegex'
}

# CNCL-15 — constitution integrity. The AUTHORITY is the digest sealed in the newest genesis/
# amendment lineage record, NOT the on-disk 5dive.md (the file is forgeable, the chain is not).
# Genesis/amend seal it with `sha256sum`; verify + convene recompute the on-disk digest the SAME
# way so the two agree. Newest record carrying a non-empty constitutionDigest wins (amend > genesis).
_council_sealed_constitution_digest() {
  [[ -f "$COUNCIL_LINEAGE" ]] || return 0
  jq -r 'select((.record.constitutionDigest // "") != "") | .record.constitutionDigest' "$COUNCIL_LINEAGE" 2>/dev/null | tail -n1
}
# sha256 of the on-disk 5dive.md ('' if missing) — the live side of the drift comparison.
_council_live_constitution_digest() {
  local p; p="$(_council_constitution_path)"
  [[ -f "$p" ]] || return 0
  sha256sum < "$p" 2>/dev/null | awk '{print $1}'
}
# Emit the drift JSON and RETURN non-zero (exit 7 from cli) when the live 5dive.md is out of sync
# with the sealed digest. Fails closed: a sealed digest with a missing/edited file is drift.
_council_constitution_drift() {
  local dir="$1" sealed live
  sealed="$(_council_sealed_constitution_digest)"
  live="$(_council_live_constitution_digest)"
  node "$dir/cli.mjs" drift-check --sealed="$sealed" --live="$live"
}

_council_help() {
  cat >&2 <<'COUNCIL_HELP'
5dive council — standalone deliberation council (v0.11)

  5dive council init --seats=<a:chair,b,c,...> --threshold=<majority|all|N|a/b> --veto=<principal>
      Human-seed the primary Council ONCE (sudo-gated, fail-closed if already initialized;
      --force re-seeds and the re-seed is logged in the lineage). The veto principal must be
      RESOLVABLE (human:<agent> -> that agent's paired human, or tg:<user_id>) or init refuses
      it. The genesis record is sealed on the root gate-proof rail and hash-chained into
      ${COUNCIL_LINEAGE}. Principle: an agent must not bootstrap its own governance body.

  5dive council lineage [verify|ls]
      Verify the sealed genesis lineage (re-seal each record, compare digests, check the
      hash-chain) or list it. `verify` fails closed on any tamper or broken link.

  5dive council roster
      The live Council: current seats, the pass threshold + quorum, the founder-veto holder,
      and the sealed lineage head (seq + digest) rooted at genesis.

  5dive council log [--limit=N]
      The past sealed verdicts — genesis + every promote/demote motion + any founder veto —
      in lineage order (the append-only governance record).

  5dive council record [--json]
      Per-seat TRACK RECORD: scores each seat's sealed votes against the REAL outcome of the task
      each convene decided (done → good, cancelled → bad; pending is not scored). A dissent is
      credited when the outcome went bad; an approve when it landed good. Data for promote/demote
      votes, not vibes. Votes are parsed from the sealed canonical; the tamper-evident seal is untouched.

  5dive council amend --file=<new 5dive.md> [--dry-run]
      Amend the constitution via a constitutional-class motion (2/3 + full quorum + founder
      veto). Validates the proposed file, convenes the amendment, and ONLY on a pass seals its
      digest into the hash-chain then swaps the on-disk 5dive.md. A non-pass leaves it untouched.
      The sealed digest — not the file — is the authority; hand-edits are caught by verify.

  5dive council verify [<receipt-digest>]
      Verify the WHOLE governance lineage: the prevDigest hash-chain, a per-record ROOT re-seal
      (each canonical must re-seal to its stored digest), AND constitution integrity (the live
      5dive.md must match the digest sealed in the newest genesis/amendment record). Fails closed
      on an edited/dropped/reordered record OR a drifted constitution. With a receipt digest,
      also re-seals that sealed receipt.

  sudo 5dive council {promote|demote|expel} --subject=<seat> [--lens="…"] [--mode=…] [--dry-run]
      Run a membership MOTION as a convened Council vote (sudo-gated — it mutates the root-owned
      roster + lineage). The subject RECUSES (does not vote on its own membership); the class is
      auto-derived IN CODE (promote = simple majority, demote/expel = 2/3 supermajority; a motion
      touching a governance param is forced constitutional). On a PASS the roster is mutated and a
      root-sealed motion record is hash-chained onto the lineage; a non-pass leaves the roster
      untouched. The convene receipt that decided it is linked from the motion record.

  5dive council convene "<question>" [--seats=a,b,c] [--mode=quick|deliberate|adversarial]
                                     [--bench=<name>] [--class=<decisionClass>]
                                     [--threshold=<n>]
                                     [--timeout=120] [--idle-secs=5] [--poll-secs=2] [--standalone]
      Convene a council over a question. By DEFAULT (CNCL-7) it DISPATCHES the question
      to the real seated agents — each seat votes via its OWN harness over the
      `5dive agent ask` rail, no shared model key. A seat that times out or replies
      without a COUNCIL-VOTE line is a recorded ABSTAIN; a convene that falls below
      quorum returns no verdict and auto-escalates with a human brief. The first round
      is BLIND (no seat sees another before its own vote); adversarial adds a rebuttal
      round, recorded separately. Emits an auditable verdict (deterministic tally over
      the current roster) and a tamper-evident, root-signed receipt. On a primary-council
      PASS it also OFFERS the founder veto to the genesis principal (CNCL-9, non-blocking):
      the pass stands, the receipt stamps executeAfter + a one-time tap nonce, and a ping
      fires. Defaults to the 5-seat standing Council. --standalone selects the deferred
      single-key modelCall seam instead of dispatch.
      (A veto can NEVER be asserted from a CLI string — `--veto-by` is refused; see below.)

  5dive council veto exercise --receipt=<sealed digest> --nonce=<tap nonce>
                              [--tier=hold|posthoc] [--reason=<why>]
      Exercise the founder veto on a sealed pass — the authenticated tap. The one-time
      nonce (minted at seal, bound to the offered recipient) authenticates it; `hold`
      (within veto_hold, default 15m) flips the pass to BLOCKED before execution,
      `posthoc` (until veto_posthoc, default 48h) flips it and flags an unwind. The flip
      is a NEW root-sealed record hash-chained to the original verdict digest; the
      original receipt is never mutated. Tier is auto-derived from the clock if omitted.

  5dive council sign-vote --seat=<id> --vote=<approve|reject|escalate|abstain>
                          --convene=<id> (--qdigest=<hex> | --question=<text>)
                          --key-file=<seat PKCS8 PEM | "-"> [--rationale=…] [--emit=line|json]
      (CNCL-10) A SEAT signs its own vote at source, from its OWN harness — sign-at-source,
      so the shell is the surface (a seat has no node of its own). Emits the `COUNCIL-SIG:`
      line the seat pastes after its COUNCIL-VOTE line (--emit=json for the full row). The
      convene id + question digest are in the signed bytes, so the signature is replay-proof.

  5dive council verify-votes --votes=<json|@file> --roster=<json|@file>
                             --convene=<id> (--qdigest=<hex> | --question=<text>)
      (CNCL-10) Re-check EVERY co-signed vote against the roster pubkeys + revocation, bound
      to THIS convene. Exits non-zero if any non-abstain vote is unsigned/forged/replayed/
      revoked, so a caller can gate on the exit code.

  5dive council bench ls
  5dive council bench show <name>
  5dive council bench add  <name> --seats=a:lens|b:lens [--mode=] [--threshold=] [--desc=]
  5dive council bench rm   <name>
      Manage the persisted, editable registry of standing benches (built-ins:
      council, ship, brand, security — fail-closed on an unknown name; add/rm are
      privileged governance writes and need sudo).

  5dive council gate-clear <task|DIVE-N> [--mode=deliberate] [--seats=a,b,c] [--dry-run]
      (CNCL-12) Route an OPEN tier-1 gate to the council. The escalate-only guardrail
      runs first: a tier>=2 gate or a human-only type (secret/approval/manual/access)
      is NEVER self-cleared — it is bumped to a human with a one-paragraph brief. A genuine
      tier-1 gate is convened (default: the primary Council), and the sealed verdict either
      CLEARS it (`task answer` with the recommendation) or escalates it with the brief.
      --dry-run prints the planned action without touching the gate.

  5dive council rot-triage [<task|DIVE-N> | --all] [--older-than-hours=48] [--dry-run]
      (CNCL-12) Rot-triage stale tier-2 gates: a tier-2 gate left UNANSWERED for 48h+
      is convened ONLY to re-brief it sharper for the human (and, in that brief, propose
      a rescope or a park+wake). It NEVER clears a tier-2 gate — tier-2 stays human-only
      (fail-closed). --all scans every stale tier-2 gate; --dry-run lists them without
      convening. Wired into the heartbeat behind COUNCIL_ROT_TRIAGE=on (default off).

  Add --json for a machine envelope. The default dispatch path needs NO model key
  (each seat uses its own harness). The --standalone seam uses COUNCIL_API_KEY
  (A-with-seam; BYO/OpenRouter via COUNCIL_BASE_URL). COUNCIL_MOCK=1 runs a
  deterministic offline council (no key, no network, no agent dispatch) for tests + smoke.
COUNCIL_HELP
}

_council_write_runtime() {
  local dir="$1"
  cat > "$dir/engine.mjs" <<'COUNCIL_ENGINE_MJS'
__ENGINE_MJS__
COUNCIL_ENGINE_MJS
  cat > "$dir/cli.mjs" <<'COUNCIL_CLI_MJS'
__CLI_MJS__
COUNCIL_CLI_MJS
}

# CNCL-8: resolve a veto PRINCIPAL to a concrete recipient id (fail-closed: echoes
# nothing if it can't resolve, and init then refuses). Supported forms:
#   human:<agent>  -> that agent's paired human (access.json allowFrom[0]) — e.g.
#                     human:main resolves to the human paired to @agent-main's bot.
#   tg:<digits> | <digits>  -> a literal Telegram user_id.
# An agent can only resolve principals that already exist as paired channels; it cannot
# invent a recipient. This is the "resolvable principal" invariant from the redesign.
_council_resolve_principal() {
  local p="$1"
  case "$p" in
    tg:*) local id="${p#tg:}"; [[ "$id" =~ ^[0-9]+$ ]] && printf '%s' "$id"; return 0 ;;
    human:*)
      local name="${p#human:}"
      [[ -n "$name" ]] || return 0
      _task_agent_channel "$name" >/dev/null 2>&1 || return 0
      [[ -n "${TASK_CH_ACCESS:-}" && -r "$TASK_CH_ACCESS" ]] || return 0
      jq -r '(.allowFrom // [])[0] // empty' "$TASK_CH_ACCESS" 2>/dev/null
      return 0 ;;
    *) [[ "$p" =~ ^[0-9]+$ ]] && printf '%s' "$p"; return 0 ;;
  esac
}

# CNCL-9: SHA-256 hex of a string (the nonce-digest primitive; seal stores the digest, exercise
# hashes the presented nonce and compares). Empty on a missing sha256sum (fail-closed downstream).
_council_sha256() { printf '%s' "${1:-}" | sha256sum 2>/dev/null | awk '{print $1}'; }

# CNCL-9 (main gate amendment 3): durable audit trail for REFUSED veto attempts — a forged
# `--veto-by` CLI string on convene, or a nonce/recipient mismatch on exercise. "refused + logged"
# must mean a real line on disk a test can assert, not just an stderr message. The file is
# attacker-triggerable, so it is root-owned 0600 (never group-readable).
_council_veto_audit() {
  local event="$1" ref="${2:-}" subject="${3:-}"
  mkdir -p "$COUNCIL_DIR" 2>/dev/null || true
  [[ -w "$COUNCIL_DIR" || -f "${COUNCIL_DIR}/veto-audit.jsonl" ]] || return 0
  local line
  line="$(jq -cn --arg e "$event" --arg r "$ref" --arg s "$subject" --arg u "$(id -un 2>/dev/null)" \
    '{ts:(now|todate? // ""), event:$e, ref:$r, subject:$s, by:$u, kind:"veto-refused"}' 2>/dev/null)" || return 0
  printf '%s\n' "$line" >> "${COUNCIL_DIR}/veto-audit.jsonl" 2>/dev/null || true
  chmod 0600 "${COUNCIL_DIR}/veto-audit.jsonl" 2>/dev/null || true
  [[ "$(id -u)" -eq 0 ]] && chown root:root "${COUNCIL_DIR}/veto-audit.jsonl" 2>/dev/null || true
  return 0
}

# CNCL-9: fire the founder veto ping at seal (non-blocking, best-effort). Records a durable ping
# entry (so "the ping fired" is observable + testable) and attempts a live notify to the resolved
# recipient. The tappable button + its callback -> `council veto exercise` is the telegram-plugin
# leg that pairs with a live genesis; this CLI leg guarantees the recipient is notified with the
# receipt handle + the one-time nonce the tap must present.
# DIVE-1546: the STRUCTURED founder-veto delivery seam `_council_veto_ping` prefers (rail B). It
# renders the offer as a telegram message + a 🛑 VETO tap button whose callback_data carries the
# one-time nonce — the ONLY place the raw nonce travels — and delivers it to the founder's DM chat.
# The nonce is NEVER put in the message text. The button carries a UNIQUE receipt PREFIX (12 chars),
# not the full digest, because `veto:<full base64url digest>:<32-char nonce>` would exceed Telegram's
# 64-byte callback_data cap; `council veto exercise --receipt` resolves the prefix fail-closed. Token
# resolution reuses the gate-notify path (per-agent connector token / $TELEGRAM_BOT_TOKEN); with no
# telegram rail the offer simply lapses (execution proceeds after the hold — fail-safe). Delivery
# routes through `_mirror_send`, which honors FIVEDIVE_NOTIFY_DRYRUN so a fixture can't DM a human.
_tg_veto_offer() {
  local resolved="$1" full_digest="$2" nonce="$3" execute_after="$4"
  [[ -n "$resolved" && -n "$full_digest" && -n "$nonce" ]] || return 0
  local token=""
  if _task_owner_channel 2>/dev/null && [[ -n "${TASK_CH_TOKEN:-}" ]]; then
    token="$TASK_CH_TOKEN"
  else
    token="${TELEGRAM_BOT_TOKEN:-}"
  fi
  [[ -n "$token" ]] || return 0   # no telegram rail → the offer lapses (fail-safe)
  local prefix="${full_digest:0:12}"
  local reply_markup
  reply_markup="$(jq -cn --arg p "$prefix" --arg n "$nonce" \
    '{inline_keyboard: [[{text: "🛑 VETO this pass", callback_data: ("veto:" + $p + ":" + $n)}]]}' 2>/dev/null)" || return 0
  # NB: the raw nonce is ONLY in callback_data above — never in this human-readable text.
  local text="Council veto offer — a pass sealed (${full_digest:0:12}…). Execution holds until ${execute_after}. Tap 🛑 VETO to block it, or ignore to let it proceed."
  _mirror_send "$token" "$resolved" "" "$text" "$reply_markup" >/dev/null 2>&1 || true
  return 0
}

_council_veto_ping() {
  local resolved="$1" digest="$2" execute_after="$3" nonce="$4"
  mkdir -p "$COUNCIL_DIR" 2>/dev/null || true
  # CNCL-9 (main gate amendment 2): the pings audit records ONLY the nonce DIGEST, never the raw
  # bearer token. The raw nonce leaves this process solely via the structured founder delivery leg
  # (`_tg_veto_offer`, DIVE-1546 rail B) below — never in chat text. The file is additionally locked
  # 0600 root so a group-claude agent cannot read even the digest+recipient trail.
  local nonce_digest; nonce_digest="$(_council_sha256 "$nonce")"
  local line
  line="$(jq -cn --arg r "$resolved" --arg d "$digest" --arg ea "$execute_after" --arg nd "$nonce_digest" \
    '{ts:(now|todate? // ""), recipient:$r, receiptDigest:$d, executeAfter:$ea, nonceDigest:$nd, kind:"veto-offer"}' 2>/dev/null)" || line=""
  if [[ -n "$line" && -w "$COUNCIL_DIR" ]]; then
    printf '%s\n' "$line" >> "${COUNCIL_DIR}/veto-pings.jsonl" 2>/dev/null || true
    chmod 0600 "${COUNCIL_DIR}/veto-pings.jsonl" 2>/dev/null || true
    [[ "$(id -u)" -eq 0 ]] && chown root:root "${COUNCIL_DIR}/veto-pings.jsonl" 2>/dev/null || true
  fi
  # Founder delivery leg — DIVE-1546 rail B (main-approved): the "nonce never printed to chat"
  # guarantee lives HERE at the source. The RAW one-time nonce leaves this process ONLY as STRUCTURED
  # data handed to the telegram plugin's veto-offer seam (`_tg_veto_offer <recipient> <receiptDigest>
  # <rawNonce> <executeAfter>`), which the plugin renders INSIDE a tap button's callback_data and
  # never echoes to chat. It is never interpolated into any human-readable message text.
  #   - Preferred: the structured `_tg_veto_offer` seam (plugin-provided) carries the raw nonce.
  #   - Fallback: if only the plain `_tg_send` seam exists, notify the founder that a veto window is
  #     open but carry NO nonce — a tap veto then needs the structured seam; without it the offer
  #     simply lapses and execution proceeds after the hold (fail-safe).
  # A missing rail must never fail the (already-sealed) convene. The live legs are skipped under MOCK.
  if command -v _tg_veto_offer >/dev/null 2>&1 && [[ -z "${COUNCIL_MOCK:-}" ]]; then
    _tg_veto_offer "$resolved" "$digest" "$nonce" "$execute_after" >/dev/null 2>&1 || true
  elif [[ -n "${COUNCIL_MOCK:-}" && -n "${COUNCIL_VETO_OFFER_SINK:-}" ]]; then
    # Offline-test capture ONLY (double-gated on MOCK + an explicit sink, mirrors COUNCIL_VETO_NONCE_SINK):
    # record the STRUCTURED offer so the bash e2e can assert the raw nonce travels structured (and that
    # no chat-text leg ever carries it). PRODUCTION is never MOCK and never writes this sink.
    ( umask 077; printf '%s\t%s\t%s\t%s\n' "$resolved" "$digest" "$nonce" "$execute_after" >> "$COUNCIL_VETO_OFFER_SINK" ) 2>/dev/null || true
  elif [[ -z "${COUNCIL_MOCK:-}" ]] && command -v _tg_send >/dev/null 2>&1; then
    _tg_send "$resolved" "Council veto offer — a pass sealed (${digest:0:12}…). Execution holds until ${execute_after}. Open /council or the dashboard to VETO within the window, or ignore to let it proceed." >/dev/null 2>&1 || true
  fi
  return 0
}

# CNCL-9: authenticated founder veto EXERCISE (the confirmed tap). bash owns authentication (the
# one-time nonce minted at seal, bound to the offered recipient); cli owns the fail-closed flip +
# the chained record. The original convene receipt is NEVER re-sealed or mutated — the veto is a
# NEW root-sealed record hash-chained to the original verdict digest.
#   5dive council veto exercise --receipt=<sealed digest> --nonce=<tap nonce> [--tier=hold|posthoc]
#                               [--reason=<why>]
_council_veto() {
  local dir="$1"; shift
  [[ "${1:-}" == "exercise" ]] || fail "$E_USAGE" "unknown veto action: ${1:-} (exercise)"
  shift
  local rcpt_digest="" nonce="" tier="" reason=""
  local a
  for a in "$@"; do
    case "$a" in
      --receipt=*) rcpt_digest="${a#--receipt=}" ;;
      --nonce=*)   nonce="${a#--nonce=}" ;;
      --tier=*)    tier="${a#--tier=}" ;;
      --reason=*)  reason="${a#--reason=}" ;;
    esac
  done
  [[ -n "$rcpt_digest" ]] || fail "$E_USAGE" "veto exercise needs --receipt=<sealed convene receipt digest>"
  [[ -n "$nonce" ]]       || fail "$E_PERMISSION" "veto exercise needs --nonce=<the one-time tap nonce> (an unauthenticated exercise is refused)"

  # Locate the sealed convene receipt by its digest. DIVE-1546: accept a UNIQUE receipt PREFIX, not
  # only the full digest — the telegram veto button carries a prefix because a full base64url digest
  # (43) + the nonce (32) exceeds Telegram's 64-byte callback_data cap. Resolution is FAIL-CLOSED:
  # collect every receipt whose sealedDigest EQUALS or STARTS WITH the arg and require EXACTLY one
  # (a full digest is a prefix of itself, so exact-match callers are unchanged; zero → not found,
  # >1 → ambiguous, both refused). The NONCE — not the prefix — is the authentication, so prefix
  # length is not a security boundary; a wrong/short prefix that resolves still dies at the nonce
  # check below. `sealedDigest` is base64url ([A-Za-z0-9_-]) so it carries no glob metacharacters.
  local rf found="" full_digest="" match_count=0 _sd
  if [[ -d "$COUNCIL_RECEIPTS" ]]; then
    for rf in "$COUNCIL_RECEIPTS"/*.json; do
      [[ -f "$rf" ]] || continue
      _sd="$(jq -r '.sealedDigest // empty' "$rf" 2>/dev/null)" || _sd=""
      [[ -n "$_sd" ]] || continue
      if [[ "$_sd" == "$rcpt_digest" || "$_sd" == "$rcpt_digest"* ]]; then
        found="$rf"; full_digest="$_sd"; match_count=$((match_count + 1))
      fi
    done
  fi
  if (( match_count > 1 )); then
    _council_veto_audit "ambiguous-prefix" "$rcpt_digest"
    fail "$E_PERMISSION" "receipt prefix ${rcpt_digest:0:16}… is AMBIGUOUS (matches ${match_count} sealed receipts) — refusing (fail-closed)"
  fi
  [[ -n "$found" ]] || fail "$E_GENERIC" "no sealed council receipt with digest ${rcpt_digest:0:16}… (fail-closed)"
  # RE-ANCHOR to the found receipt's FULL sealedDigest so every downstream check — above all the
  # re-seal hardening (main gate amendment 2) — compares against the true digest, NEVER the prefix.
  rcpt_digest="$full_digest"

  # HARDENING (main gate): before trusting ANY field of the receipt (.verdict / .vetoNonceDigest /
  # .vetoOffer), re-seal its canonical bytes on the gate-proof rail and confirm they match the
  # stored sealedDigest. A receipt whose body was edited (swapped nonce digest, flipped verdict,
  # widened offer) fails HERE — fail-closed — so the authenticated-tap path only ever acts on a
  # byte-intact receipt.
  local rcanon rseal=""
  rcanon="$(jq -r '.canonical // empty' "$found" 2>/dev/null)"
  [[ -n "$rcanon" ]] || fail "$E_GENERIC" "sealed receipt carries no canonical bytes to re-verify (fail-closed)"
  if [[ "$(id -u)" -eq 0 ]]; then rseal="$(printf '%s' "$rcanon" | cmd_gate_proof_sign_stdin 2>/dev/null)" || rseal=""
  else rseal="$(printf '%s' "$rcanon" | sudo -n 5dive gate-proof sign 2>/dev/null)" || rseal=""; fi
  [[ -n "$rseal" ]] || fail "$E_GENERIC" "cannot re-seal the receipt canonical (need root + an enforce key) — refusing to trust an unverifiable receipt (fail-closed)"
  [[ "$rseal" == "$rcpt_digest" ]] || { _council_veto_audit "receipt-tampered" "$rcpt_digest"; fail "$E_PERMISSION" "receipt canonical does not re-seal to its sealedDigest — the receipt was tampered (refused + logged, fail-closed)"; }

  # AUTHENTICATE the tap: sha256(presented nonce) must equal the nonce DIGEST minted for THIS offer.
  # The raw nonce is never stored server-side (only its digest rides in the receipt), so a
  # group-readable receipt no longer leaks the bearer token (main gate amendment 2).
  # CNCL-9 AMENDMENT (main gate): the nonce digest + executeAfter + stampedAt are read from the
  # VERIFIED canonical (which just re-sealed to the stored digest above), NEVER from the raw wrapper.
  # The wrapper's `.vetoNonceDigest`/`.executeAfter` are unsealed and forgeable; before this fix the
  # re-seal check only covered `.canonical`, so swapping `.vetoNonceDigest` to sha256(attacker-nonce)
  # passed the check and let an attacker exercise with a chosen nonce. Now those fields ride INSIDE
  # `.canonical` (seal-augment folded them in at seal time), so any edit breaks the re-seal above and
  # the values used here come from the byte-intact bytes. offer_resolved/principal stay wrapper-read:
  # exercise still requires the sealed-digest-matching nonce (the bearer token), which only the
  # founder holds, so a widened offer cannot help an attacker who lacks that nonce.
  local stored_nonce_digest offer_resolved offer_principal execute_after stamped_at verdict_json binding_json
  binding_json="$(printf '%s' "$rcanon" | node "$dir/cli.mjs" read-binding --canonical=- 2>/dev/null)" || binding_json=""
  stored_nonce_digest="$(printf '%s' "$binding_json" | jq -r '.nonceDigest // empty' 2>/dev/null)"
  execute_after="$(printf '%s' "$binding_json" | jq -r '.executeAfter // empty' 2>/dev/null)"
  stamped_at="$(printf '%s' "$binding_json" | jq -r '.stampedAt // empty' 2>/dev/null)"
  offer_resolved="$(jq -r '.verdict.vetoOffer.resolved // empty' "$found" 2>/dev/null)"
  offer_principal="$(jq -r '.verdict.vetoOffer.principal // empty' "$found" 2>/dev/null)"
  [[ -n "$stored_nonce_digest" && -n "$offer_resolved" ]] || fail "$E_GENERIC" "receipt carries no veto offer to exercise (fail-closed)"
  local presented_digest; presented_digest="$(_council_sha256 "$nonce")"
  [[ -n "$presented_digest" && "$presented_digest" == "$stored_nonce_digest" ]] || { _council_veto_audit "nonce-mismatch" "$rcpt_digest" "$offer_resolved"; fail "$E_PERMISSION" "veto nonce mismatch — this tap is not the one offered to the founder principal (refused + logged)"; }

  # Derive the tier from the clock unless explicitly given: within the HOLD window -> hold; after it
  # (up to veto_posthoc) -> posthoc; at/beyond the posthoc deadline -> refused (window expired, pass
  # is final). Boundary is inclusive: a zero/already-past window IS expired the instant it is reached
  # (now_e >= st_e + posthoc), so a 0s window never admits a same-second exercise — no clock race.
  local now_e ea_e st_e posthoc="${COUNCIL_VETO_POSTHOC_SECS:-172800}" _veto_cfg=""
  _veto_cfg="$(_council_constitution_json 2>/dev/null || true)"
  if [[ "$(printf '%s' "$_veto_cfg" | jq -r '.source // "defaults"' 2>/dev/null)" == "file" ]]; then
    posthoc="$(printf '%s' "$_veto_cfg" | jq -r '.veto.posthocSecs')"
  elif [[ "$(printf '%s' "$_veto_cfg" | jq -r '.valid // true' 2>/dev/null)" == "false" ]]; then
    posthoc=172800
  fi
  [[ "$posthoc" =~ ^[0-9]+$ ]] || posthoc=172800
  now_e="$(date -u +%s)"
  ea_e="$(date -u -d "$execute_after" +%s 2>/dev/null || echo 0)"
  st_e="$(date -u -d "$stamped_at" +%s 2>/dev/null || echo 0)"
  if [[ -z "$tier" ]]; then
    if (( ea_e > 0 && now_e < ea_e )); then tier="hold"; else tier="posthoc"; fi
  fi
  if [[ "$tier" == "posthoc" ]] && (( st_e > 0 && now_e >= st_e + posthoc )); then
    fail "$E_GENERIC" "veto window expired (past veto_posthoc=${posthoc}s from seal) — the pass is final, no override (fail-closed)"
  fi

  verdict_json="$(jq -c '.verdict' "$found" 2>/dev/null)"
  local stamped; stamped="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  local vraw
  vraw="$(node "$dir/cli.mjs" veto exercise \
    --orig-digest="$rcpt_digest" --by="$offer_principal" --resolved="$offer_resolved" \
    --tier="$tier" --reason="$reason" --verdict="$verdict_json" --stamped-at="$stamped")" || return $?

  # Root-seal the chained veto record and hash-chain it onto the original verdict digest. Same rail
  # + discipline as the genesis lineage; the original receipt bytes are left untouched.
  local canonical vdigest=""
  canonical="$(printf '%s' "$vraw" | jq -r '.canonical // empty')"
  if [[ -n "$canonical" ]]; then
    if [[ "$(id -u)" -eq 0 ]]; then vdigest="$(printf '%s' "$canonical" | cmd_gate_proof_sign_stdin)" || vdigest=""
    else vdigest="$(printf '%s' "$canonical" | sudo -n 5dive gate-proof sign 2>/dev/null)" || vdigest=""; fi
  fi
  [[ -n "$vdigest" ]] || fail "$E_GENERIC" "could not seal the veto record on the gate-proof rail (need root + an enforce key) — veto NOT recorded"

  if [[ -w "$COUNCIL_RECEIPTS" ]]; then
    printf '%s' "$vraw" | jq --arg d "$vdigest" --arg p "$rcpt_digest" --arg s "$stamped" \
      '{kind:"veto", stampedAt:$s, sealedDigest:$d, prevDigest:$p, tier: .vetoRecord.tier, unwindRequired: .vetoRecord.unwindRequired, record: .vetoRecord, flippedVerdict: .flippedVerdict, canonical: .canonical}' \
      > "${COUNCIL_RECEIPTS}/veto-${stamped//:/-}.json" 2>/dev/null || true
  fi
  # Append to the tamper-evident lineage. CNCL-9 (main gate amendment 1): the jsonl WRAPPER must
  # hash-chain to the LINEAGE head (prevDigest = the last lineage entry's digest, seq = last+1) so
  # `council lineage verify` stays green after a veto. The veto->original-verdict link is NOT lost:
  # it already rides INSIDE the signed record (record.prevDigest = the original verdict digest,
  # sealed in the canonical bytes). We keep it in the wrapper too, as `origDigest`, for readers.
  if [[ -f "$COUNCIL_LINEAGE" || -w "$COUNCIL_DIR" ]]; then
    local l_prev="" l_seq=0
    if [[ -f "$COUNCIL_LINEAGE" ]]; then
      l_prev="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.digest // ""' 2>/dev/null)"
      local l_last; l_last="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.seq // -1' 2>/dev/null)"
      [[ "$l_last" =~ ^[0-9]+$ ]] && l_seq=$((l_last+1))
    fi
    printf '%s' "$vraw" | jq -c --arg d "$vdigest" --arg lp "$l_prev" --arg od "$rcpt_digest" --arg sq "$l_seq" --arg s "$stamped" \
      '{seq: ($sq|tonumber), kind:"veto", stampedAt:$s, digest:$d, prevDigest:$lp, origDigest:$od, canonical: .canonical, record: .vetoRecord}' \
      >> "$COUNCIL_LINEAGE" 2>/dev/null || true
  fi

  if (( JSON_MODE )); then
    printf '%s' "$vraw" | jq --arg d "$vdigest" --arg p "$rcpt_digest" '{ok:true, data: (. + {sealedDigest:$d, prevDigest:$p})}'
  else
    echo "veto:         EXERCISED (${tier}) by ${offer_principal}"
    echo "disposition:  blocked  (pass overruled; original verdict left sealed + immutable)"
    [[ "$tier" == "posthoc" ]] && echo "unwind:       REQUIRED — reversible work must be manually unwound (v0.11)"
    echo "chained:      veto ${vdigest:0:16}… -> verdict ${rcpt_digest:0:16}…"
  fi
}

_council_init_or_lineage() {
  local sub="$1" dir="$2"; shift 2
  mkdir -p "$COUNCIL_DIR" 2>/dev/null || true

  if [[ "$sub" == "lineage" ]]; then
    local action="${1:-verify}"
    if [[ ! -f "$COUNCIL_LINEAGE" ]]; then
      if (( JSON_MODE )); then printf '%s\n' '{"ok":true,"data":{"entries":[],"chain":"empty"}}'; else echo "lineage: (empty — council not yet initialized)"; fi
      return 0
    fi
    if [[ "$action" == "ls" ]]; then
      if (( JSON_MODE )); then jq -s '{ok:true,data:{entries:.}}' "$COUNCIL_LINEAGE"
      else jq -r '"seq \(.seq)\t\(.kind)\t\(.stampedAt)\tdigest=\(.digest[0:16])…\tprev=\((.prevDigest // "")[0:8])"' "$COUNCIL_LINEAGE"; fi
      return 0
    fi
    # verify: re-seal each canonical on the ROOT rail, compare to the stored digest, and
    # check the prevDigest hash-chain links back to genesis. Fails closed on any mismatch.
    local ok=1 prev="" line seq canonical stored kind computed n=0
    while IFS= read -r line; do
      [[ -n "$line" ]] || continue
      n=$((n+1))
      seq="$(printf '%s' "$line" | jq -r '.seq')"
      kind="$(printf '%s' "$line" | jq -r '.kind')"
      stored="$(printf '%s' "$line" | jq -r '.digest')"
      canonical="$(printf '%s' "$line" | jq -r '.canonical')"
      local lprev; lprev="$(printf '%s' "$line" | jq -r '.prevDigest // ""')"
      if [[ "$lprev" != "$prev" ]]; then echo "lineage: BROKEN CHAIN at seq $seq (prevDigest=$lprev, expected $prev)" >&2; ok=0; fi
      if [[ "$(id -u)" -eq 0 ]]; then computed="$(printf '%s' "$canonical" | cmd_gate_proof_sign_stdin 2>/dev/null)"; else computed="$(printf '%s' "$canonical" | sudo -n 5dive gate-proof sign 2>/dev/null)"; fi
      if [[ -z "$computed" ]]; then echo "lineage: cannot re-seal seq $seq (no gate-proof key / not root)" >&2; ok=0
      elif [[ "$computed" != "$stored" ]]; then echo "lineage: TAMPERED seq $seq ($kind) — digest mismatch" >&2; ok=0; fi
      prev="$stored"
    done < "$COUNCIL_LINEAGE"
    if (( ok )); then
      if (( JSON_MODE )); then printf '%s\n' "{\"ok\":true,\"data\":{\"verified\":true,\"entries\":$n}}"; else echo "lineage: VERIFIED ($n entr$([[ $n -eq 1 ]] && echo y || echo ies), chain intact)"; fi
      return 0
    else
      if (( JSON_MODE )); then printf '%s\n' '{"ok":false,"error":"lineage verification failed"}'; fi
      return "$E_GENERIC"
    fi
  fi

  # ---- init (sudo-gated, one-time) ----------------------------------------
  if [[ ! -w "$COUNCIL_DIR" ]]; then
    fail "$E_PERMISSION" "council init seeds the governance body — it writes ${COUNCIL_DIR} (root-owned) and must be human/sudo-run: sudo 5dive council init $*"
  fi
  # Resolve the veto principal up front so init refuses an unresolvable one BEFORE any write.
  local principal="" a
  local -a passthru=()
  for a in "$@"; do
    case "$a" in --veto=*) principal="${a#--veto=}" ;; esac
    passthru+=("$a")
  done
  [[ -n "$principal" ]] || fail "$E_USAGE" "council init needs --veto=<principal> (e.g. human:main)"
  local resolved; resolved="$(_council_resolve_principal "$principal")"
  [[ -n "$resolved" ]] || fail "$E_USAGE" "veto principal '$principal' did not resolve to a real recipient — init rejects an unknown principal (fail-closed). Use human:<agent> (a paired agent) or tg:<user_id>."

  local genesis_exists=0; [[ -f "$COUNCIL_GENESIS" ]] && genesis_exists=1
  # hash-chain head: prevDigest + next seq come from the last lineage line.
  local prev_digest="" seq=0
  if [[ -f "$COUNCIL_LINEAGE" ]]; then
    prev_digest="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.digest // ""' 2>/dev/null)"
    local last_seq; last_seq="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.seq // -1' 2>/dev/null)"
    [[ "$last_seq" =~ ^[0-9]+$ ]] && seq=$((last_seq+1))
  fi
  local stamped; stamped="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  # CNCL-15: seed the v0 constitution (5dive.md) if none exists, then seal its digest INTO the
  # genesis record so a later hand-edit is detectable as drift. The file is the human-readable
  # projection; the sealed digest is the authority. `sha256sum` is the shared digest realm with
  # verify/convene. An operator-supplied 5dive.md already on disk is honored (its digest is sealed).
  local cpath; cpath="$(_council_constitution_path)"
  if [[ ! -f "$cpath" ]]; then
    if ( umask 022; node "$dir/cli.mjs" constitution-render > "$cpath" ); then
      echo "constitution: seeded v0 -> $cpath" >&2
    else
      rm -f "$cpath" 2>/dev/null || true
      fail "$E_GENERIC" "could not seed the v0 constitution at $cpath — genesis NOT written"
    fi
  fi
  # Validate the on-disk constitution parses before sealing its digest into genesis (fail-closed).
  node "$dir/cli.mjs" constitution --path="$cpath" >/dev/null 2>&1 || fail "$E_VALIDATION" "the constitution at $cpath is not valid — refusing to seal a broken governance file into genesis (fail-closed)"
  local constitution_digest; constitution_digest="$(sha256sum < "$cpath" 2>/dev/null | awk '{print $1}')"
  [[ -n "$constitution_digest" ]] || fail "$E_GENERIC" "could not digest the constitution at $cpath"

  local raw
  raw="$(node "$dir/cli.mjs" init "${passthru[@]}" \
    --registry="$COUNCIL_REGISTRY" --veto-resolved="$resolved" \
    --genesis-exists="$genesis_exists" --prev-digest="$prev_digest" --seq="$seq" \
    --constitution-digest="$constitution_digest" \
    --stamped-at="$stamped")" || return $?

  # Seal the canonical genesis bytes on the ROOT rail and hash-chain into the lineage. The
  # seal is what makes the roster non-forgeable; the chain makes the whole history verifiable.
  local canonical digest=""
  canonical="$(printf '%s' "$raw" | jq -r '.canonical // empty')"
  if [[ -z "$canonical" ]]; then fail "$E_GENERIC" "init produced no canonical record"; fi
  if [[ "$(id -u)" -eq 0 ]]; then digest="$(printf '%s' "$canonical" | cmd_gate_proof_sign_stdin 2>/dev/null)" || digest=""
  else digest="$(printf '%s' "$canonical" | sudo -n 5dive gate-proof sign 2>/dev/null)" || digest=""; fi
  [[ -n "$digest" ]] || fail "$E_GENERIC" "could not seal the genesis record on the gate-proof rail (need root + an enforce key) — genesis NOT written"

  printf '%s' "$raw" | jq --arg d "$digest" '.genesis + {sealedDigest:$d}' > "$COUNCIL_GENESIS"
  printf '%s' "$raw" | jq -c --arg d "$digest" --arg p "$prev_digest" \
    '{seq: .genesis.seq, kind: "genesis", stampedAt: .genesis.stampedAt, digest: $d, prevDigest: $p, canonical: .canonical, record: .genesis}' \
    >> "$COUNCIL_LINEAGE"

  if (( JSON_MODE )); then
    printf '%s' "$raw" | jq --arg d "$digest" '{ok:true, data: (. + {sealedDigest:$d})}'
  else
    local seats chair
    seats="$(printf '%s' "$raw" | jq -r '.seats | join(", ")')"
    chair="$(printf '%s' "$raw" | jq -r '.chair // "none"')"
    echo "council: initialized (seq $seq)"
    echo "seats:   $seats"
    echo "chair:   $chair"
    echo "veto:    $principal -> $resolved"
    echo "const:   v0 sealed (${constitution_digest:0:16}…) -> $cpath"
    echo "genesis: sealed (${digest:0:16}…) + hash-chained into lineage"
  fi
  return 0
}

# ==================== CNCL-12: gate-rot wiring ====================
# gate-clear (T1) + rot-triage (T2). Thin orchestrators: they read the gate from the tasks
# DB, ask the embedded pure `gate-map` verb what to do (guardrail + verdict->action), run the
# SAME sealed `5dive council convene` path for the deliberation, and drive real `task` verbs.
# No new seal/persist code — the convene it shells out to owns the tamper-evident receipt.
_council_bin() { echo "${COUNCIL_5DIVE_BIN:-5dive}"; }

# Emit {ident,ask,type,tier,recommend,options,live} JSON for an OPEN gate, or empty on a miss.
# `live` = the canonical still-answerable-gate predicate (need_type set, not answered, task open).
_council_gate_json() {
  local dir="$1" id="$2" row us
  us=$'\x1f'
  row="$(db "SELECT ident||x'1f'||COALESCE(need_type,'')||x'1f'||COALESCE(CAST(tier AS TEXT),'')||x'1f'||COALESCE(recommend,'')||x'1f'||COALESCE(need_options,'')||x'1f'||COALESCE(replace(ask,x'0a',' '),'')||x'1f'||CASE WHEN need_type IS NOT NULL AND need_answered_at IS NULL AND status NOT IN ('done','cancelled') THEN 1 ELSE 0 END FROM tasks WHERE ident=$(sqlq "$id") OR id=$(sqlq "$id") LIMIT 1;" 2>/dev/null)" || return 1
  [[ -n "$row" ]] || return 1
  local ident gtype gtier grec gopts gask glive
  IFS="$us" read -r ident gtype gtier grec gopts gask glive <<<"$row"
  # A missing tier defaults to 2 (fail-closed: unknown risk is treated as a hard human gate).
  [[ -n "$gtier" ]] || gtier=2
  jq -nc --arg ident "$ident" --arg ask "$gask" --arg type "$gtype" \
         --argjson tier "$gtier" --arg recommend "$grec" --arg options "$gopts" --argjson live "${glive:-0}" \
    '{ident:$ident, ask:$ask, type:$type, tier:$tier, recommend:$recommend, options:$options, live:$live}'
}

# Run the sealed primary-council convene on a question, return the --json envelope.
_council_convene_json() {
  local q="$1"; shift
  "$(_council_bin)" council convene "$q" --json "$@" 2>/dev/null
}

_council_gate_clear() {
  local dir="$1"; shift
  local id="" mode="deliberate" dry=0; local -a seat_args=()
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run) dry=1 ;;
      --mode=*) mode="${1#--mode=}" ;;
      --seats=*|--bench=*|--timeout=*|--idle-secs=*|--poll-secs=*|--standalone) seat_args+=("$1") ;;
      --*) ;;  # ignore unknown flags
      *) id="$1" ;;
    esac; shift
  done
  [[ -n "$id" ]] || fail "$E_USAGE" "gate-clear needs a task id: 5dive council gate-clear <task|DIVE-N>"
  local gate; gate="$(_council_gate_json "$dir" "$id")" || fail "$E_NOT_FOUND" "no such task: $id"
  [[ "$(printf '%s' "$gate" | jq -r '.live')" == "1" ]] || fail "$E_VALIDATION" "$id has no open human gate to clear (already answered, or not a gate)"

  # Phase 1 — escalate-only guardrail (never convene a hard-gate class).
  local plan1 clearable; plan1="$(node "$dir/cli.mjs" gate-map --gate="$gate")" || fail "$E_GENERIC" "gate-map failed"
  clearable="$(printf '%s' "$plan1" | jq -r '.clearable')"
  if [[ "$clearable" != "true" ]]; then
    local cmd; cmd="$(printf '%s' "$plan1" | jq -r '.command')"
    _council_emit_gate_result "$dry" "escalate" "$id" "$(printf '%s' "$plan1" | jq -r '.reason')" "$cmd"
    return 0
  fi

  # Phase 2 — convene the primary council on the question from the guardrail, seal the receipt.
  local q; q="$(printf '%s' "$plan1" | jq -r '.question')"
  # CNCL-17: stamp the SUBJECT task ident on the receipt so this seat vote is later scored against
  # the task's real outcome (a gate-clear convene decides exactly one task — its ident IS the subject).
  local env; env="$(_council_convene_json "$q" --mode="$mode" --subject="$id" "${seat_args[@]}")" || fail "$E_GENERIC" "convene failed"
  local verdict digest; verdict="$(printf '%s' "$env" | jq -c '.data.verdict')"; digest="$(printf '%s' "$env" | jq -r '.data.sealedDigest // empty')"
  [[ -n "$verdict" && "$verdict" != "null" ]] || fail "$E_GENERIC" "convene returned no verdict"

  # Phase 3 — map the sealed verdict to the action command and run it.
  local plan2 action cmd; plan2="$(node "$dir/cli.mjs" gate-map --gate="$gate" --verdict="$verdict")" || fail "$E_GENERIC" "gate-map (verdict) failed"
  action="$(printf '%s' "$plan2" | jq -r '.action')"; cmd="$(printf '%s' "$plan2" | jq -r '.command')"
  _council_emit_gate_result "$dry" "$action" "$id" "receipt ${digest:0:16}…" "$cmd"
}

# Execute (or, on --dry-run, just print) a gate-map command. The command is a self-contained
# `5dive task ...` string built by the pure mapper; we run it through bash -c against the CLI.
_council_emit_gate_result() {
  local dry="$1" action="$2" id="$3" note="$4" cmd="$5"
  if (( dry )); then
    if (( JSON_MODE )); then jq -nc --arg a "$action" --arg id "$id" --arg n "$note" --arg c "$cmd" '{ok:true,data:{dryRun:true,action:$a,gate:$id,note:$n,command:$c}}'
    else echo "would $action $id ($note): $cmd"; fi
    return 0
  fi
  # Route the emitted `5dive ...` verbs through our own binary (test override honored).
  local runnable="${cmd//5dive /$(_council_bin) }"
  bash -c "$runnable" >/dev/null 2>&1 || true
  if (( JSON_MODE )); then jq -nc --arg a "$action" --arg id "$id" --arg n "$note" --arg c "$cmd" '{ok:true,data:{action:$a,gate:$id,note:$n,command:$c}}'
  else echo "council $action: $id ($note)"; fi
}

_council_rot_triage() {
  local dir="$1"; shift
  local id="" all=0 hours=48 dry=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --all) all=1 ;;
      --dry-run) dry=1 ;;
      --older-than-hours=*) hours="${1#--older-than-hours=}" ;;
      --*) ;;
      *) id="$1" ;;
    esac; shift
  done
  [[ "$hours" =~ ^[0-9]+$ ]] || hours=48
  local -a idents=()
  if [[ -n "$id" ]]; then
    idents+=("$id")
  elif (( all )); then
    # Stale tier-2 (or legacy NULL-tier) gates, oldest first. Mirrors the heartbeat T2 predicate,
    # but gated on the gate-file time (need_asked_at) crossing the 48h threshold.
    local list; list="$(db "SELECT ident FROM tasks WHERE need_type IS NOT NULL AND need_answered_at IS NULL AND status NOT IN ('done','cancelled') AND (tier=2 OR tier IS NULL) AND need_asked_at IS NOT NULL AND need_asked_at <= datetime('now','-${hours} hours') ORDER BY need_asked_at ASC;" 2>/dev/null)"
    while IFS= read -r _l; do [[ -n "$_l" ]] && idents+=("$_l"); done <<<"$list"
  else
    fail "$E_USAGE" "rot-triage needs a task id or --all"
  fi
  if [[ ${#idents[@]} -eq 0 ]]; then
    if (( JSON_MODE )); then jq -nc '{ok:true,data:{triaged:[],count:0}}'; else echo "rot-triage: no stale tier-2 gates (>=${hours}h)"; fi
    return 0
  fi
  local -a done_idents=()
  local it
  for it in "${idents[@]}"; do
    local gate; gate="$(_council_gate_json "$dir" "$it")" || continue
    [[ "$(printf '%s' "$gate" | jq -r '.live')" == "1" ]] || continue
    # FAIL-CLOSED: only triage genuine tier>=2 gates (never a tier-1, which gate-clear handles).
    local gtier; gtier="$(printf '%s' "$gate" | jq -r '.tier')"
    [[ "$gtier" -ge 2 ]] 2>/dev/null || continue
    if (( dry )); then done_idents+=("$it"); continue; fi
    # Convene the triage question (the guardrail phase1 with --triage builds it). NEVER clears.
    local plan1 q; plan1="$(node "$dir/cli.mjs" gate-map --gate="$gate" --triage)" || continue
    q="$(printf '%s' "$plan1" | jq -r '.question')"
    local env verdict; env="$(_council_convene_json "$q" --mode=adversarial)" || continue
    verdict="$(printf '%s' "$env" | jq -c '.data.verdict')"; [[ -n "$verdict" && "$verdict" != "null" ]] || continue
    local plan2 cmd; plan2="$(node "$dir/cli.mjs" gate-map --gate="$gate" --triage --verdict="$verdict")" || continue
    # Belt-and-suspenders: the pure mapper never emits `task answer` for a triage, but assert it here
    # too — a triage must NEVER clear a tier-2 gate even if the mapping ever regresses.
    cmd="$(printf '%s' "$plan2" | jq -r '.command')"
    if printf '%s' "$cmd" | grep -q 'task answer'; then
      continue   # refuse: fail-closed, a tier-2 triage NEVER clears (should be unreachable)
    fi
    local runnable="${cmd//5dive /$(_council_bin) }"
    bash -c "$runnable" >/dev/null 2>&1 || true
    done_idents+=("$it")
  done
  if (( JSON_MODE )); then
    printf '%s\n' "${done_idents[@]}" | jq -R . | jq -sc --argjson dry "$dry" '{ok:true,data:{triaged:map(select(length>0)),count:(map(select(length>0))|length),dryRun:($dry==1)}}'
  else
    local _verb="re-briefed, none cleared"; (( dry )) && _verb="to triage (dry-run)"
    echo "rot-triage: ${#done_idents[@]} tier-2 gate(s) ${_verb}: ${done_idents[*]}"
  fi
}

# ==================== CNCL-11: governance surface ====================
# roster (live seats + threshold + veto holder + lineage head) / log (past verdicts) /
# verify (chain + per-record re-seal) / promote|demote|expel (a convened MOTION that, on a
# PASS, mutates the roster + writes a hash-chained, root-sealed lineage record). The convene
# it shells out to owns the tamper-evident receipt + the founder-veto offer; motions reuse it.

# Root seal of stdin canonical bytes on the gate-proof rail (empty on no key / not root).
_council_seal_stdin() {
  if [[ "$(id -u)" -eq 0 ]]; then cmd_gate_proof_sign_stdin 2>/dev/null; else sudo -n 5dive gate-proof sign 2>/dev/null; fi
}

# council roster — the current seats + live threshold (from the persisted council bench), the
# founder-veto principal (from genesis), and the sealed lineage head (seq + digest).
_council_roster() {
  local dir="$1"
  [[ -f "$COUNCIL_GENESIS" ]] || fail "$E_VALIDATION" "the Council has no genesis roster — human-seed it first: sudo 5dive council init --seats=<a:chair,b,c> --threshold=<spec> --veto=<principal>"
  local raw; raw="$(node "$dir/cli.mjs" roster --registry="$COUNCIL_REGISTRY")" || return $?
  local vprincipal vresolved head_seq head_digest hlen
  vprincipal="$(jq -r '.veto.principal // "none"' "$COUNCIL_GENESIS" 2>/dev/null)"
  vresolved="$(jq -r '.veto.resolved // ""' "$COUNCIL_GENESIS" 2>/dev/null)"
  head_seq="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.seq // 0' 2>/dev/null)"
  head_digest="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.digest // ""' 2>/dev/null)"
  hlen="$(wc -l < "$COUNCIL_LINEAGE" 2>/dev/null | tr -d ' ')"; [[ "$hlen" =~ ^[0-9]+$ ]] || hlen=0
  if (( JSON_MODE )); then
    printf '%s' "$raw" | jq --arg vp "$vprincipal" --arg vr "$vresolved" --argjson hs "${head_seq:-0}" --arg hd "$head_digest" --argjson hl "$hlen" \
      '{ok:true, data: (. + {veto:{principal:$vp, resolved:$vr}, lineage:{seq:$hs, headDigest:$hd, records:$hl}})}'
  else
    echo "council:   council ($(printf '%s' "$raw" | jq -r '.seatCount') seats)"
    printf '%s' "$raw" | jq -r '.seats[] | "  seat \(.id)\(if .chair then " (chair)" else "" end)"'
    echo "threshold: $(printf '%s' "$raw" | jq -r '.threshold') to pass, quorum $(printf '%s' "$raw" | jq -r '.quorum') (spec: $(printf '%s' "$raw" | jq -c '.thresholdSpec'))"
    echo "veto:      $vprincipal"
    echo "lineage:   seq $head_seq, ${hlen} record(s), head ${head_digest:0:16}…"
  fi
}

# council log — the past sealed verdicts (motions + genesis + vetoes) from the lineage, newest last.
_council_log() {
  local dir="$1"; shift
  local limit=0; for a in "$@"; do case "$a" in --limit=*) limit="${a#--limit=}";; esac; done
  if [[ ! -f "$COUNCIL_LINEAGE" ]]; then
    if (( JSON_MODE )); then printf '%s\n' '{"ok":true,"data":{"entries":[]}}'; else echo "log: (empty — council not yet initialized)"; fi
    return 0
  fi
  if (( JSON_MODE )); then
    jq -s --argjson lim "${limit:-0}" '{ok:true,data:{entries: (if $lim>0 then .[-$lim:] else . end)}}' "$COUNCIL_LINEAGE"
  else
    local src="$COUNCIL_LINEAGE"
    [[ "$limit" =~ ^[0-9]+$ && "$limit" -gt 0 ]] && src="$(tail -n "$limit" "$COUNCIL_LINEAGE")"
    printf '%s\n' "$([[ "$limit" -gt 0 ]] 2>/dev/null && printf '%s' "$src" || cat "$COUNCIL_LINEAGE")" | jq -r '
      if .kind=="genesis" then "seq \(.seq)\tgenesis\t\(.stampedAt)\tseats=\(.record.seats|map(.id)|join(","))"
      elif .kind=="motion" then "seq \(.seq)\tmotion:\(.record.motion.class)\t\(.stampedAt)\tsubject=\(.record.motion.subject // "-")\toutcome=\(.record.outcome)\ttally=a\(.record.tally.approve)/r\(.record.tally.reject)/e\(.record.tally.escalate)"
      elif .kind=="veto" then "seq \(.seq)\tveto\t\(.stampedAt)\ttier=\(.tier // "-")\tblocked"
      else "seq \(.seq)\t\(.kind)\t\(.stampedAt)" end'
  fi
}

# council record — CNCL-17 seat track record. Scores every seat's sealed votes against the REAL
# outcome of the task each convene decided (subject): a dissent (reject/escalate) is VINDICATED when
# the task went bad; an approve is correct when it landed good. Outcome is read from the decided
# task's terminal status (done → good, cancelled → bad; pending/unknown are not scored). Seat votes
# are PARSED from the sealed canonical (A1 — no new structured array in the tamper-evident seal), and
# the subject is the receipt's `subject` field or, for historical receipts, the first ident parsed
# from its question. Read-only over already-sealed receipts.
_council_record() {
  local dir="$1"; shift
  if ! compgen -G "${COUNCIL_RECEIPTS}/*.json" >/dev/null 2>&1; then
    if (( JSON_MODE )); then printf '%s\n' '{"ok":true,"data":{"seats":[],"scoredReceipts":0}}'
    else echo "record: (no sealed convene receipts yet)"; fi
    return 0
  fi
  local receipts; receipts="$(jq -s '[.[] | {subject:(.subject // ""), question:(.question // ""), canonical:(.canonical // "")}]' "${COUNCIL_RECEIPTS}"/*.json 2>/dev/null)" || receipts='[]'
  local subjects; subjects="$(printf '%s' "$receipts" | jq -r '.[] | (if (.subject|length)>0 then .subject else ((.question|capture("(?<i>[A-Z][A-Z0-9]+-[0-9]+)")|.i) // "") end)' 2>/dev/null | grep -E '^[A-Za-z0-9]+-[0-9]+$' | sort -u)"
  local outcomes='{}' subj st oc
  while IFS= read -r subj; do
    [[ -n "$subj" ]] || continue
    st="$(db "SELECT status FROM tasks WHERE ident=$(sqlq "$subj") OR id=$(sqlq "$subj") LIMIT 1;" 2>/dev/null)"
    case "$st" in
      done) oc="good" ;;
      cancelled) oc="bad" ;;
      *) oc="" ;;   # pending / not found → not scoreable (never score an undecided task)
    esac
    [[ -n "$oc" ]] && outcomes="$(printf '%s' "$outcomes" | jq -c --arg s "$subj" --arg o "$oc" '. + {($s): $o}')"
  done <<< "$subjects"
  local res; res="$(node "$dir/cli.mjs" record --receipts="$receipts" --outcomes="$outcomes")" || fail "$E_GENERIC" "record scoring failed"
  if (( JSON_MODE )); then
    printf '%s' "$res" | jq '{ok:true, data: .}'
  else
    local n; n="$(printf '%s' "$res" | jq -r '.seats|length')"
    if [[ "$n" == "0" ]]; then echo "record: no seat votes scored yet (no decided-task outcomes among the receipts)"; return 0; fi
    echo "seat track record (calibration vs real task outcomes):"
    printf '%s' "$res" | jq -r '.seats[] | "  \(.seat)\t\((.calibration*100)|floor)%\t(\(.correct)/\(.scored))\(if .vindicated>0 then "\t\(.vindicated) vindicated dissent" else "" end)"'
    printf '%s' "$res" | jq -r '"scored \(.scoredReceipts) receipt(s) with a known outcome"'
  fi
}

# council verify [<receipt-digest>] — structural chain check (cli verify-chain over the lineage
# entries) AND a per-record ROOT re-seal (each canonical must re-seal to its stored digest). Both
# must be green. With a receipt digest, additionally locates + re-seals that specific sealed receipt.
_council_verify() {
  local dir="$1"; shift
  local target="${1:-}"
  if [[ ! -f "$COUNCIL_LINEAGE" ]]; then fail "$E_VALIDATION" "no lineage to verify — the council is not initialized"; fi
  # 1) structural chain (prevDigest links + seq monotonicity across the WHOLE log).
  local entries chain_res chain_ok
  entries="$(jq -s -c '[.[] | {seq, prevDigest: (.prevDigest // ""), digest}]' "$COUNCIL_LINEAGE")"
  chain_res="$(node "$dir/cli.mjs" verify-chain --entries="$entries")"; chain_ok=$?
  # 2) per-record re-seal on the ROOT rail (detects an edited canonical whose digest was faked).
  local reseal_ok=1 line canonical stored computed n=0 bad=""
  while IFS= read -r line; do
    [[ -n "$line" ]] || continue; n=$((n+1))
    stored="$(printf '%s' "$line" | jq -r '.digest')"
    canonical="$(printf '%s' "$line" | jq -r '.canonical')"
    computed="$(printf '%s' "$canonical" | _council_seal_stdin)"
    if [[ -z "$computed" ]]; then reseal_ok=0; bad="seq $(printf '%s' "$line" | jq -r '.seq') (no gate-proof key / not root)"; break
    elif [[ "$computed" != "$stored" ]]; then reseal_ok=0; bad="seq $(printf '%s' "$line" | jq -r '.seq') (canonical does not re-seal to its digest — TAMPERED)"; break; fi
  done < "$COUNCIL_LINEAGE"
  # 3) optional: a specific sealed receipt digest re-seals to itself.
  local rcpt_ok="skipped" rf found=""
  if [[ -n "$target" ]]; then
    rcpt_ok=0
    for rf in "$COUNCIL_RECEIPTS"/*.json; do
      [[ -f "$rf" ]] || continue
      [[ "$(jq -r '.sealedDigest // empty' "$rf" 2>/dev/null)" == "$target" ]] && { found="$rf"; break; }
    done
    if [[ -n "$found" ]]; then
      local rc; rc="$(jq -r '.canonical // empty' "$found")"
      [[ "$(printf '%s' "$rc" | _council_seal_stdin)" == "$target" ]] && rcpt_ok=1
    fi
  fi
  # 4) CNCL-15 constitution DRIFT — the live 5dive.md must still match the digest sealed in the
  # newest genesis/amendment record. A sealed digest with a missing or edited file = drift; verify
  # FAILS CLOSED (a drifted governance file is not trusted). No sealed digest (pre-CNCL-15 lineage)
  # = nothing to check. Reuses the same drift-check node verb + sha256sum realm as convene.
  local drift_ok=1 drift_reason="no sealed constitution digest" drift_json
  drift_json="$(_council_constitution_drift "$dir" 2>/dev/null)" || drift_ok=0
  drift_reason="$(printf '%s' "$drift_json" | jq -r '.reason // "drift"' 2>/dev/null)"
  local all_ok=1
  [[ "$chain_ok" -eq 0 && "$reseal_ok" -eq 1 && "$drift_ok" -eq 1 ]] || all_ok=0
  [[ -n "$target" && "$rcpt_ok" != "1" ]] && all_ok=0
  if (( JSON_MODE )); then
    jq -nc --argjson chain "$chain_res" --argjson chainOk "$([[ $chain_ok -eq 0 ]] && echo true || echo false)" \
      --argjson resealOk "$([[ $reseal_ok -eq 1 ]] && echo true || echo false)" --arg bad "$bad" \
      --argjson driftOk "$([[ $drift_ok -eq 1 ]] && echo true || echo false)" --arg driftReason "$drift_reason" \
      --arg rcpt "$rcpt_ok" --argjson n "$n" --argjson allOk "$([[ $all_ok -eq 1 ]] && echo true || echo false)" \
      '{ok:$allOk, data:{verified:$allOk, records:$n, chain:$chain, chainOk:$chainOk, resealOk:$resealOk, resealBad:$bad, constitutionOk:$driftOk, constitution:$driftReason, receipt:$rcpt}}'
  else
    if (( all_ok )); then echo "council verify: OK — $n record(s), chain intact + every record re-seals + constitution matches its sealed digest${target:+ (receipt ${target:0:16}… verified)}"
    else
      echo "council verify: FAILED" >&2
      [[ "$chain_ok" -ne 0 ]] && echo "  chain: $(printf '%s' "$chain_res" | jq -r '.reason')" >&2
      [[ "$reseal_ok" -ne 1 ]] && echo "  re-seal: $bad" >&2
      [[ "$drift_ok" -ne 1 ]] && echo "  constitution: $drift_reason" >&2
      [[ -n "$target" && "$rcpt_ok" != "1" ]] && echo "  receipt: $target not found or does not re-seal" >&2
    fi
  fi
  (( all_ok )) && return 0 || return "$E_GENERIC"
}

# council promote|demote|expel — the convened MOTION. Sudo-gated (mutates the root-owned roster +
# lineage). Reads the current roster off the sealed lineage head, PLANs (classify+recuse) via cli,
# CONVENEs the primary council (subject recused, class auto-derived, founder-veto offered), and on a
# PASS APPLYs: mutate roster, build a hash-chained motion record, ROOT-seal it, append the lineage,
# and persist the new roster — seal FIRST so a failed seal never splits roster from lineage.
_council_motion() {
  local dir="$1" kind="$2"; shift 2
  mkdir -p "$COUNCIL_DIR" 2>/dev/null || true
  if [[ ! -w "$COUNCIL_DIR" ]]; then
    fail "$E_PERMISSION" "council $kind mutates the governance roster — it writes ${COUNCIL_DIR} (root-owned) and must be sudo-run: sudo 5dive council $kind $*"
  fi
  [[ -f "$COUNCIL_GENESIS" && -f "$COUNCIL_LINEAGE" ]] || fail "$E_VALIDATION" "the Council has no genesis roster — seed it first: sudo 5dive council init …"
  local subject="" lens="" mode="adversarial" dry=0 a
  for a in "$@"; do
    case "$a" in
      --subject=*) subject="${a#--subject=}" ;;
      --lens=*)    lens="${a#--lens=}" ;;
      --mode=*)    mode="${a#--mode=}" ;;
      --dry-run)   dry=1 ;;
    esac
  done
  [[ -n "$subject" ]] || fail "$E_USAGE" "council $kind needs --subject=<seat id>"

  # Current roster + hash-chain head come from the SEALED lineage tail (the source of truth).
  local head head_seats prev_digest last_seq seq
  head="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null)"
  head_seats="$(printf '%s' "$head" | jq -c '.record.seats // []' 2>/dev/null)"
  [[ -n "$head_seats" && "$head_seats" != "null" && "$head_seats" != "[]" ]] || fail "$E_GENERIC" "cannot read the current roster from the lineage head (fail-closed)"
  prev_digest="$(printf '%s' "$head" | jq -r '.digest // ""')"
  last_seq="$(printf '%s' "$head" | jq -r '.seq // -1')"; [[ "$last_seq" =~ ^[0-9]+$ ]] && seq=$((last_seq+1)) || seq=0

  # PLAN — classify + recuse + build the deliberation question (fail-closed on a bad subject).
  local plan cls question recuse
  plan="$(node "$dir/cli.mjs" motion-plan --kind="$kind" --subject="$subject" --seats-json="$head_seats")" || return $?
  cls="$(printf '%s' "$plan" | jq -r '.class')"
  question="$(printf '%s' "$plan" | jq -r '.question')"
  recuse="$(printf '%s' "$plan" | jq -r '(.recuse // []) | join(",")')"

  if (( dry )); then
    if (( JSON_MODE )); then printf '%s' "$plan" | jq '{ok:true,data:(. + {dryRun:true})}'
    else echo "would convene ($cls, recuse=${recuse:-none}): $question"; fi
    return 0
  fi

  # CONVENE the primary council (bench=council -> genesis-gated + veto-offered), subject recused,
  # class auto-derived in the engine from --motion-*. The sealed receipt is the audit of the vote.
  local env verdict receipt_digest rec_out
  env="$("$(_council_bin)" council convene "$question" --json --bench=council --mode="$mode" \
    --motion-kind="$kind" --motion-subject="$subject" ${recuse:+--recuse="$recuse"})" || fail "$E_GENERIC" "motion convene failed"
  verdict="$(printf '%s' "$env" | jq -c '.data.verdict')"
  receipt_digest="$(printf '%s' "$env" | jq -r '.data.sealedDigest // empty')"
  rec_out="$(printf '%s' "$verdict" | jq -r '.recommendation // "reject"')"
  [[ -n "$verdict" && "$verdict" != "null" ]] || fail "$E_GENERIC" "motion convene returned no verdict"

  if [[ "$rec_out" != "approve" ]]; then
    # Motion did not carry — roster unchanged, NOTHING written to the lineage.
    if (( JSON_MODE )); then printf '%s' "$env" | jq --arg c "$cls" '{ok:true,data:{motion:$c,carried:false,outcome:(.data.verdict.recommendation),tally:(.data.verdict.tally),receipt:(.data.sealedDigest // null)}}'
    else echo "council $kind: NOT carried ($rec_out, tally $(printf '%s' "$verdict" | jq -r '"a\(.tally.approve)/r\(.tally.reject)/e\(.tally.escalate)"')) — roster unchanged"; fi
    return 0
  fi

  # APPLY — build the hash-chained motion record + its canonical (roster mutated in-code), root-seal,
  # append the lineage, THEN persist the new roster. Seal-first so a bad seal never mutates the roster.
  local stamped threshold_json veto_json apply canonical bench_seats
  stamped="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  threshold_json="$(jq -c '.threshold // {rule:"majority"}' "$COUNCIL_GENESIS" 2>/dev/null)"
  veto_json="$(jq -c '.veto // null' "$COUNCIL_GENESIS" 2>/dev/null)"
  apply="$(node "$dir/cli.mjs" motion-apply --kind="$kind" --subject="$subject" ${lens:+--lens="$lens"} \
    --seats-json="$head_seats" --verdict="$verdict" --threshold-json="$threshold_json" --veto-json="$veto_json" \
    --registry="$COUNCIL_REGISTRY" --prev-digest="$prev_digest" --seq="$seq" --stamped-at="$stamped" \
    --receipt-digest="$receipt_digest")" || return $?
  canonical="$(printf '%s' "$apply" | jq -r '.canonical')"
  [[ -n "$canonical" ]] || fail "$E_GENERIC" "motion produced no canonical record"
  local digest; digest="$(printf '%s' "$canonical" | _council_seal_stdin)" || digest=""
  [[ -n "$digest" ]] || fail "$E_GENERIC" "could not seal the motion record on the gate-proof rail (need root + an enforce key) — roster NOT changed"

  # Append the hash-chained lineage record.
  printf '%s' "$apply" | jq -c --arg d "$digest" --arg p "$prev_digest" --arg s "$stamped" \
    '{seq: .record.seq, kind: "motion", stampedAt: $s, digest: $d, prevDigest: $p, canonical: .canonical, record: .record}' \
    >> "$COUNCIL_LINEAGE"
  # Persist the new roster into the motion-governed council bench (only now the seal succeeded).
  bench_seats="$(printf '%s' "$apply" | jq -c '.benchSeats')"
  local tmpreg; tmpreg="$(mktemp)"
  jq --argjson seats "$bench_seats" '(.council.seats)=$seats | (.council.genesis)=true' "$COUNCIL_REGISTRY" > "$tmpreg" 2>/dev/null && mv "$tmpreg" "$COUNCIL_REGISTRY" || rm -f "$tmpreg"

  if (( JSON_MODE )); then
    printf '%s' "$apply" | jq --arg d "$digest" --arg r "$receipt_digest" '{ok:true,data:{motion:.class,carried:true,subject:(.record.motion.subject),seats:.seats,sealedDigest:$d,receiptDigest:$r,seq:.record.seq}}'
  else
    echo "council $kind: CARRIED — '$subject' ${kind}d"
    echo "roster:   $(printf '%s' "$apply" | jq -r '.seats | join(", ")')"
    echo "motion:   sealed (${digest:0:16}…) + hash-chained into lineage (seq $seq)"
    echo "receipt:  convene ${receipt_digest:0:16}…"
  fi
}

# CNCL-15 — council amend: rewrite the constitution via a constitutional-class motion (2/3 + full
# quorum + founder veto). Sudo-gated (writes the root-owned 5dive.md + lineage). Validates the
# proposed file, convenes the amendment, and ONLY on a pass seals the new digest into the chain
# (seal FIRST) then swaps the on-disk 5dive.md. A non-pass leaves the constitution untouched.
_council_amend() {
  local dir="$1"; shift
  mkdir -p "$COUNCIL_DIR" 2>/dev/null || true
  if [[ ! -w "$COUNCIL_DIR" ]]; then
    fail "$E_PERMISSION" "council amend rewrites the constitution — it writes ${COUNCIL_DIR} + $(_council_constitution_path) (root-owned) and must be sudo-run: sudo 5dive council amend $*"
  fi
  [[ -f "$COUNCIL_GENESIS" && -f "$COUNCIL_LINEAGE" ]] || fail "$E_VALIDATION" "the Council has no genesis roster — seed it first: sudo 5dive council init …"
  local file="" mode="deliberate" dry=0 a
  for a in "$@"; do
    case "$a" in
      --file=*) file="${a#--file=}" ;;
      --mode=*) mode="${a#--mode=}" ;;
      --dry-run) dry=1 ;;
    esac
  done
  [[ -n "$file" ]] || fail "$E_USAGE" "council amend needs --file=<path to the proposed 5dive.md>"
  [[ -f "$file" ]] || fail "$E_NOT_FOUND" "no such file: $file"
  # Validate the proposed constitution parses+normalizes BEFORE convening (fail-closed).
  node "$dir/cli.mjs" constitution --path="$file" >/dev/null 2>&1 || fail "$E_VALIDATION" "the proposed $file is not a valid constitution — refusing to convene an amendment on it (fail-closed)"
  local new_digest; new_digest="$(sha256sum < "$file" 2>/dev/null | awk '{print $1}')"
  [[ -n "$new_digest" ]] || fail "$E_GENERIC" "could not digest the proposed constitution $file"

  # Current roster + hash-chain head from the SEALED lineage tail.
  local head head_seats prev_digest last_seq seq
  head="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null)"
  head_seats="$(printf '%s' "$head" | jq -c '.record.seats // []' 2>/dev/null)"
  [[ -n "$head_seats" && "$head_seats" != "null" && "$head_seats" != "[]" ]] || fail "$E_GENERIC" "cannot read the current roster from the lineage head (fail-closed)"
  prev_digest="$(printf '%s' "$head" | jq -r '.digest // ""')"
  last_seq="$(printf '%s' "$head" | jq -r '.seq // -1')"; [[ "$last_seq" =~ ^[0-9]+$ ]] && seq=$((last_seq+1)) || seq=0

  local plan question
  plan="$(node "$dir/cli.mjs" amend-plan --seats-json="$head_seats" --constitution="@$file" --constitution-digest="$new_digest")" || return $?
  question="$(printf '%s' "$plan" | jq -r '.question')"

  if (( dry )); then
    if (( JSON_MODE )); then printf '%s' "$plan" | jq '{ok:true,data:(. + {dryRun:true, newDigest:"'"$new_digest"'"})}'
    else echo "would convene (constitutional amendment, digest ${new_digest:0:12}…): $question"; fi
    return 0
  fi

  # CONVENE the primary council as a constitutional AMEND motion (2/3 + full quorum + veto offer).
  local env verdict receipt_digest rec_out
  env="$("$(_council_bin)" council convene "$question" --json --bench=council --mode="$mode" --motion-kind=amend)" || fail "$E_GENERIC" "amend convene failed"
  verdict="$(printf '%s' "$env" | jq -c '.data.verdict')"
  receipt_digest="$(printf '%s' "$env" | jq -r '.data.sealedDigest // empty')"
  rec_out="$(printf '%s' "$verdict" | jq -r '.recommendation // "reject"')"
  [[ -n "$verdict" && "$verdict" != "null" ]] || fail "$E_GENERIC" "amend convene returned no verdict"

  if [[ "$rec_out" != "approve" ]]; then
    if (( JSON_MODE )); then printf '%s' "$env" | jq '{ok:true,data:{motion:"constitutional",carried:false,outcome:(.data.verdict.recommendation),tally:(.data.verdict.tally),receipt:(.data.sealedDigest // null)}}'
    else echo "council amend: NOT carried ($rec_out) — constitution unchanged"; fi
    return 0
  fi

  # APPLY — seal FIRST (record carries the NEW digest), append the lineage, THEN swap the on-disk
  # 5dive.md. Seal-first so a failed seal never changes the enforced constitution.
  local stamped threshold_json veto_json apply canonical digest
  stamped="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  threshold_json="$(jq -c '.threshold // {rule:"majority"}' "$COUNCIL_GENESIS" 2>/dev/null)"
  veto_json="$(jq -c '.veto // null' "$COUNCIL_GENESIS" 2>/dev/null)"
  apply="$(node "$dir/cli.mjs" amend-apply --seats-json="$head_seats" --verdict="$verdict" \
    --threshold-json="$threshold_json" --veto-json="$veto_json" --constitution-digest="$new_digest" \
    --prev-digest="$prev_digest" --seq="$seq" --stamped-at="$stamped" --receipt-digest="$receipt_digest")" || return $?
  canonical="$(printf '%s' "$apply" | jq -r '.canonical')"
  [[ -n "$canonical" ]] || fail "$E_GENERIC" "amend produced no canonical record"
  digest="$(printf '%s' "$canonical" | _council_seal_stdin)" || digest=""
  [[ -n "$digest" ]] || fail "$E_GENERIC" "could not seal the amendment record on the gate-proof rail (need root + an enforce key) — constitution NOT changed"

  printf '%s' "$apply" | jq -c --arg d "$digest" --arg p "$prev_digest" --arg s "$stamped" \
    '{seq: .record.seq, kind: "motion", stampedAt: $s, digest: $d, prevDigest: $p, canonical: .canonical, record: .record}' \
    >> "$COUNCIL_LINEAGE"
  # Swap the on-disk constitution ONLY now the digest is sealed into the chain. cp+re-digest guard:
  # a copy that does not reproduce the sealed digest is refused (leaves the old file, verify green).
  local cpath tmpc; cpath="$(_council_constitution_path)"; tmpc="$(mktemp)"
  if cp "$file" "$tmpc" && [[ "$(sha256sum < "$tmpc" | awk '{print $1}')" == "$new_digest" ]]; then
    ( umask 022; cat "$tmpc" > "$cpath" ) && rm -f "$tmpc"
  else
    rm -f "$tmpc"
    warn "amendment sealed into the chain but the on-disk $cpath could not be updated — restore it from $file; verify will flag drift until then"
  fi

  if (( JSON_MODE )); then
    printf '%s' "$apply" | jq --arg d "$digest" --arg r "$receipt_digest" --arg nd "$new_digest" '{ok:true,data:{motion:"constitutional",carried:true,constitutionDigest:$nd,sealedDigest:$d,receiptDigest:$r,seq:.record.seq}}'
  else
    echo "council amend: CARRIED — constitution ratified"
    echo "const:    ${new_digest:0:16}… -> $cpath"
    echo "motion:   sealed (${digest:0:16}…) + hash-chained into lineage (seq $seq)"
    echo "receipt:  convene ${receipt_digest:0:16}…"
  fi
}

cmd_council() {
  command -v node >/dev/null 2>&1 || fail "$E_GENERIC" "5dive council needs node on PATH"
  command -v jq   >/dev/null 2>&1 || fail "$E_GENERIC" "5dive council needs jq on PATH"
  local sub="${1:-}"; [[ $# -gt 0 ]] && shift || true
  case "$sub" in
    ""|-h|--help|help) _council_help; return 0 ;;
    convene|bench|init|lineage|veto|gate-clear|rot-triage|roster|log|record|verify|promote|demote|expel|amend|sign-vote|verify-votes|ballot-tap) ;;
    *) fail "$E_USAGE" "unknown council command: $sub (convene|bench|init|lineage|roster|log|record|verify|promote|demote|expel|amend|veto|gate-clear|rot-triage|sign-vote|verify-votes|ballot-tap)" ;;
  esac

  local dir; dir="$(mktemp -d -t 5dive-council.XXXXXX)" || fail "$E_GENERIC" "mktemp failed"
  # shellcheck disable=SC2064
  trap "rm -rf '$dir'" RETURN
  _council_write_runtime "$dir"

  # CNCL-8: council init (human-seeded genesis) + lineage verify -----------
  if [[ "$sub" == "init" || "$sub" == "lineage" ]]; then
    _council_init_or_lineage "$sub" "$dir" "$@"
    return $?
  fi

  # CNCL-9: authenticated founder veto exercise (the confirmed tap) ---------
  if [[ "$sub" == "veto" ]]; then
    _council_veto "$dir" "$@"
    return $?
  fi

  # CNCL-12: gate-rot wiring — clear a tier-1 gate / rot-triage stale tier-2 gates.
  if [[ "$sub" == "gate-clear" ]]; then
    _council_gate_clear "$dir" "$@"
    return $?
  fi
  if [[ "$sub" == "rot-triage" ]]; then
    _council_rot_triage "$dir" "$@"
    return $?
  fi

  # CNCL-11: governance surface — roster / log / verify (read) + promote|demote|expel (motion).
  if [[ "$sub" == "roster" ]]; then _council_roster "$dir" "$@"; return $?; fi
  if [[ "$sub" == "log" ]];    then _council_log    "$dir" "$@"; return $?; fi
  if [[ "$sub" == "record" ]]; then _council_record "$dir" "$@"; return $?; fi
  if [[ "$sub" == "verify" ]]; then _council_verify "$dir" "$@"; return $?; fi
  if [[ "$sub" == "promote" || "$sub" == "demote" || "$sub" == "expel" ]]; then
    _council_motion "$dir" "$sub" "$@"; return $?
  fi

  if [[ "$sub" == "amend" ]]; then
    _council_amend "$dir" "$@"; return $?
  fi

  # CNCL-10: co-signed votes — the per-seat sign-at-source (`sign-vote`) + the verifier
  # (`verify-votes`) are pure engine verbs a SEAT invokes from its OWN harness during a
  # dispatched convene (the shell IS the product surface here — a seat has no node runtime
  # of its own). No sudo, no root seal, no lineage write: pass straight through to cli.mjs
  # (like gate-map) and preserve its stdout contract (the `COUNCIL-SIG:` line / JSON row)
  # AND its exit code (verify-votes exits non-zero on a forged/replayed/revoked vote so the
  # seat harness can gate on it). Both take their roster/key inline (--roster / --key-file),
  # so no --registry: pass the seat's args straight through, verbatim.
  if [[ "$sub" == "sign-vote" || "$sub" == "verify-votes" ]]; then
    node "$dir/cli.mjs" "$sub" "$@"; return $?
  fi

  # DIVE-1565: human ballot TAP -> task-close bridge. The DIVE-1566 telegram plugin parses the tapped
  # button's `cvote:<ref>:<code>:<nonce>` callback_data and shells THIS verb. It is a pure passthrough
  # (no sudo, no root seal, no lineage write): the verb prefix-accepts the ref to a unique OPEN human
  # ballot, verifies the one-time nonce against the ballot body's stored digest, and CLOSES that same
  # CNCL-18 ballot task with the `COUNCIL-VOTE: <verb> :: (human tap)` line — the SAME ingress an agent
  # heartbeat writes, no second write path. Preserve its stdout JSON + exit code so the plugin can gate.
  if [[ "$sub" == "ballot-tap" ]]; then
    node "$dir/cli.mjs" ballot-tap "$@"; return $?
  fi

  if [[ "$sub" == "bench" ]]; then
    local action="${1:-ls}"
    case "$action" in
      add|rm)
        mkdir -p "$COUNCIL_DIR" 2>/dev/null || true
        if [[ ! -w "$COUNCIL_DIR" ]]; then
          fail "$E_PERMISSION" "editing standing benches writes ${COUNCIL_REGISTRY} (root-owned) — re-run via: sudo 5dive council bench $action $*"
        fi
        ;;
    esac
    # cli.mjs always emits JSON; format it here so text/JSON honor the global contract.
    local braw; braw="$(node "$dir/cli.mjs" bench "$@" --registry="$COUNCIL_REGISTRY")" || return $?
    if (( JSON_MODE )); then
      printf '%s' "$braw" | jq '{ok:true, data: .}'
    elif [[ "$action" == "ls" ]]; then
      printf '%s' "$braw" | jq -r '.benches[] | "  \(.name)\t\(if .builtin then "(built-in)" else "" end)\(if .custom then "(custom)" else "" end)"'
    elif [[ "$action" == "show" ]]; then
      printf '%s' "$braw" | jq -r '"bench:  \(.name)\ndesc:   \(.description)\nmode:   \(.mode)\nseats:  \(.seats | map(.id) | join(", "))"'
    else
      printf '%s' "$braw" | jq -r 'to_entries[0] | "OK — bench \(.value) \(.key)"'
    fi
    return 0
  fi

  # convene ------------------------------------------------------------------
  local stamped; stamped="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  local genesis_exists=0; [[ -f "$COUNCIL_GENESIS" ]] && genesis_exists=1

  # CNCL-9 (main gate amendment 3): a `--veto-by` / `--veto-reason` on convene is a FORGE attempt —
  # an agent trying to assert a veto from a plain CLI string. cli.mjs refuses it (exit 9), but the
  # acceptance says "refused + LOGGED", so we write the durable audit line HERE before dispatch,
  # independent of cli's ordering (the refusal message still comes from cli). A test asserts it.
  local _fa _forge=""
  for _fa in "$@"; do
    case "$_fa" in
      --veto-by=*|--veto-by|--veto-reason=*|--veto-reason)
        _forge="${_forge:+$_forge,}${_fa%%=*}" ;;
    esac
  done
  [[ -n "$_forge" ]] && _council_veto_audit "forge-attempt-veto-by" "convene" "$_forge"

  # CNCL-9: on a PRIMARY-council convene we OFFER the founder veto to the genesis principal. The
  # offer rides inside the sealed receipt; the flip only ever happens later via an authenticated
  # tap (`council veto exercise`). We pass the genesis-resolved principal + the HOLD window (the
  # veto_hold constitution key; env-overridable seam until CNCL-13/14) down to the engine so the
  # offer is recorded on a pass. Ad-hoc panels (no genesis) get no offer.
  local -a veto_args=()
  local veto_hold="${COUNCIL_VETO_HOLD_SECS:-900}" constitution_json="" constitution_source="defaults" constitution_valid="true" constitution_principal=""
  constitution_json="$(_council_constitution_json 2>/dev/null || true)"
  if [[ -n "$constitution_json" ]]; then
    constitution_source="$(printf '%s' "$constitution_json" | jq -r '.source // "defaults"')"
    constitution_valid="$(printf '%s' "$constitution_json" | jq -r '.valid // true')"
    constitution_principal="$(printf '%s' "$constitution_json" | jq -r '.veto.principal // empty')"
    if [[ "$constitution_source" == "file" ]]; then
      veto_hold="$(printf '%s' "$constitution_json" | jq -r '.veto.holdSecs')"
    elif [[ "$constitution_valid" == "false" ]]; then
      veto_hold=900
      warn "invalid $(_council_constitution_path); council is using built-in governance defaults"
    fi
  fi
  [[ "$veto_hold" =~ ^[0-9]+$ ]] || veto_hold=900
  if (( genesis_exists )); then
    local g_principal g_resolved
    g_principal="$(jq -r '.veto.principal // empty' "$COUNCIL_GENESIS" 2>/dev/null)"
    g_resolved="$(jq -r '.veto.resolved // empty' "$COUNCIL_GENESIS" 2>/dev/null)"
    if [[ "$constitution_source" == "file" && -n "$constitution_principal" ]]; then
      if [[ "$constitution_principal" == "$g_principal" ]]; then
        g_principal="$constitution_principal"
      else
        warn "constitution veto principal '$constitution_principal' has no genesis-resolved recipient; veto offer omitted fail-closed"
        g_principal=""; g_resolved=""
      fi
    fi
    if [[ -n "$g_principal" && -n "$g_resolved" ]]; then
      veto_args=(--veto-principal="$g_principal" --veto-resolved="$g_resolved" --veto-window="$veto_hold")
    fi
  fi

  # CNCL-15: a primary-council convene under a DRIFTED constitution must escalate, not enforce
  # forged governance. Compare the sealed digest to the on-disk file; on drift pass the flag so
  # node short-circuits to an escalate verdict (fail-closed — a bad drift-check also escalates).
  local drift_flag=""
  _council_constitution_drift "$dir" >/dev/null 2>&1 || drift_flag="--constitution-drift=1"

  # CNCL-19: build the case-law precedent pool from the SEALED convene receipt log and hand it to
  # the engine. The engine deterministically selects the top-k relevant priors, injects them as
  # HISTORY into the blind ballots (never another CURRENT seat's take), and seals the followed/
  # departed citation into this receipt. Pure read-only projection of already-sealed receipts; a
  # missing/empty log yields no pool (no-op, byte-identical to pre-CNCL-19).
  local -a precedent_args=(); local _pp_tmp=""
  if compgen -G "${COUNCIL_RECEIPTS}/*.json" >/dev/null 2>&1; then
    # CNCL-29: stage the pool in a writable temp dir, NOT ${COUNCIL_DIR} (root-owned; a non-root/cron
    # caller hit EPERM there and silently ran with NO precedents — CNCL-19 case-law parity was lost on
    # every scheduled convene). mktemp keeps it collision-safe; an empty _pp_tmp on mktemp failure just
    # falls through to the no-pool path below (byte-identical to pre-CNCL-19).
    _pp_tmp="$(mktemp "${TMPDIR:-/tmp}/5dive-precedent-pool.XXXXXX" 2>/dev/null || true)"
    if jq -s '[.[] | select((.verdict.recommendation // "") != "")
                | {digest:(.sealedDigest // ""), question:(.question // ""),
                   recommendation:(.verdict.recommendation // ""),
                   brief:(.verdict.brief // .verdict.dissent // ""), stampedAt:(.stampedAt // "")}]' \
         "${COUNCIL_RECEIPTS}"/*.json > "$_pp_tmp" 2>/dev/null; then
      precedent_args=(--precedent-pool="$_pp_tmp")
    else
      rm -f "$_pp_tmp" 2>/dev/null || true; _pp_tmp=""
    fi
  fi

  local raw
  raw="$(node "$dir/cli.mjs" convene "$@" "${veto_args[@]}" "${precedent_args[@]}" ${drift_flag} --constitution-path="$(_council_constitution_path)" --registry="$COUNCIL_REGISTRY" --genesis-exists="$genesis_exists" --stamped-at="$stamped")"; local _rc=$?
  [[ -n "$_pp_tmp" ]] && rm -f "$_pp_tmp" 2>/dev/null || true
  (( _rc == 0 )) || return $_rc

  # Seal the receipt canonical at the root HMAC rail — a standalone engine has no
  # key, so the seal (via gate-proof) is what makes the verdict tamper-evident. The
  # founder veto + dissent already ride INSIDE the signed bytes (canonicalTranscript).
  local base_canonical canonical digest=""
  base_canonical="$(printf '%s' "$raw" | jq -r '.receipt.canonical // empty')"
  if [[ -n "$base_canonical" ]]; then
    # CNCL-9: if the sealed verdict carries a veto OFFER (a primary-council pass), stamp the HOLD
    # deadline (executeAfter = sealedAt + veto_hold) and mint a one-time tap nonce bound to the
    # offered recipient. AMENDMENT (main gate): mint these BEFORE sealing and FOLD their binding
    # (nonce DIGEST + executeAfter) INTO the canonical via seal-augment, so they are covered by the
    # same HMAC as the rest of the receipt. Pre-amendment they were stamped onto the unsealed
    # wrapper AFTER the seal, so the exercise-time re-seal (which only re-signs `.canonical`) did
    # not cover them and an edited `.vetoNonceDigest` slipped through. A base receipt (no offer)
    # gets no seal-binding line and stays byte-identical to CNCL-6/8.
    local offer_resolved execute_after="" veto_nonce="" veto_nonce_digest=""
    offer_resolved="$(printf '%s' "$raw" | jq -r '.verdict.vetoOffer.resolved // empty' 2>/dev/null)"
    if [[ -n "$offer_resolved" ]]; then
      execute_after="$(date -u -d "$stamped + ${veto_hold} seconds" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo "")"
      veto_nonce="$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
      veto_nonce_digest="$(_council_sha256 "$veto_nonce")"
      canonical="$(printf '%s' "$base_canonical" | node "$dir/cli.mjs" seal-augment --canonical=- --nonce-digest="$veto_nonce_digest" --execute-after="$execute_after")" || canonical="$base_canonical"
    else
      canonical="$base_canonical"
    fi
    if [[ "$(id -u)" -eq 0 ]]; then
      digest="$(printf '%s' "$canonical" | cmd_gate_proof_sign_stdin)" || digest=""
    else
      digest="$(printf '%s' "$canonical" | sudo -n 5dive gate-proof sign 2>/dev/null)" || digest=""
    fi
    if [[ -n "$digest" ]]; then
      mkdir -p "$COUNCIL_RECEIPTS" 2>/dev/null || true
      if [[ -w "$COUNCIL_RECEIPTS" ]]; then
        # Offline-test capture ONLY: when MOCK is on AND a sink path is provided, drop the raw nonce
        # so the bash e2e can present it at exercise. Double-gated on COUNCIL_MOCK (never set in a
        # real convene) + COUNCIL_VETO_NONCE_SINK, so PRODUCTION never writes the raw nonce to disk —
        # in prod it leaves solely via the _tg_send founder delivery leg (main gate amendment 2).
        if [[ -n "$veto_nonce" && -n "${COUNCIL_MOCK:-}" && -n "${COUNCIL_VETO_NONCE_SINK:-}" ]]; then
          ( umask 077; printf '%s\n' "$veto_nonce" > "$COUNCIL_VETO_NONCE_SINK" ) 2>/dev/null || true
        fi
        # The receipt stores the AUGMENTED canonical (with the sealed veto-binding line). The wrapper
        # still surfaces executeAfter + vetoNonceDigest for display/dashboard audit, but exercise no
        # longer TRUSTS them — it reads the binding back out of the verified canonical (fail-closed).
        # The raw nonce never touches the receipt; it is delivered solely to the founder via the ping.
        printf '%s' "$raw" | jq --arg d "$digest" --arg s "$stamped" --arg ea "$execute_after" --arg nd "$veto_nonce_digest" --arg canon "$canonical" \
          '{stampedAt:$s, sealedDigest:$d, council, question, disposition, verdict, canonical: $canon}
           + (if ($ea|length)>0 then {executeAfter:$ea} else {} end)
           + (if ($nd|length)>0 then {vetoNonceDigest:$nd} else {} end)
           + (if ((.subject // "")|length)>0 then {subject:.subject} else {} end)' \
          > "${COUNCIL_RECEIPTS}/${stamped//:/-}.json" 2>/dev/null || true
        # Fire the founder ping at seal (non-blocking, best-effort). Writes the durable digest-only
        # pings audit (0600) always; the live _tg_send notify (which carries the raw nonce) is
        # skipped under MOCK. The tappable button + its callback -> `council veto exercise` routing
        # is the telegram-plugin leg that pairs with a live genesis (post-seed).
        if [[ -n "$offer_resolved" ]]; then
          _council_veto_ping "$offer_resolved" "$digest" "$execute_after" "$veto_nonce" || true
        fi
      fi
    fi
  fi

  # DIVE-1494 (1): read-only convene NOTICE. Broadcast the verdict summary + tally to a configured
  # council-notify chat over the SAME guarded-optional `_tg_send` seam the veto leg uses (the plugin
  # provides it; council never hard-depends on it). Distinct from the founder veto ping: this carries
  # NO nonce and no tap — it is a read-only digest of the outcome. Opt-in via COUNCIL_NOTIFY (a chat
  # id/handle); silent when unset, under MOCK, or when the plugin hasn't installed `_tg_send`.
  # Best-effort + non-blocking so a notify failure never affects the sealed verdict.
  if [[ -n "${COUNCIL_NOTIFY:-}" ]]; then
    local n_council n_disp n_rec n_tally n_conf n_q n_short n_seal n_msg
    n_council="$(printf '%s' "$raw" | jq -r '.council // "council"')"
    n_disp="$(printf '%s' "$raw" | jq -r '.disposition // "?"')"
    n_rec="$(printf '%s' "$raw" | jq -r '.verdict.recommendation // "?"')"
    n_tally="$(printf '%s' "$raw" | jq -r '.verdict.tally | "a\(.approve)/r\(.reject)/e\(.escalate)"' 2>/dev/null)"
    n_conf="$(printf '%s' "$raw" | jq -r '.verdict.confidence // "?"')"
    n_q="$(printf '%s' "$raw" | jq -r '.question // ""')"
    n_short="${n_q:0:80}"; [[ "${#n_q}" -gt 80 ]] && n_short="${n_short}…"
    if [[ -n "$digest" ]]; then n_seal="receipt ${digest:0:12}… (sealed)"; else n_seal="unsealed"; fi
    n_msg="Council ${n_council}: ${n_disp} (rec=${n_rec}, tally ${n_tally}, conf ${n_conf}) — \"${n_short}\" · ${n_seal}"
    # Offline-test capture ONLY (double-gated on MOCK + an explicit sink, mirroring the veto
    # COUNCIL_VETO_NONCE_SINK seam): drop the composed notice so the bash e2e can assert its content
    # without a live telegram rail. PRODUCTION (non-MOCK) never writes the sink and delivers solely
    # via the guarded-optional `_tg_send` seam the plugin provides.
    if [[ -n "${COUNCIL_MOCK:-}" && -n "${COUNCIL_NOTIFY_SINK:-}" ]]; then
      ( umask 077; printf '%s\n' "$n_msg" >> "$COUNCIL_NOTIFY_SINK" ) 2>/dev/null || true
    elif [[ -z "${COUNCIL_MOCK:-}" ]] && command -v _tg_send >/dev/null 2>&1; then
      _tg_send "$COUNCIL_NOTIFY" "$n_msg" >/dev/null 2>&1 || true
    fi
  fi

  if (( JSON_MODE )); then
    printf '%s' "$raw" | jq --arg d "$digest" '{ok:true, data: (. + {sealedDigest: $d})}'
  else
    local council q disp rec tally conf dissent brief
    council="$(printf '%s' "$raw" | jq -r '.council')"
    q="$(printf '%s' "$raw" | jq -r '.question')"
    disp="$(printf '%s' "$raw" | jq -r '.disposition')"
    rec="$(printf '%s' "$raw" | jq -r '.verdict.recommendation')"
    tally="$(printf '%s' "$raw" | jq -r '.verdict.tally | "a\(.approve)/r\(.reject)/e\(.escalate)"')"
    conf="$(printf '%s' "$raw" | jq -r '.verdict.confidence')"
    dissent="$(printf '%s' "$raw" | jq -r '.verdict.dissent // "none"')"
    brief="$(printf '%s' "$raw" | jq -r '.verdict.brief // empty')"
    echo "council:      $council"
    echo "question:     $q"
    echo "disposition:  $disp  (recommendation=$rec, tally=$tally, confidence=$conf)"
    [[ -n "$dissent" && "$dissent" != "none" ]] && echo "dissent:      $dissent"
    [[ -n "$brief" ]] && echo "brief:        $brief"
    if [[ -n "$digest" ]]; then
      echo "receipt:      sealed (${digest:0:16}…)"
    else
      echo "receipt:      unsealed (no gate-proof key / not root — run via sudo to seal)"
    fi
  fi
}

# In-process root seal: reuse the existing gate-proof signer without a re-exec when
# we are already root (keeps the HMAC key handling in one place).
cmd_gate_proof_sign_stdin() { cmd_gate_proof sign; }
