# ==================== constitution kernel (DIVE-4869, DIVE-4893) ====================
# CORE-owned constitution: where constitution.yaml lives, the one parser
# (src/constitution/constitution.mjs, embedded below), the SEAL — the newest constitutionDigest in
# the council lineage, read as DATA — and, since the council left core (DIVE-4893), the SOLO writer
# of that seal. `task need`'s tier-2 floor and its lead-clear authority call the read half on every
# box; `constitution set|edit` calls the write half with no council installed.
#
# Decision (DIVE-4869 body): the seal stays the council lineage file at its existing path — core
# needs no council code to trust it, and no box needs a migration. The council PLUGIN
# (5dive-ai/5dive-council) is the only writer of MULTI-seat records; core writes only a
# single-principal genesis (a solo direct-seal). Both append to the same hash chain, which is why
# src/constitution/seal.mjs is a verbatim copy of the council's genesis writer and why
# tests/constitution_kernel_unit.sh pins its canonical bytes to the pre-move engine's.
#
# This file is GENERATED by src/constitution/gen_kernel.mjs from this template plus
# src/constitution/{constitution,seal,cli}.mjs. Edit those and re-run the generator, never the output.

COUNCIL_DIR="${STATE_DIR}/council"
COUNCIL_GENESIS="${COUNCIL_DIR}/genesis.json"
COUNCIL_REGISTRY="${COUNCIL_DIR}/benches.json"
COUNCIL_LINEAGE="${STATE_DIR}/council/lineage.jsonl"

_constitution_path() {
  # An explicit override wins verbatim — no legacy migration on a caller-chosen path.
  if [[ -n "${FIVEDIVE_CONSTITUTION_FILE:-}" ]]; then
    printf '%s' "$FIVEDIVE_CONSTITUTION_FILE"; return
  fi
  local canonical="${STATE_DIR}/constitution.yaml" legacy="${STATE_DIR}/5dive.md"
  # DIVE-1686 belt-and-suspenders for the DIVE-1676 rename: a box ratified BEFORE
  # the rename holds its constitution at the legacy 5dive.md. Do a one-time rename to
  # the canonical name so post-rename builds keep reading it — a rename is byte-preserving,
  # so the sealed-digest drift check still matches. If the rename can't happen (e.g. a
  # non-root reader on root-owned STATE_DIR), fall back to reading the legacy file IN PLACE
  # this call, so the loader NEVER silently reverts to built-in defaults.
  if [[ ! -e "$canonical" && -f "$legacy" ]]; then
    if mv -n "$legacy" "$canonical" 2>/dev/null && [[ -e "$canonical" ]]; then
      echo "constitution: migrated legacy $legacy -> $canonical (DIVE-1676 rename)" >&2
    else
      printf '%s' "$legacy"; return
    fi
  fi
  printf '%s' "$canonical"
}

_constitution_write_runtime() {
  local dir="$1"
  cat > "$dir/constitution.mjs" <<'CONSTITUTION_KERNEL_MJS'
// The constitution kernel (DIVE-4869). CORE-owned: the one parser for constitution.yaml —
// hard-gate classes, thresholds, veto windows, standing authorities — plus the digests the
// sealed-drift check compares. It lives outside src/council/ because `task need`'s tier-2 floor
// and its lead-clear authority read it on every box, with or without the council deliberation
// engine. engine.mjs re-exports everything here, so council callers see no change and there is
// still exactly ONE parser. Moved verbatim from engine.mjs; edit it here, then re-run
// `node src/council/gen_cmd.mjs` and `node src/constitution/gen_kernel.mjs`.

import { createHash } from 'node:crypto'
import fs from 'node:fs'

// (P3.1b2) TIERED THRESHOLD POLICY. Per decision-CLASS pass rule + quorum, all config. A rule is
// 'flat' (fixed N), 'majority' (floor(seats/2)+1), or 'fraction' (ceil(value*seats), e.g. 2/3).
// `quorum` = how many CURRENT seats must vote for the result to count. This map is the single knob.
export const THRESHOLD_POLICY = {
  ordinary:       { rule: 'majority',            quorum: 'majority' },
  promote:        { rule: 'majority',            quorum: 'majority' },
  demote:         { rule: 'fraction', value: 2 / 3, quorum: 'majority' },
  expel:          { rule: 'fraction', value: 2 / 3, quorum: 'majority' },
  constitutional: { rule: 'fraction', value: 2 / 3, quorum: 'all', requireQuorum: true },
}

// CNCL-14 — constitution-as-data. Missing or malformed files fall back to these
// exact pre-constitution values; a valid constitution.yaml may replace them per org.
export const DEFAULT_HARD_GATE_CLASSES = {
  spend_billing: 'spend|spending|billing|invoice|invoices|invoiced|charge|charges|charged|charging|payment|payments|refund|refunds|refunded|subscription|subscriptions|price|prices|pricing|\\$[0-9]+|€[0-9]+',
  public_comms: 'publish|publishes|published|publishing|public post|announce|announces|announced|announcing|launch post|press|pressing|customer email|email customers|newsletter|blast|blasts|blasted|blasting',
  secrets: 'secret|secrets|credential|credentials|api key|api keys|token|password|passwords',
  destructive: 'delete|deletes|deleted|deleting|destroy|destroys|destroyed|destroying|teardown|wipe|wipes|wiped|wiping|purge|purges|purged|purging|drop[^.]{0,20}table|truncate|truncated|irreversible|revoke|revokes|revoked|revoking|dns|domain transfer',
}
export const DEFAULT_HARD_GATE_RX = Object.values(DEFAULT_HARD_GATE_CLASSES).join('|')

// DIVE-1702 — the constitution document schema version. `schema_version: 1` (integer) is the
// current, and only, supported version; the field is OPTIONAL and defaults to this when absent, so
// every existing comment-free constitution.yaml stays valid. A document declaring a HIGHER version
// than this CLI understands is rejected (fail-closed) — that agent must upgrade before enforcing an
// unknown schema. This is the single knob a future migration bumps.
export const CONSTITUTION_SCHEMA_VERSION = 1

// CNCL-15 — the digest embedded in a sealed genesis/amendment record is a plain content hash of
// the constitution.yaml bytes. Its integrity comes from riding INSIDE the root-sealed, hash-chained record
// (the file is forgeable, the chain is not). bash computes the on-disk digest with `sha256sum` for
// genesis/amend/verify so every realm agrees; this JS mirror is for the unit tests + cli fallback.
// This is the SOURCE digest (raw bytes) — comment/whitespace edits DO change it, which is exactly
// what the sealed-drift check wants (any hand-edit is drift). For a digest that ignores cosmetic
// churn, see policyDigest below.
export function digestConstitution(text) {
  return createHash('sha256').update(String(text == null ? '' : text), 'utf8').digest('hex')
}

// DIVE-1702 — deterministic serialization for the CANONICAL-POLICY digest: sort object keys at every
// level so key-reordering, comment-only, or whitespace edits to constitution.yaml all serialize to the
// SAME bytes. Pure (no clock/CSPRNG). Arrays keep their order (principal lists are order-significant).
export function canonicalPolicyJSON(v) {
  if (v === null || v === undefined) return 'null'
  if (Array.isArray(v)) return `[${v.map(canonicalPolicyJSON).join(',')}]`
  if (typeof v === 'object') return `{${Object.keys(v).sort().map(k => `${JSON.stringify(k)}:${canonicalPolicyJSON(v[k])}`).join(',')}}`
  return JSON.stringify(v)
}

// DIVE-1702 — the CANONICAL-POLICY digest: sha256 over the NORMALIZED constitution (schema version,
// bench, thresholds, veto, hard-gate classes, ship/comms), NOT the raw file. Two documents that
// differ only in comments, key order, or whitespace produce the same policyDigest — so an audit can
// tell a cosmetic edit (source digest changed, policy digest unchanged) from a real policy change.
// The derived `hardGateRegex` is dropped (it is a pure function of hardGates — including it would
// double-count and is redundant). Accepts either a normalized object or raw frontmatter.
export function policyDigest(normalizedOrRaw) {
  const n = (normalizedOrRaw && Object.hasOwn(normalizedOrRaw, 'hardGates')) ? normalizedOrRaw : normalizeConstitution(normalizedOrRaw)
  const { hardGateRegex, ...policy } = n
  return createHash('sha256').update(canonicalPolicyJSON(policy), 'utf8').digest('hex')
}

// CNCL-15 — constitution-drift check (pure). `sealedDigest` = the digest sealed in the newest
// genesis/amendment record ('' if the lineage predates constitution-as-data); `liveDigest` = the
// hash of the on-disk constitution.yaml ('' if the file is missing). FAILS CLOSED: a sealed digest with a
// missing or mismatched live file is drift — a drifted constitution is NOT enforced, convene
// escalates, and verify fails. Same digest realm on both sides (bash sha256sum, or this JS mirror).
export function constitutionDriftCheck({ sealedDigest, liveDigest }) {
  const sealed = String(sealedDigest || '')
  const live = String(liveDigest || '')
  if (!sealed) return { drifted: false, reason: 'no sealed constitution digest (pre-constitution-as-data lineage)' }
  if (!live) return { drifted: true, reason: 'a constitution digest is sealed in the chain but constitution.yaml is missing (fail-closed)' }
  if (sealed !== live) return { drifted: true, reason: `constitution.yaml digest ${live.slice(0, 12)}… does not match the sealed ${sealed.slice(0, 12)}… — an unsanctioned edit (amend via a constitutional-class council motion, do not hand-edit)` }
  return { drifted: false, reason: 'the live constitution.yaml matches the sealed constitution digest' }
}

// CNCL-15 — the v0 constitution `council init` seeds. It is the HUMAN-READABLE projection of the
// built-in DEFAULT_CONSTITUTION: round-trips back through parse+normalize to the exact defaults, so
// its sealed digest is a meaningful baseline. Single-quoted regex values survive the frontmatter
// parser byte-for-byte (no backslash processing). Amend it ONLY via `5dive council amend`.
export function renderConstitutionV0() {
  const c = DEFAULT_CONSTITUTION
  const gates = Object.entries(c.hardGates)
    .map(([k, v]) => `  ${k}: '${String(v).replace(/'/g, "''")}'`).join('\n')
  // DIVE-1701 — single-agent-first-class ordering: the GUARDRAILS a solo user edits
  // (hard_gates / ship / comms) come FIRST; the Council governance keys come LAST, clearly
  // demarcated + commented as OPTIONAL and dormant so a one-agent user never feels a company
  // is forced on them. ONE schema for both `constitution init` (unsealed seed) and `council
  // init` (sealed genesis) — key ORDER is cosmetic to the parser, so this round-trips to the
  // exact defaults either way.
  return `# 5dive company constitution (v0) — governance-as-DATA, not hardcode.
# This file is the human-readable PROJECTION of your governance policy. On its own it is
# forgeable (anyone with fs write); the AUTHORITY is the sealed digest: once sealed, enforcement
# checks this file's digest against the sealed baseline and FAILS CLOSED on drift (a drifted
# constitution is not enforced). After it is sealed, edit ONLY through:
#   · solo (no Council):  sudo 5dive constitution edit          (direct-seal, no convene)
#   · a multi-seat Council: sudo 5dive council amend --file=…    (2/3 + full quorum + founder veto)
#
# ===================================================================================
# GUARDRAILS — the machine-enforced policy. This is what a solo user edits.
# ===================================================================================
#
# hard_gates: named POSIX-ERE classes. Any content matching a class is forced through a human
# gate before it can proceed. Add/rename/rewrite classes freely; the values are DATA.
hard_gates:
${gates}
#
# ship: release guardrails (e.g. require_ci: true). Empty = no extra ship gate beyond hard_gates.
ship:
#
# comms: outbound-comms guardrails (e.g. public_requires_human: true). Empty = defaults.
comms:
#
# authority: standing authorities held by a NAMED agent (DIVE-2099). EMPTY = nobody holds one,
# which is the default — a fresh org grants nothing until it deliberately amends this in.
#   eng_approval_lead: <agent> — that ONE agent may clear tier-1 ENGINEERING approval gates on
#   its own authority instead of routing them to you. Every other guard still applies (approval
#   type only, tier 1 only, positive engineering classification, hard_gates floor, out-of-scope
#   exclusions). Deliberately NOT derived from the org chart: the chart is agent-writable, so
#   deriving authority from it would let the holder appoint itself. This value is enforced only
#   while the file matches its SEALED digest, so changing who holds it is an amendment, not an
#   edit. Example:
#     authority:
#       eng_approval_lead: main
#   gate_clear_leads: — a BLOCK list (one "  - <agent>" per line, as in the example below;
#   the inline [a, b] form is refused) of the agents allowed to CLEAR an approval/manual/access
#   gate that was ROUTED to them (DIVE-2233). The org chart still decides who a gate is routed
#   TO — that is a notification. This list decides who may clear one, so re-parenting the chart
#   moves the ping and never the authority. EMPTY = nobody may lead-clear and every routed gate
#   falls through to a human, which is the safe default and NOT an outage. Example:
#     authority:
#       gate_clear_leads:
#         - main
#         - marketing
authority:
#
# ===================================================================================
# COUNCIL — OPTIONAL, and DORMANT until you convene one.
# ===================================================================================
# Solo users can ignore everything below: these keys have NO effect until you run
# \`5dive council init\` to seed a multi-agent Council. They are seeded here (not hidden) so the
# upgrade path is visible without being forced. Vote thresholds, quorum, and the founder-veto
# window are DATA another org forks and rewrites for itself.
council:
  bench: ${c.council.bench}
quorum: ${c.quorum}
veto:
  hold_secs: ${c.veto.holdSecs}
  posthoc_secs: ${c.veto.posthocSecs}
# thresholds: per-class vote rules — defaults apply when omitted. Uncomment under a real Council
# to override, e.g.:
#   thresholds:
#     constitutional: { rule: fraction, value: 2/3, quorum: all, require_quorum: true }
`
}

export const DEFAULT_CONSTITUTION = {
  schemaVersion: CONSTITUTION_SCHEMA_VERSION,
  council: { bench: 'council' },
  quorum: 'majority',
  thresholds: THRESHOLD_POLICY,
  veto: { principals: [], principal: '', holdSecs: 900, posthocSecs: 172800 },
  hardGates: DEFAULT_HARD_GATE_CLASSES,
  hardGateRegex: DEFAULT_HARD_GATE_RX,
  ship: {},
  comms: {},
  // DIVE-2099 — standing authorities held by a named agent. Empty by default: a fresh org
  // grants nobody a standing clear until it deliberately amends this in.
  authority: { engApprovalLead: '', gateClearLeads: [] },
}

function yamlScalar(raw) {
  const s = String(raw).trim()
  if (!s) return {}
  if (s.startsWith('"') && s.endsWith('"')) return JSON.parse(s)
  if (s.startsWith("'") && s.endsWith("'")) return s.slice(1, -1).replace(/''/g, "'")
  if (s.startsWith('[') && s.endsWith(']')) {
    const inner = s.slice(1, -1).trim()
    const arr = inner ? inner.split(',').map(x => yamlScalar(x.trim())) : []
    // DIVE-3493 — remember that this array came from a FLOW sequence. Only
    // `authority.gate_clear_leads` cares (the node-free reader in src/task/need.sh reads a
    // block sequence and refuses a flow one on purpose), but the provenance has to be
    // recorded here because it is gone by the time the normalizer sees a plain array.
    // Non-enumerable so it never reaches JSON output, a digest, or a canonical record.
    Object.defineProperty(arr, 'yamlFlow', { value: true })
    return arr
  }
  if (/^(true|false)$/i.test(s)) return s.toLowerCase() === 'true'
  if (/^-?[0-9]+(?:\.[0-9]+)?$/.test(s)) return Number(s)
  if (/^(null|~)$/i.test(s)) return null
  return s
}

function stripYamlComment(line) {
  let single = false, double = false
  for (let i = 0; i < line.length; i++) {
    const c = line[i]
    if (c === "'" && !double) single = !single
    else if (c === '"' && !single && line[i - 1] !== '\\') double = !double
    else if (c === '#' && !single && !double && (i === 0 || /\s/.test(line[i - 1]))) return line.slice(0, i).trimEnd()
  }
  return line
}

// Deliberately small pure-YAML parser: mappings + scalar/flow-array values plus a BLOCK
// SEQUENCE of plain scalars are the whole enforced v0 schema. Unsupported list/object
// syntax fails closed to defaults rather than being partially interpreted.
//
// DIVE-3493 — the block sequence is here because the node-free authority reader in
// src/task/need.sh reads exactly that shape (and refuses a flow one on purpose, so it
// never grants authority from a syntax it only half-supports). Until this landed the two
// accepted DISJOINT subsets of YAML — this parser threw on `- name` while the reader threw
// away `[a, b]` — so `authority.gate_clear_leads` could not be set through any path, and
// the shipped template's own worked example failed the validator shipping beside it.
export function parseConstitutionFrontmatter(text) {
  const lines = String(text || '').replace(/\r\n/g, '\n').split('\n')
  const root = {}
  const stack = [{ indent: -1, value: root }]
  for (const original of lines) {
    if (!original.trim() || original.trimStart().startsWith('#')) continue
    if (original.includes('\t')) throw new Error('tabs are not allowed in constitution YAML')
    const indent = original.length - original.trimStart().length
    if (indent % 2) throw new Error('constitution YAML indentation must use two spaces')
    const line = stripYamlComment(original.trim())
    if (!line) continue
    if (line === '-' || line.startsWith('- ')) {
      // A sequence entry belongs to the nearest enclosing key. Pop only frames INDENTED
      // DEEPER than this entry: YAML lets a block sequence sit at its key's own indent
      // (`gate_clear_leads:` / `- main` both at 2) as well as one level in, and the
      // reader accepts both, so refusing either would re-open the same asymmetry.
      while (stack.length > 1 && stack[stack.length - 1].indent > indent) stack.pop()
      const frame = stack[stack.length - 1]
      if (!frame.owner) throw new Error('a block sequence must be the value of a key')
      if (!Array.isArray(frame.value)) {
        if (Object.keys(frame.value).length) throw new Error(`constitution key '${frame.key}' holds a mapping and a block sequence`)
        frame.value = frame.owner[frame.key] = []
      }
      const entry = line === '-' ? '' : line.slice(2).trim()
      if (!entry) throw new Error(`empty entry in the block sequence under '${frame.key}'`)
      if (/^([A-Za-z_][A-Za-z0-9_-]*):(\s|$)/.test(entry)) throw new Error(`block sequence entries must be plain scalars, not mappings (under '${frame.key}')`)
      const val = yamlScalar(entry)
      if (val !== null && typeof val === 'object') throw new Error(`block sequence entries must be plain scalars (under '${frame.key}')`)
      frame.value.push(val)
      continue
    }
    const m = line.match(/^([A-Za-z_][A-Za-z0-9_-]*):(?:\s+(.*))?$/)
    if (!m) throw new Error(`unsupported constitution YAML: ${line}`)
    while (stack.length > 1 && stack[stack.length - 1].indent >= indent) stack.pop()
    const parent = stack[stack.length - 1]
    if (Array.isArray(parent.value)) throw new Error(`constitution key '${parent.key}' holds a block sequence and cannot also hold keys`)
    if (indent > parent.indent + 2) throw new Error('constitution YAML skipped an indentation level')
    const key = m[1]
    if (['__proto__', 'prototype', 'constructor'].includes(key)) throw new Error('unsafe constitution key')
    if (Object.hasOwn(parent.value, key)) throw new Error(`duplicate constitution key: ${key}`)
    if (m[2] == null || m[2] === '') {
      parent.value[key] = {}
      stack.push({ indent, value: parent.value[key], owner: parent.value, key })
    } else {
      parent.value[key] = yamlScalar(m[2])
    }
  }
  return root
}

// Parse a fraction threshold into an exact ratio. Accepts 'a/b' (e.g. '2/3' -> 0.666…) or a
// bare 0<x<=1 number. Exact fractions dodge the truncated-decimal footgun: 0.667 rounds up
// (ceil(0.667*6)=5) where true 2/3 gives 4 on a 6-seat council. Returns NaN for non-fractions.
const FRACTION_RX = /^([1-9][0-9]*)\/([1-9][0-9]*)$/
function fractionValue(raw) {
  const frac = String(raw).trim().match(FRACTION_RX)
  return frac ? Number(frac[1]) / Number(frac[2]) : Number(raw)
}

function thresholdSpec(value, base, globalQuorum) {
  const out = { ...base }
  if (typeof value === 'string' || typeof value === 'number') {
    const v = String(value).trim()
    const frac = v.match(FRACTION_RX)
    if (frac) { out.rule = 'fraction'; out.value = Number(frac[1]) / Number(frac[2]); delete out.threshold }
    else if (v === 'majority') { out.rule = 'majority'; delete out.value; delete out.threshold }
    else if (v === 'all') { out.rule = 'fraction'; out.value = 1; delete out.threshold }
    else if (/^[1-9][0-9]*$/.test(v)) { out.rule = 'flat'; out.threshold = Number(v); delete out.value }
    else throw new Error(`invalid threshold: ${v}`)
  } else if (value && typeof value === 'object' && !Array.isArray(value)) {
    const unknown = Object.keys(value).filter(k => !['rule', 'threshold', 'value', 'quorum', 'require_quorum', 'requireQuorum'].includes(k))
    if (unknown.length) throw new Error(`unknown threshold field(s): ${unknown.join(', ')}`)
    if (value.rule != null) {
      const rule = String(value.rule)
      if (!['majority', 'fraction', 'flat'].includes(rule)) throw new Error(`invalid threshold rule: ${rule}`)
      out.rule = rule
    }
    if (value.threshold != null) { out.rule = 'flat'; out.threshold = Number(value.threshold); delete out.value }
    if (value.value != null) {
      const n = fractionValue(value.value)
      if (!Number.isFinite(n) || n <= 0 || n > 1) throw new Error(`invalid threshold fraction: ${value.value}`)
      out.rule = 'fraction'; out.value = n; delete out.threshold
    }
    if (value.quorum != null) out.quorum = value.quorum
    if (value.require_quorum != null) {
      if (typeof value.require_quorum !== 'boolean') throw new Error('require_quorum must be true or false')
      out.requireQuorum = value.require_quorum
    }
    if (value.requireQuorum != null) {
      if (typeof value.requireQuorum !== 'boolean') throw new Error('requireQuorum must be true or false')
      out.requireQuorum = value.requireQuorum
    }
  } else throw new Error('threshold must be a scalar or mapping')
  if (out.quorum == null) out.quorum = globalQuorum
  if (out.rule === 'fraction' && (!Number.isFinite(Number(out.value)) || Number(out.value) <= 0 || Number(out.value) > 1)) throw new Error('fraction threshold needs value >0 and <=1')
  if (out.rule === 'flat' && (!Number.isInteger(Number(out.threshold)) || Number(out.threshold) < 1)) throw new Error('flat threshold needs a positive integer')
  return out
}

function quorumSpec(value) {
  if (typeof value === 'number' && Number.isInteger(value) && value >= 0) return value
  const s = String(value)
  if (['majority', 'all', 'none'].includes(s)) return s
  if (/^[0-9]+$/.test(s)) return Number(s)
  throw new Error(`invalid quorum: ${s}`)
}

export function normalizeConstitution(raw = {}) {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error('constitution frontmatter must be a mapping')
  const unknownTop = Object.keys(raw).filter(k => !['schema_version', 'council', 'quorum', 'thresholds', 'veto', 'hard_gates', 'ship', 'comms', 'authority'].includes(k))
  if (unknownTop.length) throw new Error(`unknown constitution field(s): ${unknownTop.join(', ')}`)
  // DIVE-1702: OPTIONAL document version. Absent -> current (back-compat with every existing file).
  // Must be a positive integer; a version NEWER than this CLI understands is refused (fail-closed) so
  // an out-of-date agent never enforces a schema it cannot fully parse.
  let schemaVersion = CONSTITUTION_SCHEMA_VERSION
  if (Object.hasOwn(raw, 'schema_version')) {
    const sv = raw.schema_version
    if (!Number.isInteger(sv) || sv < 1) throw new Error('schema_version must be a positive integer')
    if (sv > CONSTITUTION_SCHEMA_VERSION) throw new Error(`constitution schema_version ${sv} is newer than this CLI supports (max ${CONSTITUTION_SCHEMA_VERSION}); upgrade 5dive to enforce it`)
    schemaVersion = sv
  }
  if (raw.council != null && (typeof raw.council !== 'object' || Array.isArray(raw.council))) throw new Error('council must be a mapping')
  const council = raw.council || {}
  const unknownCouncil = Object.keys(council).filter(k => k !== 'bench')
  if (unknownCouncil.length) throw new Error(`unknown council field(s): ${unknownCouncil.join(', ')}`)
  if (council.bench != null && (typeof council.bench !== 'string' || !council.bench.trim())) throw new Error('council.bench must be a non-empty string')
  const globalQuorum = quorumSpec(raw.quorum == null ? DEFAULT_CONSTITUTION.quorum : raw.quorum)
  const thresholds = {}
  if (raw.thresholds != null && (typeof raw.thresholds !== 'object' || Array.isArray(raw.thresholds))) throw new Error('thresholds must be a mapping')
  const configured = raw.thresholds || {}
  const unknownClasses = Object.keys(configured).filter(k => !Object.hasOwn(THRESHOLD_POLICY, k))
  if (unknownClasses.length) throw new Error(`unknown threshold class(es): ${unknownClasses.join(', ')}`)
  for (const cls of Object.keys(THRESHOLD_POLICY)) {
    thresholds[cls] = thresholdSpec(Object.hasOwn(configured, cls) ? configured[cls] : THRESHOLD_POLICY[cls], THRESHOLD_POLICY[cls], globalQuorum)
    const classValue = configured[cls]
    const classHasQuorum = classValue && typeof classValue === 'object' && Object.hasOwn(classValue, 'quorum')
    thresholds[cls].quorum = quorumSpec(thresholds[cls].quorum)
    if (raw.quorum != null && cls !== 'constitutional' && !classHasQuorum) thresholds[cls].quorum = globalQuorum
  }
  if (raw.veto != null && (typeof raw.veto !== 'object' || Array.isArray(raw.veto))) throw new Error('veto must be a mapping')
  const veto = raw.veto || {}
  const unknownVeto = Object.keys(veto).filter(k => !['principal', 'principals', 'hold_secs', 'posthoc_secs'].includes(k))
  if (unknownVeto.length) throw new Error(`unknown veto field(s): ${unknownVeto.join(', ')}`)
  if (veto.principal != null && typeof veto.principal !== 'string') throw new Error('veto.principal must be a string')
  if (veto.principals != null && (!Array.isArray(veto.principals) || veto.principals.some(x => typeof x !== 'string'))) throw new Error('veto.principals must be a list of strings')
  if (veto.principal && veto.principals) throw new Error('use veto.principal or veto.principals, not both')
  const principals = Array.isArray(veto.principals) ? veto.principals : (veto.principal ? [veto.principal] : [])
  const seconds = (v, fallback, field) => {
    if (v == null) return fallback
    if (!Number.isInteger(v) || v < 0) throw new Error(`${field} must be a non-negative integer`)
    return v
  }
  let hardGates = DEFAULT_CONSTITUTION.hardGates
  let hardGateRegex = DEFAULT_HARD_GATE_RX
  if (Object.hasOwn(raw, 'hard_gates')) {
    if (!raw.hard_gates || typeof raw.hard_gates !== 'object' || Array.isArray(raw.hard_gates)) throw new Error('hard_gates must be a mapping')
    hardGates = Object.fromEntries(Object.entries(raw.hard_gates).map(([k, v]) => {
      if (typeof v !== 'string') throw new Error(`hard_gates.${k} must be a regex string`)
      if (/\(\?|\\[bBdDsSwW]|\\[1-9]/.test(v)) throw new Error(`hard_gates.${k} uses syntax outside POSIX ERE`)
      return [k, v]
    }))
    hardGateRegex = Object.values(hardGates).filter(Boolean).map(x => `(${x})`).join('|') || 'a^'
    new RegExp(hardGateRegex, 'i')
  }
  for (const section of ['ship', 'comms']) {
    if (raw[section] != null && (typeof raw[section] !== 'object' || Array.isArray(raw[section]))) throw new Error(`${section} must be a mapping`)
  }
  // DIVE-2099 — `authority`: standing authorities held by a NAMED agent, granted by the
  // constitution itself rather than derived from the org chart (which is agent-writable, so
  // deriving from it lets the beneficiary self-grant). Absent/empty = nobody holds it; there is
  // no "everyone" value and no fallback. Bash reads this field node-free on the gate path and
  // trusts it ONLY when the file still matches the sealed digest, so the enforced value can only
  // change through a constitutional-class amendment.
  if (raw.authority != null && (typeof raw.authority !== 'object' || Array.isArray(raw.authority))) throw new Error('authority must be a mapping')
  const authority = raw.authority || {}
  const AUTHORITY_KEYS = ['eng_approval_lead', 'gate_clear_leads']
  const unknownAuthority = Object.keys(authority).filter(k => !AUTHORITY_KEYS.includes(k))
  if (unknownAuthority.length) throw new Error(`unknown authority field(s): ${unknownAuthority.join(', ')}`)
  if (authority.eng_approval_lead != null && typeof authority.eng_approval_lead !== 'string') throw new Error('authority.eng_approval_lead must be a string')
  const engApprovalLead = String(authority.eng_approval_lead || '').trim()
  // The same shape bash enforces (`_GATE_STANDING_LEAD_NAME_RX`): a plain agent name, so the
  // value stays a name comparison. `human:x`, `*`, `all`, paths and metacharacters are rejected
  // here rather than silently ignored at enforcement time.
  const AGENT_NAME_RE = /^[a-z0-9][a-z0-9_-]{0,31}$/
  if (engApprovalLead && !AGENT_NAME_RE.test(engApprovalLead)) throw new Error('authority.eng_approval_lead must be a plain agent name (a-z0-9, _ or -, max 32)')
  // DIVE-2233 — `gate_clear_leads`: the agents permitted to exercise the ROUTED lead-clear
  // (DIVE-1182/1243) on an approval/manual/access gate. A LIST, not a scalar, because routing is
  // per-filer: a real org has several managers who each legitimately clear their own reports'
  // gates, and collapsing that to one name would break every branch of the chart but one.
  //
  // This does NOT decide who a gate is ROUTED to — the org chart still does that, and routing is
  // a notification concern. It decides who may CLEAR. That split is the whole fix: an agent that
  // sudo-writes itself into a builder's `reports_to` still receives the ping and still cannot
  // clear, because the name it just gave itself is not in these sealed bytes.
  if (authority.gate_clear_leads != null && !Array.isArray(authority.gate_clear_leads)) throw new Error('authority.gate_clear_leads must be a list of agent names')
  // DIVE-3493 — and it must be a BLOCK sequence, because bash is what enforces it. The
  // node-free reader refuses a flow sequence deliberately, so a document that NAMES holders
  // inline validates, seals, and then denies every name it lists — emitting an audit reason
  // (`no-gate-clear-leads-key`) indistinguishable from "never sealed". Refusing the shape
  // here is what keeps the sealed bytes and the enforced authority the same document.
  // An EMPTY `[]` is exempt on purpose: it grants nobody under either reader, it is the
  // documented safe default, and reddening it would fail a doc that is already correct.
  if (Array.isArray(authority.gate_clear_leads) && authority.gate_clear_leads.yamlFlow && authority.gate_clear_leads.length) {
    throw new Error('authority.gate_clear_leads must be written as a block sequence (one "  - name" per line), not inline [a, b] — the enforcing reader does not accept the inline form and would deny every name listed')
  }
  const gateClearLeads = (authority.gate_clear_leads || []).map(v => {
    if (typeof v !== 'string') throw new Error('authority.gate_clear_leads entries must be strings')
    return v.trim()
  }).filter(v => v !== '')
  for (const n of gateClearLeads) {
    if (!AGENT_NAME_RE.test(n)) throw new Error(`authority.gate_clear_leads entry '${n}' must be a plain agent name (a-z0-9, _ or -, max 32)`)
  }
  if (new Set(gateClearLeads).size !== gateClearLeads.length) throw new Error('authority.gate_clear_leads must not repeat a name')
  return {
    schemaVersion,
    council: { bench: String(council.bench || DEFAULT_CONSTITUTION.council.bench) },
    quorum: globalQuorum,
    thresholds,
    veto: {
      principals,
      principal: principals[0] || '',
      holdSecs: seconds(veto.hold_secs, DEFAULT_CONSTITUTION.veto.holdSecs, 'veto.hold_secs'),
      posthocSecs: seconds(veto.posthoc_secs, DEFAULT_CONSTITUTION.veto.posthocSecs, 'veto.posthoc_secs'),
    },
    hardGates, hardGateRegex,
    ship: raw.ship && typeof raw.ship === 'object' ? raw.ship : {},
    comms: raw.comms && typeof raw.comms === 'object' ? raw.comms : {},
    authority: { engApprovalLead, gateClearLeads },
  }
}

export function loadConstitution(path, readFile = p => fs.readFileSync(p, 'utf8')) {
  // DIVE-1702: every result carries schemaVersion (via the normalized object) plus two digests:
  //   sourceDigest — sha256 of the raw file bytes (cosmetic edits DO churn it; '' when on defaults)
  //   policyDigest — sha256 of the normalized policy (cosmetic edits do NOT churn it)
  // so a caller can tell an effective-policy change from a comment-only edit.
  const withDigests = (normalized, text, extra) => {
    const enforced = { ...normalized, ...extra }
    return { ...enforced, sourceDigest: digestConstitution(text), policyDigest: policyDigest(normalized) }
  }
  if (!path) return withDigests(normalizeConstitution({}), '', { source: 'defaults', path: '', valid: true, error: null })
  try {
    if (!fs.existsSync(path)) return withDigests(normalizeConstitution({}), '', { source: 'defaults', path, valid: true, error: null })
    const text = readFile(path)
    return withDigests(normalizeConstitution(parseConstitutionFrontmatter(text)), text, { source: 'file', path, valid: true, error: null })
  } catch (e) {
    // Fail closed to defaults; the enforced policy IS the defaults, so its digests describe defaults.
    return withDigests(normalizeConstitution({}), '', { source: 'defaults', path, valid: false, error: String(e && e.message || e) })
  }
}
CONSTITUTION_KERNEL_MJS
  cat > "$dir/seal.mjs" <<'CONSTITUTION_KERNEL_SEAL_MJS'
// The constitution SEAL (DIVE-4893). CORE-owned: the solo writer of the council lineage — a
// single-principal genesis record, its canonical preimage (the bytes the root gate-proof rail
// seals), the bench entry it seeds, and the structural chain check `constitution show` reports.
// Moved VERBATIM from the council engine (5dive-ai/5dive fcd81d73 src/council/engine.mjs) when the
// council left core, because `constitution set|edit` direct-seals with no council present. The
// council plugin keeps its own copy of these for multi-seat genesis and motions: the two writers
// append to the same lineage, so their canonical bytes must stay identical —
// tests/constitution_kernel_unit.sh pins them to golden bytes produced by the pre-move engine.

// (DIVE-1563) HUMAN-AS-SEAT SCHEMA. A council seat MAY be a human principal rather than a registry
// agent — marked `{ kind: 'human' }` (or `human: true`) with a chat/principal binding naming which
// Telegram chat the ballot goes to + whose allowFrom the tap is authenticated against (DIVE-1564
// branches on seatIsHuman to emit a ballot instead of an agent-directed ask). PURELY ADDITIVE +
// back-compat: a bare-string or existing {id, agent?, lens?} seat is NEVER human, needs zero
// migration, and serializes byte-identical (canonicalGenesis/canonicalMotion seal only id/chair/lens).
export function seatIsHuman(seat) {
  return !!seat && typeof seat === 'object' && (seat.kind === 'human' || seat.human === true)
}
// The chat/principal a human seat's ballot is delivered to + authenticated against. An explicit
// `chat` (a resolved tg chat/user id) wins; else a resolvable `principal` string (e.g. 'human:main')
// the bash/plugin layer resolves via the DIVE-1546 founder resolver. Returns '' for a non-human OR an
// unbound human seat — dispatch (DIVE-1564) must fail closed on '' and never silently drop the ballot.
export function resolveSeatChat(seat) {
  if (!seatIsHuman(seat)) return ''
  if (seat.chat != null && String(seat.chat).trim()) return String(seat.chat).trim()
  if (seat.principal && typeof seat.principal === 'string' && seat.principal.trim()) return seat.principal.trim()
  return ''
}
// The extra record fields a HUMAN seat carries beyond {id,lens,chair}. Empty {} for an agent seat, so
// spreading it into a seat projection is a no-op for all-agent rosters (seal + JSON both unchanged).
// Applied at every seat->record projection (addSeat + genesis/motion/bench serializers) so a promoted
// human seat keeps its marker across reloads instead of silently reverting to an agent.
export function humanSeatFields(seat) {
  if (!seatIsHuman(seat)) return {}
  const f = { kind: 'human' }
  const chat = resolveSeatChat(seat)
  if (chat) f.chat = chat
  return f
}

// CNCL-11: verify the append-only lineage CHAIN. `entries` is the ordered log — each entry
// { seq, prevDigest, digest }, digest = the record's root seal. Rooted at genesis (prevDigest
// === ''). Tamper-evidence across the WHOLE log, not one record: an edited record changes its
// digest so the NEXT entry's prevDigest link breaks; a dropped or reordered record breaks the
// prevDigest link and/or seq monotonicity. Returns { ok, head, length } or { ok:false, reason, index }.
export function verifyLineageChain(entries) {
  const list = entries || []
  if (!list.length) return { ok: false, reason: 'empty lineage — no genesis root', index: -1 }
  let prev = ''
  for (let i = 0; i < list.length; i++) {
    const e = list[i]
    if (!e || !e.digest) return { ok: false, reason: `record ${i} has no sealed digest`, index: i }
    if (i === 0) {
      if (e.prevDigest) return { ok: false, reason: 'genesis root must have an empty prevDigest', index: 0 }
    } else {
      if (String(e.prevDigest) !== String(prev)) {
        return { ok: false, reason: `broken chain at record ${i} (seq ${e.seq}): prevDigest ${String(e.prevDigest).slice(0, 12)}… != prior digest ${String(prev).slice(0, 12)}… (edited/dropped/reordered record)`, index: i }
      }
      if (Number(e.seq) <= Number(list[i - 1].seq)) {
        return { ok: false, reason: `non-monotonic seq at record ${i} (${list[i - 1].seq} -> ${e.seq}) — a reordered or dropped record`, index: i }
      }
    }
    prev = e.digest
  }
  return { ok: true, head: prev, length: list.length }
}

// Parse a threshold SPEC string: "majority" | "all" | "3" (flat N) | "2/3" (fraction). Returns
// a spec object consumable by resolveThreshold/quorumSize. Fails CLOSED (null) on garbage.
export function parseThresholdSpec(str) {
  const s = String(str == null ? '' : str).trim().toLowerCase()
  if (!s || s === 'majority') return { rule: 'majority' }
  if (s === 'all') return { rule: 'fraction', value: 1 }
  const frac = s.match(/^(\d+)\s*\/\s*(\d+)$/)
  if (frac) { const a = Number(frac[1]), b = Number(frac[2]); if (b > 0 && a > 0 && a <= b) return { rule: 'fraction', value: a / b, label: `${a}/${b}` }; return null }
  if (/^\d+$/.test(s)) { const n = Number(s); return n > 0 ? { rule: 'flat', threshold: n } : null }
  return null
}

// Parse a genesis seat spec: "a:chair,b,c" — a comma list of ids; a token "id:chair" marks the
// chair (princeps senatus, breaks ties, votes last). Exactly one chair is allowed. Anything
// else after the colon is treated as an explicit lens. Returns { seats, chair } or throws.
export function parseGenesisSeats(spec) {
  const parts = String(spec == null ? '' : spec).split(',').map(s => s.trim()).filter(Boolean)
  const seats = []
  let chair = null
  const seen = new Set()
  for (const p of parts) {
    const i = p.indexOf(':')
    const id = (i < 0 ? p : p.slice(0, i)).trim()
    const tag = i < 0 ? '' : p.slice(i + 1).trim()
    if (!id) throw new Error(`empty seat id in "${p}"`)
    if (seen.has(id)) throw new Error(`duplicate seat: ${id}`)
    seen.add(id)
    const isChair = tag.toLowerCase() === 'chair'
    if (isChair) { if (chair) throw new Error(`more than one chair (${chair}, ${id})`); chair = id }
    const lens = (!tag || isChair) ? `${id} — council seat.` : tag
    seats.push({ id, lens, ...(isChair ? { chair: true } : {}) })
  }
  if (!seats.length) throw new Error('genesis needs at least one seat')
  return { seats, chair }
}

// Build the immutable genesis record. `veto` is { principal, resolved } — the resolvable human
// principal (e.g. human:main) plus the tg user_id the bash layer resolved it to; init REFUSES
// an unresolved principal (the record must carry a real, resolvable veto holder). prevDigest
// hash-chains this record to the prior lineage head (empty for the very first seed). No in-engine
// clock — caller supplies stampedAt (byte-reproducible canonical form).
export function buildGenesisRecord({ seats, chair, threshold, veto, prevDigest, stampedAt, forced, seq, constitutionDigest }) {
  if (!Array.isArray(seats) || !seats.length) throw new Error('genesis needs seats')
  if (!veto || !veto.principal) throw new Error('genesis needs a veto principal')
  if (!veto.resolved) throw new Error(`veto principal "${veto.principal}" did not resolve to a real recipient (fail-closed)`)
  return {
    kind: 'genesis',
    version: 1,
    seq: Number(seq) || 0,
    council: 'council',
    seats: seats.map(s => ({ id: s.id, lens: s.lens, ...(s.chair ? { chair: true } : {}), ...humanSeatFields(s) })),
    chair: chair || null,
    threshold: threshold || { rule: 'majority' },
    veto: { principal: veto.principal, resolved: String(veto.resolved) },
    // CNCL-15: the v0 constitution digest, sealed into genesis so `council verify` can detect a
    // later hand-edit of constitution.yaml as drift. '' on a pre-constitution-as-data seed (back-compat).
    constitutionDigest: constitutionDigest ? String(constitutionDigest) : '',
    forced: !!forced,
    prevDigest: prevDigest || '',
    stampedAt: stampedAt || '',
  }
}

// Deterministic, whitespace-normalized preimage of a genesis record — the bytes the ROOT rail
// seals + hash-chains. Same discipline as canonicalTranscript: order-independent seats, the veto
// + prevDigest INSIDE the signed bytes so neither can be quietly altered without failing verify.
export function canonicalGenesis(rec) {
  const norm = (s) => String(s == null ? '' : s).replace(/\s+/g, ' ').trim()
  const L = []
  L.push(`genesis: ${norm(rec.council)} v${Number(rec.version) || 1} seq=${Number(rec.seq) || 0}`)
  L.push(`stampedAt: ${norm(rec.stampedAt)}`)
  L.push(`forced: ${!!rec.forced}`)
  L.push(`prevDigest: ${norm(rec.prevDigest)}`)
  const seats = (rec.seats || []).slice().sort((a, b) => (norm(a.id) < norm(b.id) ? -1 : 1))
  for (const s of seats) L.push(`seat ${norm(s.id)}${s.chair ? ' (chair)' : ''}: ${norm(s.lens)}`)
  L.push(`chair: ${norm(rec.chair)}`)
  const th = rec.threshold || {}
  L.push(`threshold: rule=${norm(th.rule)} value=${th.value != null ? Number(th.value) : ''} flat=${th.threshold != null ? Number(th.threshold) : ''}`)
  L.push(`veto: ${norm(rec.veto && rec.veto.principal)} -> ${norm(rec.veto && rec.veto.resolved)}`)
  // CNCL-15: seal the constitution digest INTO the genesis bytes. Conditional so a pre-CNCL-15
  // record (no digest) canonicalizes exactly as before and its stored seal still re-verifies.
  if (rec.constitutionDigest) L.push(`constitution: ${norm(rec.constitutionDigest)}`)
  return L.join('\n')
}

// The primary council's bench identity, as the council engine's DEFAULT_COUNCIL declares it — only
// the two fields genesisToBench copies, so a solo seal seeds the same bench a council init would.
const COUNCIL_BENCH_DESCRIPTION = 'The 5dive Council — self-governed standing body, one vote each. Seats mutable by quorum vote.'
const COUNCIL_BENCH_MODE = 'deliberate'

// The bench entry a genesis record seeds into the persisted registry — the primary `council`.
export function genesisToBench(rec) {
  return {
    description: COUNCIL_BENCH_DESCRIPTION,
    mode: COUNCIL_BENCH_MODE,
    seats: rec.seats.map(s => ({ id: s.id, lens: s.lens, ...(s.chair ? { chair: true } : {}), ...humanSeatFields(s) })),
    threshold: rec.threshold,
    genesis: true,           // marks this bench as motion-governed (raw add/rm refused)
    seededAt: rec.stampedAt,
  }
}
CONSTITUTION_KERNEL_SEAL_MJS
  cat > "$dir/constitution-cli.mjs" <<'CONSTITUTION_KERNEL_CLI_MJS'
#!/usr/bin/env node
// The constitution kernel's CLI (DIVE-4869, DIVE-4893) — everything `5dive constitution` needs with
// no council present: parse (`constitution`), the show envelope, the v0 render, the structured
// guardrail merge, the solo genesis record (`genesis`) and the structural chain check. The show /
// render / merge / verify-chain bodies moved VERBATIM from council/cli.mjs when the council left
// core; `genesis` is council cli's `init` minus the interactive wizard (bash owns the prompts,
// the sudo gate, the principal resolution, the root seal and the lineage append).
import * as K from './constitution.mjs'
import * as S from './seal.mjs'
import fs from 'node:fs'

const argv = process.argv.slice(2)
const sub = argv[0] || ''
const rest = argv.slice(1)
const flag = (k, d) => {
  const hit = rest.find(a => a === `--${k}` || a.startsWith(`--${k}=`))
  if (hit == null) return d
  return hit.includes('=') ? hit.slice(hit.indexOf('=') + 1) : true
}
const die = (msg, code = 2) => { process.stderr.write(`constitution: ${msg}\n`); process.exit(code) }
// bash passes boolean flags as the STRINGS "0"/"1" — and JS `!"0"` is false, so never test a
// flag's truthiness for these. `--genesis-exists=0` MUST read as false (fail-closed correctness).
const flagBool = (k) => { const v = flag(k); return v === true || v === '1' || v === 'true' }
const out = (obj) => { process.stdout.write(JSON.stringify(obj) + '\n') }
const E = { ...K, ...S }

function cmdConstitution() {
  const p = flag('path')
  const path = p === true || p == null ? '' : String(p)
  out(E.loadConstitution(path))
}

// DIVE-1742: `constitution show --json` READ verb. Composes ONE envelope the dashboard (DIVE-1732)
// and any client consume instead of parsing raw constitution.yaml in-browser (DIVE-1731 no-mutation
// line + DIVE-1700 YAML bug class). The engine loadConstitution is the single shared parser. Digests
// + chain-verify come from the ROOT-sealed lineage via bash (which owns the gate-proof key); this verb
// just reads the lineage FILE for the amendment receipt list + normalizes null semantics. Fail-safe:
// a missing/garbage lineage yields amendments:[] and null digests, never a throw.
function readLineageRecords(lineagePath) {
  if (!lineagePath) return []
  let raw
  try { raw = fs.readFileSync(lineagePath, 'utf8') } catch { return [] }
  const out = []
  for (const line of raw.split(/\r?\n/)) {
    const s = line.trim(); if (!s) continue
    try { out.push(JSON.parse(s)) } catch { /* skip a corrupt line, never abort the read */ }
  }
  return out
}
function cmdConstitutionShow() {
  const strv = (k) => { const v = flag(k); return (v == null || v === true) ? '' : String(v) }
  const path = strv('path')
  const sealed = strv('sealed')
  const live = strv('live')
  const lineagePath = strv('lineage')
  const verifyFile = strv('verify-file')
  const c = E.loadConstitution(path)
  // Per-class hard_gates: raw effective ERE strings + a default-vs-custom source flag (custom ==
  // differs from the shipped default) so the dashboard can render "default" vs "customized".
  const hard_gates = { ...c.hardGates }
  const hard_gates_source = {}
  for (const k of Object.keys(hard_gates)) {
    hard_gates_source[k] = (hard_gates[k] === E.DEFAULT_HARD_GATE_CLASSES[k]) ? 'default' : 'custom'
  }
  // Amendment receipts: lineage records that carry a non-empty constitutionDigest (genesis-with-
  // constitution + every amend). Newest last (lineage is append-ordered). Fields per DIVE-1742 lock.
  const amendments = readLineageRecords(lineagePath)
    .map(w => ({ w, r: (w && w.record) || {} }))
    .filter(({ r }) => r && typeof r.constitutionDigest === 'string' && r.constitutionDigest !== '')
    .map(({ w, r }) => ({
      seq: Number.isInteger(r.seq) ? r.seq : (Number.isInteger(w.seq) ? w.seq : null),
      recordDigest: (w && typeof w.digest === 'string') ? w.digest : null,
      constitutionDigest: r.constitutionDigest,
      at: r.stampedAt || null,
      motion: (r.motion && r.motion.kind) || r.kind || null,
      outcome: r.outcome || null,
      by: r.by || (r.veto && r.veto.principal) || null,
    }))
  // verify passthrough (chain re-seal is root-only, computed by bash `council verify`); null if absent.
  let verify = null
  if (verifyFile) { try { verify = JSON.parse(fs.readFileSync(verifyFile, 'utf8')) } catch { verify = null } }
  const drift = E.constitutionDriftCheck({ sealedDigest: sealed, liveDigest: live })
  // genesisExists: is a council seated at all? This is the robust edit-vs-readonly signal (and the
  // DIVE-1743 write-path branch): a box can have a council genesis but an as-yet-UNSEALED constitution
  // (sealedDigest=null), where edits must still route through `council amend`, not a solo write. Truly
  // solo (editable) == no genesis AND no seal. bash passes --genesis-exists (it owns the genesis path).
  const genesisExists = String(flag('genesis-exists') || '') === '1'
  out({
    path: c.path, source: c.source, valid: c.valid, error: c.error,
    hard_gates, hard_gates_source, hard_gates_defaults: E.DEFAULT_HARD_GATE_CLASSES,
    hard_gate_regex: c.hardGateRegex,
    thresholds: c.thresholds, quorum: c.quorum,
    veto: c.veto, ship: c.ship, comms: c.comms, council: c.council,
    // null (NOT '') when no council has sealed. Pair with genesisExists for the edit-vs-readonly switch:
    // editable only when !genesisExists && sealedDigest==null (truly solo); else route via council amend.
    sealedDigest: sealed || null,
    liveDigest: live || null,
    genesisExists,
    drifted: !!drift.drifted, driftReason: drift.reason || null,
    verify,
    amendments,
  })
}

// The bench registry the genesis seeds. Same read contract as council cli's loadRegistry for the
// cases a solo seal meets (absent / empty -> {}; garbage -> refuse), without the DIVE-3729 repair.
function loadRegistry(p) {
  if (!p) return {}
  let raw
  try { raw = fs.readFileSync(p, 'utf-8') } catch (e) {
    if (e && e.code === 'ENOENT') return {}
    die(`cannot read the bench registry ${p}: ${(e && e.code) || 'unknown error'} — this is a READ FAILURE, not an empty registry`)
  }
  if (!raw.trim()) return {}
  try { return JSON.parse(raw) } catch (e) { die(`bench registry ${p} is not valid JSON (${e.message}) — refusing to run as if it were empty`) }
}
function saveRegistry(p, reg) {
  if (!p) die('bench mutation needs --registry=<path>')
  // DIVE-3729: `mode` applies only when the file is CREATED (and is still masked by the umask), so
  // this cannot downgrade an existing registry — it stops a first write under a tight umask from
  // leaving the store root-only, which is the same lockout the shell-side rewrite caused.
  const existed = fs.existsSync(p)
  fs.writeFileSync(p, JSON.stringify(reg, null, 2) + '\n', { mode: 0o644 })
  if (!existed) { try { fs.chmodSync(p, 0o644) } catch { /* best effort; the write itself succeeded */ } }
}

// CNCL-8: council init (human-seeded genesis roster). Seeds the primary `council` bench ONCE from
// a human-supplied roster + veto principal. bash owns the sudo gate, veto-principal resolution,
// the ROOT seal, and the hash-chained lineage write. cli validates the roster, enforces one-time
// (fail-closed unless --force), and emits the record for bash to seal — an agent can never call
// this to bootstrap its own council because the write path (COUNCIL_DIR) is root-owned.
function cmdGenesis() {
  const registryPath = flag('registry')
  const genesisExists = flagBool('genesis-exists')
  const forced = !!flag('force')
  if (genesisExists && !forced) {
    die('council is already initialized (one-time). Re-seed with --force (the re-seed is logged in the lineage).', 5)
  }
  let parsed
  try { parsed = E.parseGenesisSeats(flag('seats')) }
  catch (e) { die(`bad --seats: ${String(e && e.message || e)}`) }
  const threshold = E.parseThresholdSpec(flag('threshold') || 'majority')
  if (!threshold) die(`bad --threshold (use: majority | all | <N> | <a>/<b>, e.g. 2/3)`)
  const principal = flag('veto')
  if (!principal || principal === true) die('init needs --veto=<principal> (a resolvable human, e.g. human:main)')
  const resolved = flag('veto-resolved')   // bash resolves the principal -> tg user_id
  if (!resolved || resolved === true) die(`veto principal "${principal}" did not resolve — use human:<agent> (a paired agent) or tg:<user_id>`, 6)
  let rec
  try {
    rec = E.buildGenesisRecord({
      seats: parsed.seats, chair: parsed.chair, threshold,
      veto: { principal: String(principal), resolved: String(resolved) },
      prevDigest: flag('prev-digest') || '', stampedAt: flag('stamped-at') || '',
      forced, seq: Number(flag('seq')) || 0,
      // CNCL-15: bash sha256sum's the seeded v0 constitution.yaml and passes it here so the digest is
      // sealed into the genesis bytes (drift baseline). '' if the caller seeded no constitution.
      constitutionDigest: flag('constitution-digest') === true ? '' : (flag('constitution-digest') || ''),
    })
  } catch (e) { die(String(e && e.message || e)) }
  // Seed / re-seat the primary council bench in the persisted registry (bench edits on it are
  // refused elsewhere — init and, later, motions are the ONLY writers).
  const reg = loadRegistry(registryPath)
  reg.council = E.genesisToBench(rec)
  saveRegistry(registryPath, reg)
  out({ genesis: rec, canonical: E.canonicalGenesis(rec), bench: 'council', seats: rec.seats.map(s => s.id), chair: rec.chair, constitutionDigest: rec.constitutionDigest })
}

// CNCL-15: constitution v0 render + drift check + amend motion. `constitution-render` prints the
// v0 constitution.yaml `council init` seeds when none exists. bash writes it, then sha256sum's the on-disk
// bytes for the sealed digest — one digest realm across seed/amend/verify.
function cmdConstitutionRender() { process.stdout.write(E.renderConstitutionV0()) }

// DIVE-1751 — browser-callable STRUCTURED-FIELD write. `constitution-merge --path=<current>` reads a
// JSON patch of the SOLO-editable guardrail fields from STDIN, merges it into the CURRENT constitution,
// and re-emits a valid v0 constitution.yaml on stdout. The bash layer then flows it through the EXACT
// SAME validate + seat-count route + seal path as `set --file=`. This keeps serialize+seal colocated in
// the CLI — the browser NEVER authors governance YAML (DIVE-1700 fraction-bug class). The patch is
// STRICTLY whitelisted to hard_gates/ship/comms; the governance keys (council/quorum/veto/thresholds)
// are unreachable here BY DESIGN (they change only through a `council amend` constitutional motion). The
// emitted bytes are re-validated through the SAME normalizer before we hand them back (one parser,
// fail-closed) — a structured write can never produce a constitution that would not parse.
const MERGE_TOP = new Set(['hard_gates', 'ship', 'comms'])
const MERGE_SHIP_KEYS = new Set(['require_ci'])
const MERGE_COMMS_KEYS = new Set(['public_requires_human'])
// Serialize a raw-parsed constitution node back to v0 frontmatter. Single-quote every string so
// regex backslashes + special chars survive the frontmatter parser byte-for-byte (it does no escape
// processing); numbers/booleans/null stay bare so they re-parse as themselves. Inline arrays for lists.
function serializeConstitutionScalar(v) {
  if (v === null) return 'null'
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  if (typeof v === 'number' && Number.isFinite(v)) return String(v)
  if (Array.isArray(v)) return '[' + v.map(serializeConstitutionScalar).join(', ') + ']'
  return `'${String(v).replace(/'/g, "''")}'`
}
// DIVE-3493 — a non-empty list is re-emitted as a BLOCK sequence, never inline. This verb
// re-serializes the WHOLE document (it only ever CHANGES hard_gates/ship/comms, but it
// rewrites every key it read), so an inline emitter here would silently convert a sealed
// `authority.gate_clear_leads` into the one shape the enforcing reader in src/task/need.sh
// treats as absent — revoking the allowlist as a side effect of a guardrail edit, and now
// also failing this verb's own re-validation. Empty stays `[]`: block form cannot say it.
function serializeConstitutionList(k, v, pad) {
  if (!v.length) return `${pad}${k}: []\n`
  return `${pad}${k}:\n` + v.map(x => `${pad}  - ${serializeConstitutionScalar(x)}\n`).join('')
}
function serializeConstitutionNode(obj, indent) {
  const pad = ' '.repeat(indent)
  let out = ''
  for (const [k, v] of Object.entries(obj)) {
    if (Array.isArray(v)) out += serializeConstitutionList(k, v, pad)
    else if (v && typeof v === 'object') {
      const inner = serializeConstitutionNode(v, indent + 2)
      out += inner ? `${pad}${k}:\n${inner}` : `${pad}${k}:\n`
    } else out += `${pad}${k}: ${serializeConstitutionScalar(v)}\n`
  }
  return out
}
function serializeConstitution(raw) {
  // Canonical section order; only sections present in the merged doc are emitted. Governance keys
  // (council/quorum/veto/thresholds) are re-emitted verbatim from the current doc — never touched here.
  const order = ['hard_gates', 'ship', 'comms', 'council', 'quorum', 'veto', 'thresholds']
  const keys = [...order.filter(k => Object.hasOwn(raw, k)), ...Object.keys(raw).filter(k => !order.includes(k))]
  let out = '# 5dive company constitution (v0) — machine-enforced guardrails.\n'
    + '# Written by `5dive constitution set --json` (structured guardrail write, DIVE-1751). The AUTHORITY\n'
    + '# is the sealed digest: after this file is sealed, enforcement fails CLOSED on any drift from it.\n'
  for (const k of keys) {
    const v = raw[k]
    if (Array.isArray(v)) out += serializeConstitutionList(k, v, '')
    else if (v && typeof v === 'object') {
      const inner = serializeConstitutionNode(v, 2)
      out += inner ? `${k}:\n${inner}` : `${k}:\n`
    } else out += `${k}: ${serializeConstitutionScalar(v)}\n`
  }
  return out
}
function cmdConstitutionMerge() {
  const pf = flag('path')
  const path = (pf == null || pf === true) ? '' : String(pf)
  // Base = the CURRENT constitution's RAW frontmatter (preserve the exact governance keys the user /
  // council authored — we touch ONLY the three guardrail sections). No file yet -> base on the v0
  // default projection so a first structured write still yields a complete, valid file.
  let baseText
  if (path && fs.existsSync(path)) { try { baseText = fs.readFileSync(path, 'utf8') } catch (e) { die(`constitution-merge: cannot read the current constitution ${path} (${String(e && e.message || e)})`, 4) } }
  else baseText = E.renderConstitutionV0()
  let raw
  try { raw = E.parseConstitutionFrontmatter(baseText) }
  catch (e) { die(`constitution-merge: current constitution does not parse (${String(e && e.message || e)}) — refusing to write onto it`, 4) }

  // Read + STRICTLY whitelist the STDIN patch. Anything outside hard_gates/ship/comms is refused.
  let patch
  try { patch = JSON.parse(fs.readFileSync(0, 'utf8') || '{}') }
  catch (e) { die(`constitution-merge: invalid JSON on stdin (${String(e && e.message || e)})`, 2) }
  if (!patch || typeof patch !== 'object' || Array.isArray(patch)) die('constitution-merge: stdin must be a JSON object of structured fields', 2)
  const badTop = Object.keys(patch).filter(k => !MERGE_TOP.has(k))
  if (badTop.length) die(`constitution-merge: not settable here: ${badTop.join(', ')} — only hard_gates/ship/comms (governance: council amend)`, 2)

  if (Object.hasOwn(patch, 'hard_gates')) {
    const hg = patch.hard_gates
    if (!hg || typeof hg !== 'object' || Array.isArray(hg)) die('constitution-merge: hard_gates must be an object of class -> regex string', 2)
    const cur = (raw.hard_gates && typeof raw.hard_gates === 'object' && !Array.isArray(raw.hard_gates)) ? raw.hard_gates : {}
    const allowed = new Set([...Object.keys(cur), ...Object.keys(E.DEFAULT_HARD_GATE_CLASSES)])
    for (const [k, val] of Object.entries(hg)) {
      if (!allowed.has(k)) die(`constitution-merge: unknown hard_gates class '${k}' (editable classes: ${[...allowed].sort().join(', ')})`, 2)
      if (typeof val !== 'string' || !val.trim()) die(`constitution-merge: hard_gates.${k} must be a non-empty regex string`, 2)
    }
    raw.hard_gates = { ...cur, ...hg }
  }
  for (const [sec, keys] of [['ship', MERGE_SHIP_KEYS], ['comms', MERGE_COMMS_KEYS]]) {
    if (!Object.hasOwn(patch, sec)) continue
    const p = patch[sec]
    if (!p || typeof p !== 'object' || Array.isArray(p)) die(`constitution-merge: ${sec} must be an object`, 2)
    const cur = (raw[sec] && typeof raw[sec] === 'object' && !Array.isArray(raw[sec])) ? raw[sec] : {}
    for (const [k, val] of Object.entries(p)) {
      if (!keys.has(k)) die(`constitution-merge: unknown ${sec}.${k} (settable: ${[...keys].join(', ')})`, 2)
      if (typeof val !== 'boolean') die(`constitution-merge: ${sec}.${k} must be true or false`, 2)
    }
    raw[sec] = { ...cur, ...p }
  }

  // Re-serialize + re-validate through the SAME normalizer BEFORE emitting (fail-closed): a structured
  // write can never produce a constitution that would not parse under the one shared parser.
  const text = serializeConstitution(raw)
  try { E.normalizeConstitution(E.parseConstitutionFrontmatter(text)) }
  catch (e) { die(`constitution-merge: merged constitution failed validation (${String(e && e.message || e)}) — refusing to emit`, 4) }
  process.stdout.write(text)
}

// `drift-check` — pure comparison of the sealed digest vs the live-file digest (both computed by
// bash with sha256sum). Exits non-zero when drifted so callers can fail closed on the exit code.
function cmdDriftCheck() {
  const sealed = flag('sealed') === true || flag('sealed') == null ? '' : String(flag('sealed'))
  const live = flag('live') === true || flag('live') == null ? '' : String(flag('live'))
  const res = E.constitutionDriftCheck({ sealedDigest: sealed, liveDigest: live })
  out(res)
  process.exit(res.drifted ? 7 : 0)
}

function readJsonFlag(name, { optional = false } = {}) {
  const v = flag(name)
  if (!v || v === true) { if (optional) return null; die(`needs --${name}=<json or @file>`) }
  try { return JSON.parse(String(v).startsWith('@') ? fs.readFileSync(String(v).slice(1), 'utf-8') : v) }
  catch (e) { die(`bad --${name} json: ${String(e && e.message || e)}`) }
}

// council verify — the structural chain check (bash re-seals each record's canonical separately;
// both must be green). Detects an edited/dropped/reordered receipt across the WHOLE append-only log.
function cmdVerifyChain() {
  const entries = readJsonFlag('entries')
  const res = E.verifyLineageChain(entries)
  out(res)
  process.exit(res.ok ? 0 : 5)
}

const SUBS = {
  constitution: cmdConstitution,
  'constitution-show': cmdConstitutionShow,
  'constitution-render': cmdConstitutionRender,
  'constitution-merge': cmdConstitutionMerge,
  'drift-check': cmdDriftCheck,
  genesis: cmdGenesis,
  'verify-chain': cmdVerifyChain,
}
if (Object.hasOwn(SUBS, sub)) SUBS[sub]()
else die(`unknown subcommand: ${sub} (want: ${Object.keys(SUBS).join(' | ')})`)
CONSTITUTION_KERNEL_CLI_MJS
}

# Parse the machine-enforced constitution through the one loader. A function (not a source-time
# global) so test/runtime STATE_DIR overrides resolve correctly.
_constitution_json() {
  ensure_node_on_path || return 1
  local dir rc=0
  dir="$(mktemp -d -t 5dive-constitution.XXXXXX)" || return 1
  _constitution_write_runtime "$dir"
  node "$dir/constitution-cli.mjs" constitution --path="$(_constitution_path)" || rc=$?
  rm -rf "$dir"
  return "$rc"
}

_constitution_hard_gate_rx() {
  _constitution_json | jq -r '.hardGateRegex'
}

# CNCL-15 — constitution integrity. The AUTHORITY is the digest sealed in the newest genesis/
# amendment lineage record, NOT the on-disk constitution.yaml (the file is forgeable, the chain is not).
# Newest record carrying a non-empty constitutionDigest wins (amend > genesis).
_constitution_sealed_digest() {
  [[ -f "$COUNCIL_LINEAGE" ]] || return 0
  jq -r 'select((.record.constitutionDigest // "") != "") | .record.constitutionDigest' "$COUNCIL_LINEAGE" 2>/dev/null | tail -n1
}
# sha256 of the on-disk constitution.yaml ('' if missing) — the live side of the drift comparison.
_constitution_live_digest() {
  local p; p="$(_constitution_path)"
  [[ -f "$p" ]] || return 0
  sha256sum < "$p" 2>/dev/null | awk '{print $1}'
}

# DIVE-1695 — node-free drift verdict for the gate-floor hot path. Returns 0 (DRIFTED, fail closed)
# / 1 (in sync, or no seal to enforce). No sealed digest -> 1; sealed but the live file is missing or
# its digest differs -> 0 (an unsanctioned edit/drop must NOT be enforced).
_constitution_drifted() {
  local sealed live
  sealed="$(_constitution_sealed_digest 2>/dev/null || true)"
  [[ -z "$sealed" ]] && return 1          # no sealed constitution -> nothing to drift from
  live="$(_constitution_live_digest 2>/dev/null || true)"
  [[ -z "$live" ]] && return 0            # sealed but file gone -> drift (fail closed)
  [[ "$sealed" != "$live" ]] && return 0  # sealed but file edited -> drift (fail closed)
  return 1                                 # live matches the sealed digest
}

# ==================== the solo seal (DIVE-4893) ====================
# Moved from the council engine when it left core: `constitution set|edit` on a box with no council
# (or a single-principal one) seals the constitution itself — a single-principal genesis, root-sealed
# on the gate-proof rail and hash-chained into the lineage. Multi-seat governance (convene, motions,
# amendments) is the council plugin's; core never writes a multi-seat record.

# Root-seal stdin on the gate-proof rail: in-process as root, else through `sudo -n`. Empty output
# on no key / no root — every caller fails closed on empty.
_constitution_seal_stdin() {
  if [[ "$(id -u)" -eq 0 ]]; then cmd_gate_proof sign 2>/dev/null; else sudo -n 5dive gate-proof sign 2>/dev/null; fi
}

# A veto principal -> the Telegram user id it delivers to ('' when it does not resolve).
#   tg:<digits> | <digits>  -> the id;   human:<agent> -> that agent's paired human (allowFrom[0]).
_constitution_resolve_principal() {
  local p="$1"
  case "$p" in
    tg:*) local id="${p#tg:}"; [[ "$id" =~ ^[0-9]+$ ]] && printf '%s' "$id"; return 0 ;;
    human:*)
      local name="${p#human:}"
      [[ -n "$name" ]] || return 0
      _task_agent_channel "$name" >/dev/null 2>&1 || return 0
      [[ -n "${TASK_CH_ACCESS:-}" && -r "$TASK_CH_ACCESS" ]] || return 0
      jq -r '(.allowFrom // [])[0] // empty' "$TASK_CH_ACCESS" 2>/dev/null
      return 0 ;;
    *) [[ "$p" =~ ^[0-9]+$ ]] && printf '%s' "$p"; return 0 ;;
  esac
}

# _constitution_solo_seal <runtime-dir> --seats=<id:chair> --veto=<principal> [--force]
# Seal the on-disk constitution.yaml (seeding the v0 default when there is none) into a
# single-principal genesis. The caller has already materialized the runtime into <runtime-dir>
# and checked COUNCIL_DIR is writable. Byte-for-byte the record the council's `init` wrote.
_constitution_solo_seal() {
  local dir="$1"; shift
  mkdir -p "$COUNCIL_DIR" 2>/dev/null || true
  [[ -w "$COUNCIL_DIR" ]] || fail "$E_PERMISSION" "the constitution seal writes root-owned governance files — run it under sudo"
  local principal="" a
  for a in "$@"; do case "$a" in --veto=*) principal="${a#--veto=}" ;; esac; done
  [[ -n "$principal" ]] || fail "$E_USAGE" "the solo seal needs --veto=<principal> (e.g. human:main)"
  local resolved; resolved="$(_constitution_resolve_principal "$principal")"
  [[ -n "$resolved" ]] || fail "$E_USAGE" "veto principal '$principal' did not resolve — use human:<agent> (a paired agent) or tg:<user_id>"
  # DIVE-2278: a raw user id is copied verbatim into the SEALED, immutable, publishable bytes.
  if [[ "$principal" =~ ^(tg:)?[0-9]+$ ]]; then
    printf 'warn: --principal=%s puts a raw user id inside the SEALED genesis bytes, which are\n' "$principal" >&2
    printf '      immutable and publishable. Prefer --principal=human:<agent> — same recipient, name in the seal.\n' >&2
  fi

  local genesis_exists=0; [[ -f "$COUNCIL_GENESIS" ]] && genesis_exists=1
  local prev_digest="" seq=0
  if [[ -f "$COUNCIL_LINEAGE" ]]; then
    prev_digest="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.digest // ""' 2>/dev/null)"
    local last_seq; last_seq="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.seq // -1' 2>/dev/null)"
    [[ "$last_seq" =~ ^[0-9]+$ ]] && seq=$((last_seq+1))
  fi
  local stamped; stamped="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  # CNCL-15: seed the v0 constitution if none exists, then seal its digest INTO the genesis record so
  # a later hand-edit is detectable as drift. `sha256sum` is the one digest realm.
  local cpath; cpath="$(_constitution_path)"
  if [[ ! -f "$cpath" ]]; then
    if ( umask 022; node "$dir/constitution-cli.mjs" constitution-render > "$cpath" ); then
      echo "constitution: seeded v0 -> $cpath" >&2
    else
      rm -f "$cpath" 2>/dev/null || true
      fail "$E_GENERIC" "could not seed the v0 constitution at $cpath — genesis NOT written"
    fi
  fi
  node "$dir/constitution-cli.mjs" constitution --path="$cpath" | jq -e '.valid == true' >/dev/null 2>&1 \
    || fail "$E_VALIDATION" "the constitution at $cpath is not valid — refusing to seal a broken governance file into genesis (fail-closed)"
  local constitution_digest; constitution_digest="$(sha256sum < "$cpath" 2>/dev/null | awk '{print $1}')"
  [[ -n "$constitution_digest" ]] || fail "$E_GENERIC" "could not digest the constitution at $cpath"

  local raw
  raw="$(node "$dir/constitution-cli.mjs" genesis "$@" \
    --registry="$COUNCIL_REGISTRY" --veto-resolved="$resolved" \
    --genesis-exists="$genesis_exists" --prev-digest="$prev_digest" --seq="$seq" \
    --constitution-digest="$constitution_digest" \
    --stamped-at="$stamped")" || return $?

  # Seal the canonical genesis bytes on the ROOT rail, then hash-chain them into the lineage.
  local canonical digest=""
  canonical="$(printf '%s' "$raw" | jq -r '.canonical // empty')"
  [[ -n "$canonical" ]] || fail "$E_GENERIC" "the genesis writer produced no canonical record"
  digest="$(printf '%s' "$canonical" | _constitution_seal_stdin)" || digest=""
  [[ -n "$digest" ]] || fail "$E_GENERIC" "could not seal the genesis record on the gate-proof rail (need root + an enforce key) — genesis NOT written"

  printf '%s' "$raw" | jq --arg d "$digest" '.genesis + {sealedDigest:$d}' > "$COUNCIL_GENESIS"
  printf '%s' "$raw" | jq -c --arg d "$digest" --arg p "$prev_digest" \
    '{seq: .genesis.seq, kind: "genesis", stampedAt: .genesis.stampedAt, digest: $d, prevDigest: $p, canonical: .canonical, record: .genesis}' \
    >> "$COUNCIL_LINEAGE"

  if (( JSON_MODE )); then
    printf '%s' "$raw" | jq --arg d "$digest" '{ok:true, data: (. + {sealedDigest:$d})}'
  else
    echo "constitution: sealed (seq $seq)"
    echo "const:   ${constitution_digest:0:16}… -> $cpath"
    echo "genesis: sealed (${digest:0:16}…) + hash-chained into lineage"
  fi
  return 0
}

# _constitution_verify <runtime-dir> — the lineage verdict `constitution show` reports (and the
# council plugin's `council verify` reaches): the structural chain, every record re-sealing to its
# stored digest on the root rail, and the live constitution matching its sealed digest. Prints the
# {verified, records, chain, chainOk, resealOk, resealBad, constitutionOk, constitution} object;
# returns non-zero on any failure. Read-only.
_constitution_verify() {
  local dir="$1"
  [[ -f "$COUNCIL_LINEAGE" ]] || return 1
  local entries chain_res chain_ok
  entries="$(jq -s -c '[.[] | {seq, prevDigest: (.prevDigest // ""), digest}]' "$COUNCIL_LINEAGE")"
  chain_res="$(node "$dir/constitution-cli.mjs" verify-chain --entries="$entries")"; chain_ok=$?
  local reseal_ok=1 line canonical stored computed n=0 bad=""
  while IFS= read -r line; do
    [[ -n "$line" ]] || continue; n=$((n+1))
    stored="$(printf '%s' "$line" | jq -r '.digest')"
    canonical="$(printf '%s' "$line" | jq -r '.canonical')"
    computed="$(printf '%s' "$canonical" | _constitution_seal_stdin)"
    if [[ -z "$computed" ]]; then reseal_ok=0; bad="seq $(printf '%s' "$line" | jq -r '.seq') (no gate-proof key / not root)"; break
    elif [[ "$computed" != "$stored" ]]; then reseal_ok=0; bad="seq $(printf '%s' "$line" | jq -r '.seq') (canonical does not re-seal to its digest — TAMPERED)"; break; fi
  done < "$COUNCIL_LINEAGE"
  local drift_ok=1 drift_json drift_reason
  drift_json="$(node "$dir/constitution-cli.mjs" drift-check --sealed="$(_constitution_sealed_digest)" --live="$(_constitution_live_digest)" 2>/dev/null)" || drift_ok=0
  drift_reason="$(printf '%s' "$drift_json" | jq -r '.reason // "drift"' 2>/dev/null)"
  local all_ok=1
  [[ "$chain_ok" -eq 0 && "$reseal_ok" -eq 1 && "$drift_ok" -eq 1 ]] || all_ok=0
  jq -nc --argjson chain "${chain_res:-null}" --argjson chainOk "$([[ $chain_ok -eq 0 ]] && echo true || echo false)" \
    --argjson resealOk "$([[ $reseal_ok -eq 1 ]] && echo true || echo false)" --arg bad "$bad" \
    --argjson driftOk "$([[ $drift_ok -eq 1 ]] && echo true || echo false)" --arg driftReason "$drift_reason" \
    --argjson n "$n" --argjson allOk "$([[ $all_ok -eq 1 ]] && echo true || echo false)" \
    '{verified:$allOk, records:$n, chain:$chain, chainOk:$chainOk, resealOk:$resealOk, resealBad:$bad, constitutionOk:$driftOk, constitution:$driftReason, receipt:"skipped"}'
  (( all_ok ))
}
