# ==================== constitution kernel (DIVE-4869, DIVE-4893) ====================
# CORE-owned constitution: where constitution.yaml lives, the one parser
# (src/constitution/constitution.mjs, embedded below), the SEAL — the newest constitutionDigest in
# the council lineage, read as DATA — and, since the council left core (DIVE-4893), the SOLO writer
# of that seal. `task need`'s tier-2 floor and its lead-clear authority call the read half on every
# box; `constitution set|edit` calls the write half with no council installed.
#
# Decision (DIVE-4869 body): the seal stays the council lineage file at its existing path — core
# needs no council code to trust it, and no box needs a migration. The council PLUGIN
# (5dive-ai/5dive-council) is the only writer of MULTI-seat records; core writes only a
# single-principal genesis (a solo direct-seal). Both append to the same hash chain, which is why
# src/constitution/seal.mjs is a verbatim copy of the council's genesis writer and why
# tests/constitution_kernel_unit.sh pins its canonical bytes to the pre-move engine's.
#
# This file is GENERATED by src/constitution/gen_kernel.mjs from this template plus
# src/constitution/{constitution,seal,cli}.mjs. Edit those and re-run the generator, never the output.

COUNCIL_DIR="${STATE_DIR}/council"
COUNCIL_GENESIS="${COUNCIL_DIR}/genesis.json"
COUNCIL_REGISTRY="${COUNCIL_DIR}/benches.json"
COUNCIL_LINEAGE="${STATE_DIR}/council/lineage.jsonl"

_constitution_path() {
  # An explicit override wins verbatim — no legacy migration on a caller-chosen path.
  if [[ -n "${FIVEDIVE_CONSTITUTION_FILE:-}" ]]; then
    printf '%s' "$FIVEDIVE_CONSTITUTION_FILE"; return
  fi
  local canonical="${STATE_DIR}/constitution.yaml" legacy="${STATE_DIR}/5dive.md"
  # DIVE-1686 belt-and-suspenders for the DIVE-1676 rename: a box ratified BEFORE
  # the rename holds its constitution at the legacy 5dive.md. Do a one-time rename to
  # the canonical name so post-rename builds keep reading it — a rename is byte-preserving,
  # so the sealed-digest drift check still matches. If the rename can't happen (e.g. a
  # non-root reader on root-owned STATE_DIR), fall back to reading the legacy file IN PLACE
  # this call, so the loader NEVER silently reverts to built-in defaults.
  if [[ ! -e "$canonical" && -f "$legacy" ]]; then
    if mv -n "$legacy" "$canonical" 2>/dev/null && [[ -e "$canonical" ]]; then
      echo "constitution: migrated legacy $legacy -> $canonical (DIVE-1676 rename)" >&2
    else
      printf '%s' "$legacy"; return
    fi
  fi
  printf '%s' "$canonical"
}

_constitution_write_runtime() {
  local dir="$1"
  cat > "$dir/constitution.mjs" <<'CONSTITUTION_KERNEL_MJS'
__CONSTITUTION_MJS__
CONSTITUTION_KERNEL_MJS
  cat > "$dir/seal.mjs" <<'CONSTITUTION_KERNEL_SEAL_MJS'
__CONSTITUTION_SEAL_MJS__
CONSTITUTION_KERNEL_SEAL_MJS
  cat > "$dir/constitution-cli.mjs" <<'CONSTITUTION_KERNEL_CLI_MJS'
__CONSTITUTION_CLI_MJS__
CONSTITUTION_KERNEL_CLI_MJS
}

# Parse the machine-enforced constitution through the one loader. A function (not a source-time
# global) so test/runtime STATE_DIR overrides resolve correctly.
_constitution_json() {
  ensure_node_on_path || return 1
  local dir rc=0
  dir="$(mktemp -d -t 5dive-constitution.XXXXXX)" || return 1
  _constitution_write_runtime "$dir"
  node "$dir/constitution-cli.mjs" constitution --path="$(_constitution_path)" || rc=$?
  rm -rf "$dir"
  return "$rc"
}

_constitution_hard_gate_rx() {
  _constitution_json | jq -r '.hardGateRegex'
}

# CNCL-15 — constitution integrity. The AUTHORITY is the digest sealed in the newest genesis/
# amendment lineage record, NOT the on-disk constitution.yaml (the file is forgeable, the chain is not).
# Newest record carrying a non-empty constitutionDigest wins (amend > genesis).
_constitution_sealed_digest() {
  [[ -f "$COUNCIL_LINEAGE" ]] || return 0
  jq -r 'select((.record.constitutionDigest // "") != "") | .record.constitutionDigest' "$COUNCIL_LINEAGE" 2>/dev/null | tail -n1
}
# sha256 of the on-disk constitution.yaml ('' if missing) — the live side of the drift comparison.
_constitution_live_digest() {
  local p; p="$(_constitution_path)"
  [[ -f "$p" ]] || return 0
  sha256sum < "$p" 2>/dev/null | awk '{print $1}'
}

# DIVE-1695 — node-free drift verdict for the gate-floor hot path. Returns 0 (DRIFTED, fail closed)
# / 1 (in sync, or no seal to enforce). No sealed digest -> 1; sealed but the live file is missing or
# its digest differs -> 0 (an unsanctioned edit/drop must NOT be enforced).
_constitution_drifted() {
  local sealed live
  sealed="$(_constitution_sealed_digest 2>/dev/null || true)"
  [[ -z "$sealed" ]] && return 1          # no sealed constitution -> nothing to drift from
  live="$(_constitution_live_digest 2>/dev/null || true)"
  [[ -z "$live" ]] && return 0            # sealed but file gone -> drift (fail closed)
  [[ "$sealed" != "$live" ]] && return 0  # sealed but file edited -> drift (fail closed)
  return 1                                 # live matches the sealed digest
}

# ==================== the solo seal (DIVE-4893) ====================
# Moved from the council engine when it left core: `constitution set|edit` on a box with no council
# (or a single-principal one) seals the constitution itself — a single-principal genesis, root-sealed
# on the gate-proof rail and hash-chained into the lineage. Multi-seat governance (convene, motions,
# amendments) is the council plugin's; core never writes a multi-seat record.

# Root-seal stdin on the gate-proof rail: in-process as root, else through `sudo -n`. Empty output
# on no key / no root — every caller fails closed on empty.
_constitution_seal_stdin() {
  if [[ "$(id -u)" -eq 0 ]]; then cmd_gate_proof sign 2>/dev/null; else sudo -n 5dive gate-proof sign 2>/dev/null; fi
}

# A veto principal -> the Telegram user id it delivers to ('' when it does not resolve).
#   tg:<digits> | <digits>  -> the id;   human:<agent> -> that agent's paired human (allowFrom[0]).
_constitution_resolve_principal() {
  local p="$1"
  case "$p" in
    tg:*) local id="${p#tg:}"; [[ "$id" =~ ^[0-9]+$ ]] && printf '%s' "$id"; return 0 ;;
    human:*)
      local name="${p#human:}"
      [[ -n "$name" ]] || return 0
      _task_agent_channel "$name" >/dev/null 2>&1 || return 0
      [[ -n "${TASK_CH_ACCESS:-}" && -r "$TASK_CH_ACCESS" ]] || return 0
      jq -r '(.allowFrom // [])[0] // empty' "$TASK_CH_ACCESS" 2>/dev/null
      return 0 ;;
    *) [[ "$p" =~ ^[0-9]+$ ]] && printf '%s' "$p"; return 0 ;;
  esac
}

# _constitution_solo_seal <runtime-dir> --seats=<id:chair> --veto=<principal> [--force]
# Seal the on-disk constitution.yaml (seeding the v0 default when there is none) into a
# single-principal genesis. The caller has already materialized the runtime into <runtime-dir>
# and checked COUNCIL_DIR is writable. Byte-for-byte the record the council's `init` wrote.
_constitution_solo_seal() {
  local dir="$1"; shift
  mkdir -p "$COUNCIL_DIR" 2>/dev/null || true
  [[ -w "$COUNCIL_DIR" ]] || fail "$E_PERMISSION" "the constitution seal writes root-owned governance files — run it under sudo"
  local principal="" a
  for a in "$@"; do case "$a" in --veto=*) principal="${a#--veto=}" ;; esac; done
  [[ -n "$principal" ]] || fail "$E_USAGE" "the solo seal needs --veto=<principal> (e.g. human:main)"
  local resolved; resolved="$(_constitution_resolve_principal "$principal")"
  [[ -n "$resolved" ]] || fail "$E_USAGE" "veto principal '$principal' did not resolve — use human:<agent> (a paired agent) or tg:<user_id>"
  # DIVE-2278: a raw user id is copied verbatim into the SEALED, immutable, publishable bytes.
  if [[ "$principal" =~ ^(tg:)?[0-9]+$ ]]; then
    printf 'warn: --principal=%s puts a raw user id inside the SEALED genesis bytes, which are\n' "$principal" >&2
    printf '      immutable and publishable. Prefer --principal=human:<agent> — same recipient, name in the seal.\n' >&2
  fi

  local genesis_exists=0; [[ -f "$COUNCIL_GENESIS" ]] && genesis_exists=1
  local prev_digest="" seq=0
  if [[ -f "$COUNCIL_LINEAGE" ]]; then
    prev_digest="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.digest // ""' 2>/dev/null)"
    local last_seq; last_seq="$(tail -n1 "$COUNCIL_LINEAGE" 2>/dev/null | jq -r '.seq // -1' 2>/dev/null)"
    [[ "$last_seq" =~ ^[0-9]+$ ]] && seq=$((last_seq+1))
  fi
  local stamped; stamped="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  # CNCL-15: seed the v0 constitution if none exists, then seal its digest INTO the genesis record so
  # a later hand-edit is detectable as drift. `sha256sum` is the one digest realm.
  local cpath; cpath="$(_constitution_path)"
  if [[ ! -f "$cpath" ]]; then
    if ( umask 022; node "$dir/constitution-cli.mjs" constitution-render > "$cpath" ); then
      echo "constitution: seeded v0 -> $cpath" >&2
    else
      rm -f "$cpath" 2>/dev/null || true
      fail "$E_GENERIC" "could not seed the v0 constitution at $cpath — genesis NOT written"
    fi
  fi
  node "$dir/constitution-cli.mjs" constitution --path="$cpath" | jq -e '.valid == true' >/dev/null 2>&1 \
    || fail "$E_VALIDATION" "the constitution at $cpath is not valid — refusing to seal a broken governance file into genesis (fail-closed)"
  local constitution_digest; constitution_digest="$(sha256sum < "$cpath" 2>/dev/null | awk '{print $1}')"
  [[ -n "$constitution_digest" ]] || fail "$E_GENERIC" "could not digest the constitution at $cpath"

  local raw
  raw="$(node "$dir/constitution-cli.mjs" genesis "$@" \
    --registry="$COUNCIL_REGISTRY" --veto-resolved="$resolved" \
    --genesis-exists="$genesis_exists" --prev-digest="$prev_digest" --seq="$seq" \
    --constitution-digest="$constitution_digest" \
    --stamped-at="$stamped")" || return $?

  # Seal the canonical genesis bytes on the ROOT rail, then hash-chain them into the lineage.
  local canonical digest=""
  canonical="$(printf '%s' "$raw" | jq -r '.canonical // empty')"
  [[ -n "$canonical" ]] || fail "$E_GENERIC" "the genesis writer produced no canonical record"
  digest="$(printf '%s' "$canonical" | _constitution_seal_stdin)" || digest=""
  [[ -n "$digest" ]] || fail "$E_GENERIC" "could not seal the genesis record on the gate-proof rail (need root + an enforce key) — genesis NOT written"

  printf '%s' "$raw" | jq --arg d "$digest" '.genesis + {sealedDigest:$d}' > "$COUNCIL_GENESIS"
  printf '%s' "$raw" | jq -c --arg d "$digest" --arg p "$prev_digest" \
    '{seq: .genesis.seq, kind: "genesis", stampedAt: .genesis.stampedAt, digest: $d, prevDigest: $p, canonical: .canonical, record: .genesis}' \
    >> "$COUNCIL_LINEAGE"

  if (( JSON_MODE )); then
    printf '%s' "$raw" | jq --arg d "$digest" '{ok:true, data: (. + {sealedDigest:$d})}'
  else
    echo "constitution: sealed (seq $seq)"
    echo "const:   ${constitution_digest:0:16}… -> $cpath"
    echo "genesis: sealed (${digest:0:16}…) + hash-chained into lineage"
  fi
  return 0
}

# _constitution_verify <runtime-dir> — the lineage verdict `constitution show` reports (and the
# council plugin's `council verify` reaches): the structural chain, every record re-sealing to its
# stored digest on the root rail, and the live constitution matching its sealed digest. Prints the
# {verified, records, chain, chainOk, resealOk, resealBad, constitutionOk, constitution} object;
# returns non-zero on any failure. Read-only.
_constitution_verify() {
  local dir="$1"
  [[ -f "$COUNCIL_LINEAGE" ]] || return 1
  local entries chain_res chain_ok
  entries="$(jq -s -c '[.[] | {seq, prevDigest: (.prevDigest // ""), digest}]' "$COUNCIL_LINEAGE")"
  chain_res="$(node "$dir/constitution-cli.mjs" verify-chain --entries="$entries")"; chain_ok=$?
  local reseal_ok=1 line canonical stored computed n=0 bad=""
  while IFS= read -r line; do
    [[ -n "$line" ]] || continue; n=$((n+1))
    stored="$(printf '%s' "$line" | jq -r '.digest')"
    canonical="$(printf '%s' "$line" | jq -r '.canonical')"
    computed="$(printf '%s' "$canonical" | _constitution_seal_stdin)"
    if [[ -z "$computed" ]]; then reseal_ok=0; bad="seq $(printf '%s' "$line" | jq -r '.seq') (no gate-proof key / not root)"; break
    elif [[ "$computed" != "$stored" ]]; then reseal_ok=0; bad="seq $(printf '%s' "$line" | jq -r '.seq') (canonical does not re-seal to its digest — TAMPERED)"; break; fi
  done < "$COUNCIL_LINEAGE"
  local drift_ok=1 drift_json drift_reason
  drift_json="$(node "$dir/constitution-cli.mjs" drift-check --sealed="$(_constitution_sealed_digest)" --live="$(_constitution_live_digest)" 2>/dev/null)" || drift_ok=0
  drift_reason="$(printf '%s' "$drift_json" | jq -r '.reason // "drift"' 2>/dev/null)"
  local all_ok=1
  [[ "$chain_ok" -eq 0 && "$reseal_ok" -eq 1 && "$drift_ok" -eq 1 ]] || all_ok=0
  jq -nc --argjson chain "${chain_res:-null}" --argjson chainOk "$([[ $chain_ok -eq 0 ]] && echo true || echo false)" \
    --argjson resealOk "$([[ $reseal_ok -eq 1 ]] && echo true || echo false)" --arg bad "$bad" \
    --argjson driftOk "$([[ $drift_ok -eq 1 ]] && echo true || echo false)" --arg driftReason "$drift_reason" \
    --argjson n "$n" --argjson allOk "$([[ $all_ok -eq 1 ]] && echo true || echo false)" \
    '{verified:$allOk, records:$n, chain:$chain, chainOk:$chainOk, resealOk:$resealOk, resealBad:$bad, constitutionOk:$driftOk, constitution:$driftReason, receipt:"skipped"}'
  (( all_ok ))
}
