# ==================== constitution kernel (DIVE-4869) ====================
# CORE-owned read side of the constitution: where constitution.yaml lives, the one parser
# (src/constitution/constitution.mjs, embedded below), and the SEAL — the newest constitutionDigest
# in the council lineage, read as DATA. `task need`'s tier-2 floor and its lead-clear authority call
# these, so they must exist whether or not the council deliberation engine is in the bundle.
#
# Decision (DIVE-4869 body): the seal stays the council lineage file at its existing path, read with
# jq — core needs no council code to trust it, and no box needs a migration. The council engine
# (src/cmd_council.sh) still carries identical `_council_*` copies until it leaves core; the parity
# arm in tests/constitution_kernel_unit.sh fails if the two drift in the meantime.
#
# This file is GENERATED by src/constitution/gen_kernel.mjs from this template plus
# src/constitution/{constitution,cli}.mjs. Edit those and re-run the generator, never the output.

COUNCIL_LINEAGE="${STATE_DIR}/council/lineage.jsonl"

_constitution_path() {
  # An explicit override wins verbatim — no legacy migration on a caller-chosen path.
  if [[ -n "${FIVEDIVE_CONSTITUTION_FILE:-}" ]]; then
    printf '%s' "$FIVEDIVE_CONSTITUTION_FILE"; return
  fi
  local canonical="${STATE_DIR}/constitution.yaml" legacy="${STATE_DIR}/5dive.md"
  # DIVE-1686 belt-and-suspenders for the DIVE-1676 rename: a box ratified BEFORE
  # the rename holds its constitution at the legacy 5dive.md. Do a one-time rename to
  # the canonical name so post-rename builds keep reading it — a rename is byte-preserving,
  # so the sealed-digest drift check still matches. If the rename can't happen (e.g. a
  # non-root reader on root-owned STATE_DIR), fall back to reading the legacy file IN PLACE
  # this call, so the loader NEVER silently reverts to built-in defaults.
  if [[ ! -e "$canonical" && -f "$legacy" ]]; then
    if mv -n "$legacy" "$canonical" 2>/dev/null && [[ -e "$canonical" ]]; then
      echo "constitution: migrated legacy $legacy -> $canonical (DIVE-1676 rename)" >&2
    else
      printf '%s' "$legacy"; return
    fi
  fi
  printf '%s' "$canonical"
}

_constitution_write_runtime() {
  local dir="$1"
  cat > "$dir/constitution.mjs" <<'CONSTITUTION_KERNEL_MJS'
__CONSTITUTION_MJS__
CONSTITUTION_KERNEL_MJS
  cat > "$dir/constitution-cli.mjs" <<'CONSTITUTION_KERNEL_CLI_MJS'
__CONSTITUTION_CLI_MJS__
CONSTITUTION_KERNEL_CLI_MJS
}

# Parse the machine-enforced constitution through the one loader. A function (not a source-time
# global) so test/runtime STATE_DIR overrides resolve correctly.
_constitution_json() {
  ensure_node_on_path || return 1
  local dir rc=0
  dir="$(mktemp -d -t 5dive-constitution.XXXXXX)" || return 1
  _constitution_write_runtime "$dir"
  node "$dir/constitution-cli.mjs" constitution --path="$(_constitution_path)" || rc=$?
  rm -rf "$dir"
  return "$rc"
}

_constitution_hard_gate_rx() {
  _constitution_json | jq -r '.hardGateRegex'
}

# CNCL-15 — constitution integrity. The AUTHORITY is the digest sealed in the newest genesis/
# amendment lineage record, NOT the on-disk constitution.yaml (the file is forgeable, the chain is not).
# Newest record carrying a non-empty constitutionDigest wins (amend > genesis).
_constitution_sealed_digest() {
  [[ -f "$COUNCIL_LINEAGE" ]] || return 0
  jq -r 'select((.record.constitutionDigest // "") != "") | .record.constitutionDigest' "$COUNCIL_LINEAGE" 2>/dev/null | tail -n1
}
# sha256 of the on-disk constitution.yaml ('' if missing) — the live side of the drift comparison.
_constitution_live_digest() {
  local p; p="$(_constitution_path)"
  [[ -f "$p" ]] || return 0
  sha256sum < "$p" 2>/dev/null | awk '{print $1}'
}

# DIVE-1695 — node-free drift verdict for the gate-floor hot path. Returns 0 (DRIFTED, fail closed)
# / 1 (in sync, or no seal to enforce). No sealed digest -> 1; sealed but the live file is missing or
# its digest differs -> 0 (an unsanctioned edit/drop must NOT be enforced).
_constitution_drifted() {
  local sealed live
  sealed="$(_constitution_sealed_digest 2>/dev/null || true)"
  [[ -z "$sealed" ]] && return 1          # no sealed constitution -> nothing to drift from
  live="$(_constitution_live_digest 2>/dev/null || true)"
  [[ -z "$live" ]] && return 0            # sealed but file gone -> drift (fail closed)
  [[ "$sealed" != "$live" ]] && return 0  # sealed but file edited -> drift (fail closed)
  return 1                                 # live matches the sealed digest
}
